.pylintrc
Add a symlink to etc/pylintrc to enable Codacy to pick it up.
=> Add pylintrc symlink for Codacy

bin/improver-tests, tests/bin/bats-exec-test, tests/bin/bats-format-tap-stream, tests/improver-nbhood/00-null.bats, tests/improver-nbhood/01-help.bats, tests/improver-nbhood/02-basic.bats, tests/improver-tests/00-help.bats, tests/improver-tests/01-bad-option.bats, tests/lib/utils
This closes #59.
If an IMPROVER_ACC_TEST_DIR environment is set in the `etc/site-init` file (or elsewhere) (refer to our internal New Developer Guide for details here) then look for a neighbourhood processing specific input file within that directory, run neighbourhood processing on it, produce an output file and compare with a known good file using `nccmp`.
If IMPROVER_ACC_TEST_DIR is not set, skip - same goes for if `nccmp` is not installed.
I have also rationalised the test command a bit - you can now just run a subset of tests with e.g.:
`improver tests cli`
or
`improver tests pep8`
Tests pass with and without the new environment variable in the `etc/site-init` script.
This pull request also adds the functionality to individually test `pep8`, `pylint -E`, `pylint`, `unit` tests, and …
=> Add neighbourhood processing CLI acceptance tests and enhance improver tests interface

bin/improver-tests
Fix the `improver tests` subcommand when `doc` is passed in as an argument (e.g. `improver tests doc`).
The command `improver tests doc` now does something and passes.
=> Fix 'improver tests doc'

bin/improver-ensemble-calibration, lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, tests/improver-ensemble-calibration/00_null.bats, tests/improver-ensemble-calibration/01_help.bats, tests/improver-ensemble-calibration/02_gaussian.bats, tests/improver-ensemble-calibration/03_trunc_gaussian.bats, tests/improver-ensemble-calibration/04_save_mean_and_var.bats
Provides CLI and acceptance tests for ensemble calibration plugins.
Calls EnsembleCalibration plugin and passes output to GeneratePercentilesFromMeanAndVariance and EnsembleReordering to create ensemble members from mean and variance produced. Has option to save mean and variance to file in addition to final ensemble members.
Added CLI AT for: no args, help, gaussian distribution, truncated gaussian distribution, saving out mean and variance.
Issue: #87 
Testing:
=> Ensemble Calibration CLI

bin/improver-tests, tests/improver-tests/00-help.bats, tests/improver-tests/01-bad-option.bats
First attempt to add option to run only one of cli tests. 
Use as: `improver tests cli opt1 opt2 ...` where opt1, opt2 etc are the names of directories in `/improver/tests/` without the `improver-` at the beginning (ex: generate-landmask-ancillary, weighted-blending).
If passed in after another test type, the options will have no effect. Ie: `improver tests pep8 cli nbhood` will run pep8 and ALL cli tests in `/improver/tests/` .
Issue: #144 
Testing:
=> 144: add cli sub-test option

.travis.yml
As a developer I want Improver travis fixed so that my automated tests can pick up real errors!
Currently, travis on master fails due to the removal of biggus from the scitools channel, as Iris 2 does not require it.
This fixes the problem by adding their less-controlled channel just for biggus.
When Iris 2 is out, we should migrate to that ASAP and avoid this.
=> Fix Travis biggus install

.travis.yml
This installs Iris properly from conda, bypassing some of our recent Travis Conda issues.
It should give us a nice recent version of Numpy (a problem with #220) and should be pretty compatible with our current environment.
This should be a lot more resilient (he says, crossing his fingers).
=> Travis bug fix: install Iris properly from conda

bin/improver-tests
Added a use of `find` to identify all python files in the IMPROVER respository, including those in the /bin directory.
Tests fail, awaiting clean up of /bin directory.
=> Extended testing to all python files within IMPROVER.

lib/improver/spotdata/extract_data.py
A bug fix to avoid zeroing valid altitudes set for sites. I had used a nanmin(<num>, 0) to set NaNs to zero if they cropped up. Unfortunately I failed to note that this would obviously set any positive altitude to zero as well. I have now replaced nanmin with nan_to_num which replaces the NaNs with zeros whilst leaving valid entries unchanged.
=> Fix to avoid zeroing valid altitudes.

bin/improver-tests, tests/improver-tests/00-help.bats, tests/improver-tests/01-bad-option.bats
Fiona stumbled across an improver-<plugin>~ file being checked, so I have added an exclusion for files ending in a tilda to the pep8/pylint file check list.
Removed trailing white space from improver-tests and associated bats tests.
=> Exclude temporary tilda files from pep8 and pylint checks.

etc/pylintrc, lib/improver/spotdata/extract_data.py, lib/improver/spotdata/extrema.py, lib/improver/tests/spotdata/spotdata/test_extract_data.py, lib/improver/tests/spotdata/spotdata/test_extrema.py, lib/improver/tests/spotdata/spotdata/test_main.py
#235 
Adding metadata to spotdata cubes, including forecast reference time and forecast period. Also somewhat rewriting cube construction in spotdata in the hope that it can all get factored out to common utilities in a future ticket.
Testing:
=> Metadata added into spotdata (plus rejigging).

bin/improver-threshold, lib/improver/threshold.py, tests/improver-threshold/00-null.bats, tests/improver-threshold/01-help.bats, tests/improver-threshold/02-basic.bats, tests/improver-threshold/03-below_threshold.bats, tests/improver-threshold/04-multiple_thresholds.bats, tests/improver-threshold/05-threshold_units.bats, tests/improver-threshold/06-fuzzy_factor.bats
Issue #98 
A CLI to accept a single or multiple thresholds to apply to a cube. When multiple thresholds are provided it produces a concatenated cube with a threshold dimension coordinate.
Acceptance tests to be added following first review.
=> CLI for threshold plugin

etc/pylintrc
Updates pylintrc so that `pylint -E` in `improver tests` will pass using the latest pylint at our site.
There were quite a few new false-alarm 'membership' issues detected by this version of pylint, stemming from known pylint problems. It looks like pylint will be able to figure this stuff out in the future, but for now I think it is OK to skip them.
Test by removing the PYLINT override in `etc/site-init` and running `improver tests` with/without this change.
=> Update pylintrc file to enable use of up-to-date pylint at our site

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
Added a rounding to ECC to avoid precision errors causing a non-monotonically increasing probability error.
Testing:
=> IMPRO-319 - Precision error rounding.

bin/improver-weighted-blending, lib/improver/blending/weights.py, lib/improver/tests/blending/weights/test_ChooseDefaultWeightsLinear.py, tests/improver-weighted-blending/01-help.bats
A Fix to allow a linear_starting_point of zero to be provided to the weighted-blending plugin.
Testing:
=> Weighted-blending with a 0 linear_starting_point.

bin/improver
Make location of IMPROVER site-init file configurable through environment, so it can be changed for read-only installations of IMPROVER.
=> make location of IMPROVER site-init file configurable through environment

tests/bin/bats-exec-test
Additional echo statement to give information about the failure of a bats test when run with the --debug flag.
Testing:
=> CLI debug info extension

bin/improver-tests
As discussed in the Developer Catch-up, this removes the unnecessary use of wildcards in the globbing of CLI test names. This branch has been branched from the branch used in #312 to allow easier testing, therefore this branch shouldn't be merged until #312 has been merged. Only the final commit within the PR is relevant.
Testing:
=> Remove unnecessary globbing in CLI tests

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
Increase the rounding of the from 10 decimal places to 9 decimal places, based on test runs for temperature post-processing, which failed if rounding was done to 10 decimal places, rather than 9 decimal places.
This is essentially an adjustment of #288. 
Testing:
=> Increase decimal place rounding within Ensemble Copula Coupling

lib/improver/tests/nbhood/nbhood/test_BaseNeighbourhoodProcessing.py
The cubes produced by our unit tests cannot be plotted by iris.quickplot because they do not have a coordinate system defined. This makes investigating the behaviour of tests more difficult and is fairly simple to fix.
I have added a unit test to test that the cube can be interpolated onto another. This test fails without a coord_system on both source and destination cube.
Testing:
=> Add coord reference system to set_up_cube

lib/improver/tests/utilities/test_rescale.py, lib/improver/utilities/rescale.py
For #263 
This PR adds a linear rescaling function to the utilities area. This has come from work on a nowcast lightning plugin (in work stream for next FY). Links to this can be found on the JIRA ticket and this has been reviewed once by Gavin, but not in an IMPROVER context.
The intention is to use this function to calculate probability-of-event based on fuzzy thresholds supplied as lower, mid and upper bounds.
Testing:
=> Adds rescale function to utilities with unit tests for #263.

lib/improver/nbhood/recursive_filter.py, lib/improver/tests/nbhood/nbhood/test_RecursiveFilter.py
Adds the capability to run a recursive filter to convert a square neighbourhood into a Gaussian-like kernel or simply to smooth over short distances. The recursive filter uses an "alpha" parameter that controls what proportion of stuff (probability) is passed along to the next grid square. 
Implementation  allows the alpha parameter to be set on a grid square by grid square basis (e.g. an array of alpha parameters equivalent in dimensions to the domain). Each grid square has a pair of alpha parameters to allow for orthogonally discrete functionality, e.g. one to act in the N-S direction, and another to act in the E-W direction.
Testing:
=> Impro 176 recursive filter

bin/improver-threshold, lib/improver/tests/threshold/test_BasicThreshold.py, lib/improver/threshold.py, tests/improver-threshold/00-null.bats, tests/improver-threshold/01-help.bats, tests/improver-threshold/07-fuzzy_bounds.bats
2nd PR from #263  (1st PR is #333).
This PR adds the option to specify fuzzy bounds to the threshold plugin and CLI. 
The changes are backward-compatible so any existing uses do not need updating unless they wish to benefit from this change.
Testing:
=> Adds fuzzy bounds option to threshold plugin and CLI for #263.

bin/improver-percentile, tests/improver-percentile/00-null.bats, tests/improver-percentile/01-help.bats, tests/improver-percentile/05-number_of_percentiles.bats
Updated percentile CLI to accept a number of percentiles as an optional argument. This then uses the ecc choose_set_of_percentiles function to produce the list of percentiles that will be generated.
Implemented to remove some hard coding in a patch script implemented in IMPRO-336.
Testing:
=> Updated percentile CLI to accept a number of percentiles

lib/improver/nbhood/recursive_filter.py, lib/improver/tests/nbhood/nbhood/test_RecursiveFilter.py
An additional exception for when alpha is set in two ways in the plugin. An additional unit test for this exception and multiple fixes to recursive filter unit tests missed in review.
Testing:
=> Recursive filter fixes

lib/improver/generate_ancillaries/generate_ancillary.py, lib/improver/tests/generate_ancillaries/test_GenerateOrographyBandAncils.py
Bug occured when there were no sea points in the input landsea mask.
Added a new unit test to check this works.
Testing:
=> Fixed a bug in generation of topography masks

lib/improver/nbhood/square_kernel.py, lib/improver/tests/nbhood/square_kernel/test_SquareNeighbourhood.py, lib/improver/tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py
Edit so that if division within neighbourhood processing results in a non-finite number, then this number is set to NaN, rather than zero. This is for the purposes of the triangular weighting that will need to be done to collapse the topographic band coordinate, as a NaN will indicate that there are no values within a topographic zone, so the triangular weighting will be adjusted to only include topographic zones with values within the weighting.
#283 
Testing:
=> Set division to NaN in Neighbourhood Processing

lib/improver/tests/utilities/test_OccurrenceWithinVicinity.py, lib/improver/utilities/spatial.py
#145 implemented the OccurrenceWithinVicinity plugin.
The process method states that it will ensure that 2D slices are passed to to the maximum_within_vicinity method, but it only slices_over realization and time coordinates.
This PR replaces the slices_over statements with a slices statement to explicitly select slices over y and x only. This allows the plugin to work when other coordinates are present, such as threshold.
Without this bug-fix, the plugin appears to work successfully, but returns the maximum value across each additional dimension as well as x and y.
I have also included an additional comment to try to make it clearer that this plugin uses a square kernel to find the maximum value in the vicinity.
The existing tests seem adequate to cover this change so I have not added …
=> Fixes a bug in selecting 2D slices in OccurrenceWithinVicinity.

lib/improver/threshold.py
As agreed at the developer catch-up session, the code style for docstrings showing the arguments to the class __init__ method is correct. This PR moves the docstring for the one known offending plugin.
Testing:
=> Moves argument descriptions in docstring

lib/improver/blending/weighted_blend.py, lib/improver/utilities/temporal.py
Added statements to preserve input precision when calculating new forecast reference times and forecast periods using the conform metadata utility and associated utilities in temporal.py.
New acceptance test data due to type change; location available from me.
Testing:
=> Coordinate precision preservation in conform_metadata

lib/improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py, lib/improver/wind_gust_diagnostic.py
The current wind_gust_diagnostic code will not cope with wind-gust data which is max over the hour. This data reports mid-point in period so the time is 1/2 past the hour and forecast period is ?.5. The data will not match up with the instantaneous wind-speed data and so can not be merged into the same cube as the code currently stands. This change makes use of the CubeCombiner code to resolve the issue with max wind-gust data.
Testing:
New CLI data is required as the old version loses _FillValue when the cube is collapsed.
=> Fix to the wind-gust diagnostic (IMPRO 361)

bin/improver-snow-falling-level, lib/improver/tests/utilities/test_load.py, lib/improver/utilities/load.py
Snow falling level can take over an hour to run for a single lead time with input NetCDF with realization, height, x, y sizes of roughly 12, 30, 1000, 1000.
Profiling shows this is mainly (3000 seconds) due to inefficiencies in accessing the cube data,
with the rest being mainly numpy griddata interpolation.
We've seen this kind of problem before, so I think it would be good to have a generic solution.
This modifies our load wrapper to allow the option of disabling of Iris 1's lazy loading, at a cost in memory. Individual calls to the CLI are now ~4 times faster, although we can only run around half as many as once given the memory increase - so an increase of x2 from a suite point of view.
It looks like porting to Iris 2 (rc1) is non-trivial - there are now some interesting unit test …
=> snow falling level: no lazy load for speed

.travis.yml
Updated numpy version on Travis to be 1.13.3. See IMPRO-481.
Testing:
=> Updated numpy version on Travis to be 1.13.3.

lib/improver/spotdata/extract_data.py, lib/improver/tests/spotdata/spotdata/test_extract_data.py, lib/improver/threshold.py
Refactoring to remove make_stat_coordinate_first function, in favour of more generic enforce_coordinate_ordering function.
Issues: #384 
Testing:
=> Retire make_stat_coordinate_first

etc/pylintrc, lib/improver/tests/utilities/test_save.py, lib/improver/utilities/save.py
Generic save wrapper to save dataset-specific attributes as non-global attributes in netcdf files.
Substantial amount of CLI test output needs updating for this change.
Testing:
Related issue #393
=> Impro426: use of local_keys to restrict netcdf global attributes

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py
Added ecc bounds for precipitation accumulations to ensure we can produce output for verification from this diagnostic.
IMPRO-415
Testing:
=> IMPRO-415 - ECC bounds for precipitation accumulation

CONTRIBUTING.md
This adds contributing guidance and a contributor licence agreement (CLA). This allows external contributors to contribute code under our open-source licence.
It adds all contributors who have made non-merge commits to master as of this date.
Future and upcoming new contributors must add their names to the file as part of their first pull request.
=> Add contributing guidance and CLA

.travis.yml
Set sphinx version to remain at 1.7.0 (it changed to 1.7.1 over the weekend and seems buggy) and consolidate numpy install statement into single conda line (which seems to remove the seg fault issue we have been seeing).
=> Sphinx 1.7.1 Fix

lib/improver/blending/weighted_blend.py, lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
The iris aggregate method always moves the dimension being collapsed to the -1 index position. This is hardcoded in iris. As the percentile aggregator stands it works out the percentile coordinate index (perc_dim) before this happens, and then uses it after it happens. As such the np.moveaxis that occurs in the top of our custom aggregate function within PercentileBlendingAggregator gets a bit confused and the data array ends up oddly shaped. This PR addresses this issue.
This is not picked up in the acceptance tests as the percentile coordinate precedes the coordinate being collapsed in the input data, thus moving the latter does not affect the index of the former. We could consider capturing this, but once it is fixed it is probably not necessary.
Testing:
=> Fix to coordinate reordering in PercentileAggregator

environment.yml
Reverts metoppv/improver#448
This change had to be merged to test its efficacy. It did not fix our problem, so I am removing the change.
=> Revert "Update environment.yml"

lib/improver/tests/threshold/test_BasicThreshold.py, lib/improver/threshold.py
Changes to ensure float precision is preserved within the thresholding app. Additionally, ensures integer inputs become float32 output cubes to allow for fuzzy thresholding.
Unit tests added to check conservation/conversion. Requires updated KGO, though no new tests were added.
IMPRO-505 / #434 
Testing:
=> IMPRO-505: ensure output is float32 not double

bin/improver-wind-downscaling
The extract_subcube function now includes a call to parse the constraints, which are set explicitly within this CLI. As such we should now be calling apply_extraction, and we must modify the constraints input to be a set of iris constraints, rather than a dictionary.
Testing:
=> IMPRO-522: Bug fix for altered extract subcube plugin usage in wind-downscaling.

doc/source/conf.py, doc/source/index.rst, lib/improver/utilities/ancillary_creation.py, lib/improver/utilities/cube_extraction.py
Fixes to warnings raised by recently committed code that did not adhere to sphinx formatting requirements. Additionally, modified sphinx config to remove remaining warnings/errors that have always been raised. I have also added a modules/subpackages section to the front page of the docs.
Testing:
=> Sphinx changes and docstring fixes

lib/improver/tests/utilities/test_load.py, lib/improver/utilities/load.py
Correction to rename coordinate to be reordered to threshold, rather than probability. Two unit tests have been added to test the reordering of a percentile_over coordinate and a threshold coordinate.
Testing:
=> Fix enforcing of probability coordinate within load_cube

lib/improver/nbhood/circular_kernel.py, lib/improver/tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py
Reference issue: #415 
As an IMPROVER developer I want to be able to generate percentiles from a neighbourhood for a single percentile so that I can, for example, generate a wind gust diagnostic successfully, where I want to focus on processing a single percentile.
Currently, it is the case that when using the generate percentiles from a neighbourhood code with a single percentile value there is a shape mismatch due to the promotion/demotion of what effectively becomes a scalar coordinate within pad_and_unpad_cube function. This needs to be fixed, so that the wind_gust_diagnostic processing chain can complete properly.
This PR fixes the bug.
Testing:
CLA
=> 415 Generate percentiles from a neighbourhood for a single percentile

.travis.yml
Attempt to avoid iris.fileformats.grib deprecation warning, which breaks current CLI tests.
=> Fix iris.fileformats.grib Travis warning

bin/improver-combine, tests/improver-combine/02-basic.bats, tests/improver-combine/03-metadata.bats, tests/improver-combine/04-min-temp.bats, tests/improver-combine/05-max-temp.bats, tests/improver-combine/06-accumulations.bats, tests/improver-combine/07-mean-temp.bats
Removal of globbing from improver-combine by allowing wildcard expansion on command line.
Reference issue: #409 
Testing:
=> Edit improver-combine so that wildcard expansion occurs within shell

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/spotdata/extrema.py, lib/improver/spotdata/read_input.py, lib/improver/tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py, lib/improver/tests/spotdata/spotdata/test_extract_data.py, lib/improver/tests/spotdata/spotdata/test_read_input.py, lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py
GitHub Issue #477
Testing:
Following unittests now run:
* test_wrong_size_coords (tests.blending)
* test_invalid_extraction_time (tests.spotdata)
* test_invalid_time (tests.utilities)
* test_negative_forecast_periods_warning (tests.utilities)
Note that these changes are not backward compatible with Iris 1.13.0 due to the removal of `iris.FUTURE.context(cell_datetime_objects=True)` statements and unit test regex matching to changed Iris2 error messages.
=> Impro 570 fix iris2 unittests2

tests/improver-probabilities-to-realizations/02-basic.bats, tests/improver-probabilities-to-realizations/03-12_realizations.bats
Simply moving the input.nc file down into the /basic directory to keep the structure consistent with other tests.
=> Acceptance test tweak

.travis.yml
Hardcode netcdf4 version, as netcdf4 version 1.4.0 currently breaks Iris, as the netcdf4 module no longer contains netcdftime, which has been factored out into a separate package.
Testing:
=> Hardcode netcdf4 version, so that netcdftime is still included

bin/improver-extract, bin/improver-generate-topography-bands-mask, bin/improver-generate-topography-bands-weights, tests/improver-extract/01-help.bats, tests/improver-extract/09-ignore-failure.bats, tests/improver-generate-topography-bands-mask/06-multi-realization.bats, tests/improver-generate-topography-bands-weights/06-multi-realization.bats
Adds ignore failure option to cube extract to return input if constraints are not matched; useful for e.g. applying realization extraction to a cube of unknown origin which could be determinitistc. Also modified topographic band generation CLIs to work on an x-y slice in case there are leading dimensions of time/realization etc.
Added bats tests to relevant CLIs.
IMPRO-436
Testing:
=> IMPRO-436: Changes to CLIs for use in importing ancillaries

lib/improver/database.py, lib/improver/tests/database/test_SpotDatabase.py
Master is currently failing on Travis due to the latest version of pandas (0.23.0) removing the flavor argument for pandas.io.sql.get_schema: https://github.com/pandas-dev/pandas/commit/5a926a7d1d9041749c1cd8f73e4e5e3cc5a7f360#diff-b41f9fd042c423682f8e4c4d808dbe64. This argument is no longer needed as 'sqlite' was the only supported flavor anyway.
Testing:
=> Removed use of deprecated flavor argument within pandas

bin/improver-gradient
Addresses #538 , #439 
Description:
Edit to force the gradient CLI to convert a tuple to a cubelist, as save_netcdf expects to be handling cubelists.
Testing:
=> Fix the gradient CLI to pass a CubeList to save_netcdf

bin/improver-regrid, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/utilities/cube_metadata.py, tests/improver-regrid/00-null.bats, tests/improver-regrid/01-help.bats, tests/improver-regrid/02-basic.bats, tests/improver-regrid/03-nearest.bats, tests/improver-regrid/04-extrapolate.bats
A wrapper to iris regrid functionality; initial use case if regridding radar data. Includes a new utility to use a pattern to delete attributes from a cube; this is used to delete StaGE derived grid descriptors which become incorrect once a grid is regridded.
Testing:
=> IMPRO-618: Grid to grid interpolation

bin/improver-tests
Related to #558 
Description: As part of #558, it was helpful to run the unit tests with the verbose option enabled, so that it was possible to know which unit test was generating the warnings that were being raised. This PR makes use of the existing ability to specify a `--debug` option, so that this option is passed to the call to `unittest discover` and verbose unit test output is enabled.
Testing:
=> Add support for providing a verbose option for the unit tests

.travis.yml, bin/improver-tests
This is aimed at #580.
This should add code coverage results to Codacy, at least for master (so we can view current and past coverage info). Incoming PRs from non-metoppv forks are hit by https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions and won't work with this.
Follows https://support.codacy.com/hc/en-us/articles/207279819-Coverage and https://github.com/codacy/python-codacy-coverage#setup.
I've added the token to our Travis setup, suitably securely: https://travis-ci.org/metoppv/improver/builds/386636363#L422
and the coverage uploads OK:
https://travis-ci.org/metoppv/improver/builds/386636363#L1987
=> Code coverage reporting for master

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/ensemble_calibration/ensemble_calibration_utilities.py, lib/improver/tests/ensemble_calibration/ensemble_calibration_utilities/test_ensemble_calibration_utilities.py
Removal of renaming of coordinates within ensemble calibration, as this functionality is not used, as no input is provided with ensemble_member_id or ensemble_realization_id as a coordinate. This functionality existed to support an old input format that no longer needs to be supported.
Addresses #543 
Description:
As part of some clean up following the implementation, there is no need for ensemble calibration to support the existence of an `ensemble_realization_id` coordinate. Ensemble calibration uses the realization coordinate, however, support for `ensemble_member_id` was previously added to support an old input format.
Testing:
=> Removal of usage of ensemble_realization_id coordinate in ensemble calibration

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GenerateProbabilitiesFromMeanAndVariance.py, lib/improver/tests/utilities/test_cube_checker.py, lib/improver/utilities/cube_checker.py
A plugin to generate probabilities from the mean and variance of a parameter distribution at a list of thresholds provided by a template cube. The code has been structured in this way as we will have an input probability cube that will contain the thresholds and metadata that we want in the output.
Testing:
=> IMPRO-639: GenerateProbabilitiesFromMeanAndVariance plugin

bin/improver-tests, doc/source/conf.py, lib/improver/tests/nbhood/recursive_filter/test_RecursiveFilter.py, lib/improver/tests/wind_downscaling/test_FrictionVelocity.py, tests/improver-tests/00-help.bats, tests/improver-tests/01-bad-option.bats
Addresses #6 
Description
Add a test to check whether the desired licence information is present within each file. This test runs alongside the existing tests e.g. pycodestyle, pylintE to ensure that the licence information is recorded correctly. Files where the licence information did not match the expected licence information have been updated.
Testing:
=> Add test for licence information

bin/improver-snow-falling-level, lib/improver/psychrometric_calculations/psychrometric_calculations.py, lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py, tests/improver-snow-falling-level/00-null.bats, tests/improver-snow-falling-level/01-help.bats, tests/improver-snow-falling-level/02-basic.bats
Addresses #511 
Updating to use land-sea mask rather than orography to determine sea points.
Testing:
CLA
=> Impro 621 improve snow

lib/improver/nowcasting/optical_flow.py, lib/improver/tests/nowcasting/optical_flow/test_AdvectField.py, lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py, lib/improver/threshold.py
Addresses #571 
Description
Edits to optical flow to add a warning being raised, if an excess of zero values is calculated within the advection velocities. At the moment, the threshold for when a warning is raised is hard-coded within `optical_flow.py`. This could be modified, if this is desirable.
Testing:
=> Add warning if too many zero values for advection velocities

lib/improver/nowcasting/optical_flow.py, lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py
Addresses #571 
This warning should only be raised where there is rain - we expect all other advection velocities to have a zero (or "no data") value.
Testing:
=> IMPRO722 part 2: added "in rain" condition

doc/source/conf.py
Following #591.
Description
This PR switches the use of pngmath, which is a deprecated Sphinx extension for mathjax, which appears to display correctly locally. mathjax has been used in preference to imgmath, as the usage of imgmath led to a number of LaTeX related error messages when run locally.
Reference to maths support within Sphinx: http://www.sphinx-doc.org/en/stable/ext/math.html.
Testing:
=> Sphinx: Swap pngmath for mathjax, as pngmath is deprecated.

CONTRIBUTING.md, lib/improver/tests/utilities/solar/test_solar.py
Description
Fixed docstrings in test_solar.py so that they better reflect what each test does.
Testing:
CLA
=> Fix solar unit tests docstrings

lib/improver/tests/wind_direction/test_WindDirection.py, lib/improver/wind_direction.py
Addresses #495 
Refactors wind direction code to make implementation of IMPRO 598 easier.
One unit test is slightly modified at the 3rd significant figure, otherwise functionality is unchanged.
Testing:
=> Refactors wind direction code to make implementation of IMPRO 598 easier

tests/improver-threshold/06-fuzzy_factor.bats
Changed fuzzy_factor test to give a field demonstrating the effect. Previously, as the fuzzy factor was too large, it gave a huge range in kelvin that encompassed all the data, making the output look like the unthresholded input.
Fuzzy factor changed to give a much smaller range.
Acceptance test data linke to from IMPRO-408
Testing:
=> Change to threshold fuzzy factor acceptance test to make it useful.

tests/improver-spot-extract/02-nearest.bats, tests/improver-spot-extract/03-model_level.bats
Updated spot-data tests to use real UKV data and to select sites over the UK. Turned off testing of the extrema value extraction as this will not be used and has some bugs in it; we will instead select min/max temperatures from a field of such values.
IMPRO-434
=> Update spot-data acceptance test data to use something real.

lib/improver/nbhood/square_kernel.py, lib/improver/tests/nbhood/square_kernel/test_SquareNeighbourhood.py, lib/improver/tests/wind_direction/test_WindDirection.py, lib/improver/wind_direction.py
Addresses #495 
Adds a new (and default) backup method for most-likely wind direction to sample the local neighbourhood as well as other ensemble members when the derived wind direction comes with low confidence.
Follows PR #592
Testing:
=> Adds neighbourhooding to wind direction as a backup

requirements.txt
Addition of a requirements.txt file such that github can show the necessary library dependiencies. Currently excludes default modules like scipy/numpy.
This feels like an omission on our part, so I thought I would add this requirements file to help collaborators ascertain what they need to run IMPROVER. We may wish to include version information, and it's possible I have missed a library/module or thought something is a standard library that is not (e.g. sqlite3).
=> Addition of library/module requirements file.

lib/improver/tests/utilities/test_load.py, lib/improver/utilities/load.py
Addresses IMPRO-734
When testing the triangular blending in the suite we realised that if the history attributes are different then the load function fails. These changes address this problem.
Testing:
=> Modification to the load function to handle merging cubes with different history attributes

tests/improver-nbhood-land-and-sea/11-topographic_bands_probs.bats
Helps towards #583.
This adds a new BATS test for nbhood-land-and-sea that covers probabilities over thresholds. I've taken  input screen temperature data from our deterministic UK model, and run it through improver threshold with only 4 thresholds to make it not quite so slow...
Data in the usual central place.
Testing:
=> Add BATS test for topographic band probability nbhooding

lib/improver/ensemble_calibration/ensemble_calibration_utilities.py
Replace masked points with nans to avoid the use of fill values in further processing. This is to avoid issues with precision leading to different behaviours.
Testing:
=> ECC: Masked data replaced with nans to avoid processing fill values

.travis.yml
Travis has started failing for some PRs. (e.g. #653 )
Fixing the pylint version in Travis to 1.9.1 resolves this problem, so this PR applies this change.
Testing:
=> Selects pylint version 1.9.1 to fix Travis.

bin/improver-tests
Speeds up prove-run CLI BATS tests by using prove's parallel option.
This number of tests at once seems to fit just about OK within the memory we typically have here for our current test data. Memory use gets a bit spiky with some of the nbhood tests!
Testing:
=> Run multiple CLI tests at once

.travis.yml
Force numpy version with iris install.
Attempt to change the iris version associated with iris back to a version below 1.14. Currently the conda defaults channel has upgraded to 1.15, which is breaking our tests.
=> Force iris 2.0 to use earlier version of numpy

bin/improver-tests, tests/improver-tests/00-help.bats, tests/improver-tests/01-bad-option.bats
Allows running a single CLI test from the command line.
This saves quite a bit of time when you have a problem with a
particular test in a slow category like nbhood.
Testing:
=> Add facility for running a single CLI test

doc/source/conf.py, lib/improver/convection.py, lib/improver/nbhood/square_kernel.py, lib/improver/utilities/cube_manipulation.py
Add the inclusion of doc strings relating to private functions into the documentation. Fix the issues identified by warnings that arise with this change.
I noticed that they are missing with the addition of the orographic_enhancement plugin which includes lots of private functions.
Testing:
=> Private function doc-strings in documentation

lib/improver/tests/utilities/cube_manipulation/test_demote_float64_precision.py
Description
Following rebasing the feature branch on upstream/master, the demote_float64_precision unit tests failed, as a result of a change to the default dtype used within the set_up_temperature_cube helper function. This PR sets the dtype to be float64 for the purposes of these unit tests.
Testing:
=> Specify dtype of float64 in unit test for demote_float64_precision

bin/improver-tests
Description
Enable the debug option for the CLI tests to run CLI tests serially, as running serially provides more verbose output messages, which are useful for debugging. The debug option would only typically be used when trying to debug a specific set of CLI tests.
Testing:
=> Enable serial running of CLI tests with debug option

bin/improver-nbhood-land-and-sea, lib/improver/nbhood/use_nbhood.py, lib/improver/tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py, tests/improver-nbhood-land-and-sea/11-topographic_bands_probs.bats
Contributes towards #583 and closes #473.
This should go in after #637, which gives a proper control result for this to be proved against.
This speeds up masked neighbourhood processing, particularly when probabilities are sometimes the same from one threshold to the next (e.g. for very low or very high thresholds).
One speedup comes from non-lazy-loading the weights and masks cubes in nbhood-land-and-sea (#473). These are small enough not to make a real difference to memory, and otherwise get read in repeatedly, incurring an I/O cost in elapsed time. This is definitely a worthwhile thing to switch off.
The other result comes from reusing the previous neighbourhood processing result when the previous input is the same as the current one. This is true when we take 2D slices over thresholds …
=> Speed up serial performance of masked nbhood

lib/improver/nowcasting/optical_flow.py, lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py
Addresses #638 
Two functional changes:
- Changed radius to be set explicitly rather than iteratively modified every time "process" is called
- Set radius to increase for larger time offsets but NOT to decrease for smaller offsets (this is justified separately)
Testing:
=> Impro858 optical flow radius bug

tests/improver-nowcast-extrapolate/04-metadata.bats
After PR's #679 and #673 went in, the AT data associated with PR #633 was out of date.
I didn't notice this when merging (my bad), so I've updated the AT data and the test coverage.
Testing:
=> Add KGO0 to nowcast-extrapolate with metadata BATS test

lib/improver/nbhood/circular_kernel.py, lib/improver/tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py
Description:
Update metadata in circular_kernel.py
percentile_over_neighbourhood rather than
percentiles_over_neighbourhood.
Testing:
=> IMPRO586 Update metadata in circular_kernel.py

lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_RebadgePercentilesAsMembers.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py, lib/improver/tests/wind_calculations/wind_gust_diagnostic/test_WindGustDiagnostic.py
Description : Changing percentile_over_nbhood to percentile_over_neighbourhood in unit tests.
Testing:
=> IMPRO586 percentile metadata - update percentile_over_nbhood

bin/improver-ecc, bin/improver-percentile, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py, lib/improver/percentile.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ensemble_copula_coupling_utilities.py, lib/improver/tests/percentile/test_PercentileConverter.py, tests/improver-ecc/00-null.bats, tests/improver-ecc/01-help.bats, tests/improver-ecc/04-percentiles_rebading_extra_option.bats, tests/improver-percentile/01-help.bats
Also other minor changes to get suite to work
Addresses IMPRO-912
When using the ECC CLI to convert percentiles to members for global data there were a few things that needed changing. This included removing the collapsed scalar coordinate when using members_to_percentiles and changing the ECC bounds to be suitable for global data.
Testing:
=> Remove scalar coordinates after collapsing with percentiles.

lib/improver/utilities/temporal.py, tests/improver-weighted-blending/02-basic_nonlin.bats, tests/improver-weighted-blending/03_basic_lin.bats, tests/improver-weighted-blending/05_options_nonlin.bats, tests/improver-weighted-blending/06_options_lin.bats, tests/improver-weighted-blending/07_coord_adj.bats, tests/improver-weighted-blending/11-expected-coord-vals.bats, tests/improver-weighted-blending/12-percentile_blending.bats, tests/improver-weighted-blending/13-weighted_max.bats
Change to CLI tests for weighted blending so that this simulates cycle blending (ie across forecast_reference_time rather than time).  This provides a better baseline for testing of #658 and is a prerequisite.
New CLI test inputs and outputs are referenced in the Jira ticket.
Testing:
=> Update weighted blending tests

.travis.yml
Travis versions aligned with October 4th scitools/experimental-current stack for iris2.1.
Testing:
=> Travis package versions update for iris 2.1

lib/improver/spotdata_new/neighbour_finding.py, lib/improver/tests/spotdata_new/spotdata_new/test_NeighbourSelection.py, lib/improver/utilities/spatial.py
A new plugin for neighbour finding as part of the spot data redesign. Allows selection of neighbours using constraints in different combinations and returns a cube of neighbours for use later at the data extraction step.
There is an associated notebook to go with this PR. See improver_aux.
Testing:
=> IMPRO-875: Spot data neighbour finding plugin

requirements.txt
Fix to requirements.txt to remove dependency on linkedin/iris and replace with scitools/iris.
Testing:
- No testable features changed.
=> Requirements.txt dependency fix - point at scitools instead of linkedin.

.travis.yml
Force cftime module back to version under which our unit tests pass. Ticket opened to look at changes that occur under 1.0.2.1 which cause the failures.
Testing:
=> CFTime Version reset to 1.0.1 for Travis

lib/improver/blending/weighted_blend.py, lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py
Addresses #658
When running a blend-models configuration of improver-weighted-blending, which requires the forecast_reference_time and forecast_period coords to be recalculated, the dtype of those coords is not preserved. This causes a fault in the pre-verification task because the precision is not suitable for integer-comparison.
This PR inherits the dtype from the input coord and sets this again at the end of each relevant function.
Testing:
=> Correctly inherit time coord dtypes

bin/improver-neighbour-finding, lib/improver/argparser.py, lib/improver/spotdata_new/neighbour_finding.py, lib/improver/tests/argparser/test_safe_eval.py, lib/improver/tests/spotdata_new/spotdata_new/test_NeighbourSelection.py, lib/improver/utilities/load.py, tests/improver-neighbour-finding/00-null.bats, tests/improver-neighbour-finding/01-help.bats, tests/improver-neighbour-finding/02-nearest-uk.bats, tests/improver-neighbour-finding/03-nearest-land-constraint-uk.bats, tests/improver-neighbour-finding/04-nearest-minimum-dz-uk.bats, tests/improver-neighbour-finding/05-nearest-land-constraint-minimum-dz-uk.bats, tests/improver-neighbour-finding/06-all-methods-uk.bats, tests/improver-neighbour-finding/07-nearest-global.bats, tests/improver-neighbour-finding/08-nearest-land-constraint-global.bats, tests/improver-neighbour-finding/09-nearest-minimum-dz-global.bats, tests/improver-neighbour-finding/10-nearest-land-constraint-minimum-dz-global.bats, tests/improver-neighbour-finding/11-all-methods-global.bats, tests/improver-neighbour-finding/12-alternative-site-coordinate-system.bats, tests/improver-neighbour-finding/13-incompatible-constraints.bats, tests/improver-neighbour-finding/14-different-grid-metadata.bats
This PR adds a CLI and associated tests for the neighbour finding plugin. This allows users to build cubes of grid point neighbours that can be used to extract gridded data to represent off-grid spot sites.
Testing:
=> IMPRO-877: Spot data neighbour finding CLI

tests/improver-weighted-blending/06-options_lin.bats, tests/improver-weighted-blending/11-cycletime.bats
Addresses #713 
Changed parameters for the cycle blending tests that use the "ChooseDefaultWeightsLinear" plugin so that more recent forecasts receive a higher weighting.
=> Updated cycle blending tests to have sensible weights

lib/improver/tests/utilities/cube_manipulation/test__equalise_coord_bounds.py, lib/improver/utilities/cube_manipulation.py
Addresses #700 
Testing:
I have looked at cube_manipulation.py and changed the functionality of _equalise_coord_bounds slightly. This was doing most of what we wanted it to do, but if there was a cube which didn't have bounds, and one that did, it would get rid of the bounds. This was a historic fix, which after discussion with Stephen Moseley we realised we didn't need. So this functionality has been taken out.
There were unit tests to cover some of the work already, but I have updated and added to the unit tests within test_equalise_coord_bounds. This should run as required. The unit tests now cover these cases (for both the coordinate 'time' and also 'forecast_period':
- Where the cubes have identical bounds
- Where none of the cubes have bounds
- Where the cubes have mismatched bounds …
=> Changes to make sure that time bounds are preserved in the correct way.

lib/improver/nowcasting/lightning.py, lib/improver/spotdata/extrema.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py
Changes to temporal.py for usage in the future addition of the orographic enhancement to the extrapolate and optical-flow CLIs.
Addresses #169 
Description
Factored out the changes required to temporal.py from #726, so that #726 can be made simpler.
Primarily this PR factors out the nearest time point extraction capability from lightning.py into a separate function with unit tests. The dt_to_utc_hours function is modified to be datetime_to_iris_time for usage in the new extract_nearest_time_point function.
Testing:
=> Temporal.py changes to support orographic enhancement

lib/improver/lapse_rate.py, lib/improver/tests/lapse_rate/Test_LapseRate.py
Addresses #731
Fix temperature lapse rate plugin after a number of issues came to light as a result of #732 
**Plugin:**
- Ensure units of the output lapse rate cube are set to `'K m-1'`.
- Ensure that specifying a maximum lapse rate smaller than minimum lapse rate produces an error.
- Ensure that specifying a neighbourhood radius of less than zero produces an error.
- Ensure that specifying a maximum height difference of less than zero produces an error.
**Additional unittests:**
- Test that the output cube units are `'K m-1'`regardless of wether or not default arguments are used.
- Test that a maximum lapse rate less than the minimum produces an error.
- Test that a maximum height difference of less than zero produces an error.
- Test that a neighbourhood radius less than zero produces …
=> Fix temperature lapse rate plugin to add lapse rate units and add extra unit tests.

bin/improver-time-lagged-ensembles, tests/improver-time-lagged-ensembles/00-null.bats, tests/improver-time-lagged-ensembles/01-help.bats, tests/improver-time-lagged-ensembles/02-basic.bats, tests/improver-time-lagged-ensembles/03-validity-error.bats, tests/improver-time-lagged-ensembles/04-single-cube.bats
Addresses #711 
Description
Testing:
I have created a CLI to make use of the time-lagged ensemble plugin that had already been created in a previous ticket. It should:
- Call the GenerateTimeLaggedEnsemble from improver.utilities.time_lagging
- Use this plugin on a list of files that have the same validity time, but can be from different cycles
-  If it is used on files with different validity times an Error will occur
I have also written some basic CLI tests for this to check it is working properly. I created the CLI data, but using the plugin, generating a cube from this and then saving it to a NetCDF file. I was then able to compare this file to one created by using my new CLI, which I have documented in a jupyter notebook.
=> Created CLI for time-lagged ensemble plugin and added CLI tests.

bin/improver-standardise, lib/improver/tests/utilities/test_RegridLandSea.py, lib/improver/tests/utilities/test_cube_checker.py, lib/improver/utilities/cube_checker.py, lib/improver/utilities/spatial.py, tests/improver-standardise/00-null.bats, tests/improver-standardise/01-help.bats, tests/improver-standardise/03-regrid_nearest.bats, tests/improver-standardise/04-regrid_extrapolate.bats, tests/improver-standardise/09-check_output_filepath.bats, tests/improver-standardise/10-regrid_nearest_landmask.bats, tests/improver-standardise/11_check_landmask_input.bats, tests/improver-standardise/12-args_error_landmask_present.bats, tests/improver-standardise/13-args_error_no_target_with_landmask.bats, tests/improver-standardise/14-args_error_no_landmask_file.bats
Addresses #719 
Adds a plugin to update a regridded cube around coastlines to ensure that output sea-points use input sea-point data (where possible) and vice-versa.
Adds options to the improver-standardise CLI to use this plugin.
Testing:
=> Impro977 landsea regridding

tests/improver-nbhood/05-mask-square.bats
nccmp no longer has an issue with masked arrays using nan fill values. This test has been updated to use the standard means of testing using nccmp. Ticket IMPRO-263 can be closed as the issue no longer exists.
Testing:
=> IMPRO-263 (defunct): nccmp replaces temporary use of cmp for masked arrays with nans

bin/improver-update-grid-metadata, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/utilities/cube_metadata.py
Added argument to set up standard grid metadata attributes automatically if required.
=> Unit test cube setup: add StaGE metadata

lib/improver/tests/utilities/cube_manipulation/test_merge_cubes.py
Fix to a unit test that is broken in the trunk following code changes to the merge_cubes function. This fix required the addition of a new keyword argument and the changing of the numerical values used to identify models.
Testing:
=> Unit test fix for broken merge_cubes test in trunk

bin/improver-extend-radar-mask, lib/improver/nowcasting/utilities.py, lib/improver/tests/nowcasting/utilities/test_ExtendRadarMask.py, tests/improver-extend-radar-mask/00-null.bats, tests/improver-extend-radar-mask/01-help.bats, tests/improver-extend-radar-mask/02-basic.bats, tests/improver-nowcast-optical-flow/08-remasked.bats
Plugin and CLI to update the radar rain rate mask based on a radar coverage composite.  Additional test for the optical-flow CLI with remasked radar data (ie where masks on the three input radar composites are different).
=> Impro1001 radar coverage mask

lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/tests/utilities/test_load.py, lib/improver/tests/utilities/test_rescale.py, lib/improver/tests/utilities/test_temporal.py
Begins to address #742 
Migrated the following test modules (under lib/improver/tests/utilities/) to use the new cube setup utilities, or local utilities in integer seconds:
- test_cube_metadata
- test_load
- test_rescale
- test_temporal
The test_save module should be migrated after https://github.com/metoppv/improver/pull/748 is merged.
=> Migrating unit tests to new cube setup utilities: PR 1

lib/improver/spotdata_new/apply_lapse_rate.py, lib/improver/tests/utilities/cube_manipulation/test_compare_attributes.py, lib/improver/utilities/cube_manipulation.py
- Modified compare_attributes function to look more like it once did, though now with attribute filtering. The use of python 3 dictionary comparison methods failed when the dictionaries contained unhashable values (e.g. arrays, lists) as is the case for source_realizations. As such the code has been reverted to something more robust.
- Added missing kwarg (grid_metadata_identifier) in call to SpotExtraction from within SpotLapseRateAdjust.
Testing:
=> IMPRO-880: Compare attributes and missing kwarg fix

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py
Added ecc bounds for feels like temperature, where these are used for percentile extract in the global processing chain.
Testing:
=> IMPRO-814: ECC bounds for feels like temperature.

bin/improver-spot-extract-new, tests/improver-spot-extract-new/00-null.bats, tests/improver-spot-extract-new/01-help.bats, tests/improver-spot-extract-new/02-nearest-uk.bats, tests/improver-spot-extract-new/03-nearest_uk_min_dz.bats, tests/improver-spot-extract-new/04-lapse_rate_adjusted_uk.bats, tests/improver-spot-extract-new/05-global_site_list_uk_data.bats, tests/improver-spot-extract-new/06-mismatched_metadata.bats, tests/improver-spot-extract-new/07-alternate_metadata.bats, tests/improver-spot-extract-new/08-unavailable_neighbour_method.bats, tests/improver-spot-extract-new/09-unmatched_lapse_rate_height.bats, tests/improver-spot-extract-new/10-missing_lapse_rate_height.bats, tests/improver-spot-extract-new/11-modified_metadata_with_json.bats, tests/improver-spot-extract-new/12-lapse_rate_for_non_temperature_data.bats, tests/improver-spot-extract-new/13-multiple_constraints.bats
This PR adds a CLI for using the new spot-extract and lapse rate adjustment plugins. Additional bats tests are also added.
Testing:
=> IMPRO-881: Spot-extract and lapse rate adjust CLI

lib/improver/tests/utilities/test_save.py, lib/improver/utilities/save.py
Function added to save.py that orders cell methods before saving for instances where there are multiple cell methods applied. In these situations, iris does not consistently order the cell methods on the cube. This leads to CLI test failures as each time a cube is generated the cell method tuple may be differently ordered.
This change is required by #779.
New acceptance test data is needed for cases with multiple cell methods in which they were previously sorted in reverse, e.g. nbhood, recursive filter. In the nbhood/recursive filter cases the cell methods are:
```
mean: time (1 hour)
mean: forecast_period
```
which is reversed by this new function.
This PR relates to IMPRO-1011 in which a test was created that adds two types of cell method to a single cube, e.g.
```
maximum: time (1 …
```
=> Cell Method Sorting: Consistent ordering for multiple cell methods

bin/improver-percentile, bin/improver-percentiles-to-realizations, bin/improver-probabilities-to-realizations, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py, tests/improver-percentiles-to-realizations/00-null.bats, tests/improver-percentiles-to-realizations/01-help.bats, tests/improver-percentiles-to-realizations/05-reordering_wrong_options.bats, tests/improver-percentiles-to-realizations/06-rebading_wrong_option1.bats, tests/improver-percentiles-to-realizations/07-rebading_wrong_option2.bats, tests/improver-percentiles-to-realizations/08-ecc_bounds_warning.bats
Although an ECC bounds exceedance warning option had previously been added for probability data, this had not been implemented for percentile data. 
- Added ECC bounds warning handling to `ensemble-copula-coupling` using a similar method to that used for probabilities. This includes extending the bounds to encompass the exceeded values when the warning option is specified. 
- If the warning option is not specified then an exception will be raised when values exceed ECC bounds.
- Added new unit tests to check that the correct warning is raised and that the new bounds are correctly set.
- Added `--ecc_bounds_warning` option to the `percentiles-to-realizations` CLI. Default option is not to apply the warning functionality.
- Update existing CLI tests to take account …
=> Add ECC bounds exceedance warning option for percentile data

lib/improver/tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/utilities/cube_metadata.py
Description
~~This PR extends the existing functionality for modifying units using the amend_metadata function and, in turn, the standardise CLI. This is done by adding an `update_units` function, primarily to handle instances where the user wants the units to be set directly or where the user wants to convert the units.~~
This PR updates the amend_metadata functionality, so that if a units are specified when a coordinate is being updated then a unit conversion takes place. 
Testing:
=> Update amend_metadata functionality to convert coordinate units

bin/improver-spot-extract, lib/improver/spotdata/spot_extraction.py, tests/improver-spot-extract/01-help.bats
Making clear that the grid_metadata_identifier can be set to None to avoid making any metadata comparisons.
Changes to doc-strings in code and CLI help.
Testing:
=> IMPRO-881: Change to make doc-strings and CLI document additional functionality.

lib/improver/cube_combiner.py, lib/improver/tests/cube_combiner/test_CubeCombiner.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py
Addresses #792 .  In working on #782 , found CubeCombiner cannot generate accurate time points when given int64 seconds.  This PR fixes the underlying bug where datatypes were being escalated in CubeCombiner.expand_bounds, and updates CubeCombiner unit tests to use the centralised cube setup utilities (apart from those served by create_cube_with_threshold() which is dealt with in a separate PR).
=> Update CubeCombiner unit tests to use integer seconds and fix bug

bin/improver-tests
This allows `sphinx-build` to be configured in the site-init, for situations where the normally desired Python deployment doesn't have it.
=> Allow sphinx-build to be supplied via site-init

lib/improver/percentile.py, lib/improver/tests/percentile/test_PercentileConverter.py
Related to #69, #109  
Description
The main aim of this PR is the one line correction in `percentile.py`. I accidentally came across this bug, for the case where you're trying to calculate percentiles over the time coordinate. In the current code, using the `time` coordinate will also result in the `forecast_reference_time` coordinate being matched. This results in `n_collapse_coords` not being able to equal `n_valid_coords`, so I've fixed this. Subsequently, a unit test has been added, that would be previously failed, and other unit tests have been updated to use the `set_up_variable_cube` helper function.
Testing:
=> Allow PercentileConverter plugin to work for time coordinate

bin/improver-threshold, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ensemble_copula_coupling_utilities.py, tests/improver-threshold/01-help.bats, tests/improver-threshold/13-threshold_json.bats
Changed ECC bounds for all temperature diagnostics to be the same (-100C to 60C).  Updated threshold CLI to read a json file with no bounds (so that we don't have to repeat the same list of 50 thresholds in multiple calls).
Testing:
=> Impro1059 ecc thresholds

lib/improver/spotdata/neighbour_finding.py, lib/improver/tests/spotdata/spotdata/test_NeighbourSelection.py, tests/improver-neighbour-finding/15-invalid-global-site.bats, tests/improver-neighbour-finding/16-circular-coord-beyond-bounds.bats
This PR addresses an issue of longitudes defined variously 0 to 360 degrees of -180 to 180 degrees and their interoperability. No longer will sites on a circular longitude coordinate by removed by the bounds checking code because they do no fall into the correct longitudinal bracket, instead they will persist. The spot data code is already able to handle this, it was just the check getting in the way. Domain checking still works for the non-circular latitudinal coordinate.
Testing:
=> IMPRO-1082: Global domain checking to allow circular coordinates

lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py, lib/improver/utilities/time_lagging.py
This changes fixes time lagged ensemble plugin to renumber ensemble members when duplicates are found in the input cube. This is needed for when we time lag Mogrep-G where both cycles have a 0 realization.
Testing:
=> Impro 1036 time lagging fix

.travis.yml
Pylint 2.1.1 doesn't work with astroid 2.2.0, which is now being pulled into our Travis build instead of astroid 2.1.0 - I've hardcoded this to 2.1.0 now.
Astroid version is the only difference between e.g. https://travis-ci.org/metoppv/improver/builds/499210080#L1121 (failing) and https://travis-ci.org/metoppv/improver/builds/498992208#L1120 (succeeding), so I think this should work...
=> Fix pylint Travis failure

bin/improver-wxcode, lib/improver/nowcasting/lightning.py, lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py, lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py, lib/improver/tests/threshold/test_BasicThreshold.py, lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py, lib/improver/threshold.py, lib/improver/wxcode/weather_symbols.py, lib/improver/wxcode/wxcode_decision_tree.py, lib/improver/wxcode/wxcode_decision_tree_global.py, tests/improver-threshold/01-help.bats, tests/improver-wxcode/01-help.bats, tests/improver-wxcode/02-basic.bats, tests/improver-wxcode/03-native_units.bats, tests/improver-wxcode/04-global.bats, tests/improver-wxcode/05-insufficient-files.bats
Rename all IMPROVER cubes that contain probabilities like  `probability_of_rainfall_rate` to follow a specified convention that includes whether the probability is above or below a threshold within the cube name, so that the cube name better describes the contents of the cube. For example:
- `probability_of_rainfall_rate_above_threshold`
- `probability_of_visibility_in_air_below_threshold`
Testing:
This initial PR only includes changes to the following areas:
```
- wxcodes (the greatest number of changes)
- threshold
- set_up_test_cubes
- cube_metadata
- weighted_blend
- nowcast lightning
```
A subsequent PR will be used for changes to the following:
```
- ensemble_calibration
- GenerateProbabilitiesFromPercentiles2D
- probability_of_snow_falling_level (special …
```
=> Impro-1121: Rename probability cubes - 1

.travis.yml
Set numpy to fixed version 1.15.4 until we have a chance to iron out the changes neccessary to use numpy 1.16.2.
Numpy 1.16.2 is causing PRs to fail the pylint test in the travis tests. This seems to be because previous warnings have now been escalated to errors. All of these are of the following types:
```
improver/utilities/solar.py:139:4: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
improver/orographic_enhancement.py:447:51: E1130: bad operand type for unary ~: tuple (invalid-unary-operand-type)
```
Testing:
=> Travis: Fix numpy version to 1.15.4 until we are 1.16.2 ready

bin/improver-threshold, bin/improver-wxcode, lib/improver/nowcasting/lightning.py, lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py, lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py, lib/improver/tests/threshold/test_BasicThreshold.py, lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py, lib/improver/threshold.py, lib/improver/utilities/cube_metadata.py, lib/improver/wxcode/weather_symbols.py, lib/improver/wxcode/wxcode_decision_tree.py, lib/improver/wxcode/wxcode_decision_tree_global.py, tests/improver-threshold/01-help.bats, tests/improver-wxcode/01-help.bats, tests/improver-wxcode/02-basic.bats, tests/improver-wxcode/03-native_units.bats, tests/improver-wxcode/04-global.bats, tests/improver-wxcode/05-insufficient-files.bats
Rename all IMPROVER cubes that contain probabilities like `probability_of_rainfall_rate` to follow a specified convention that includes whether the probability is above or below a threshold within the cube name, so that the cube name better describes the contents of the cube. For example:
-  `probability_of_rainfall_rate_above_threshold`
-  `probability_of_visibility_in_air_below_threshold`
-  `probability_of_lwe_precipitation_rate_in_vicinity_above_threshold`
Testing:
This PR covers an initial set of changes with a final set being made in PR #817 (this PR will be rebased on master once these initial changes have been merged in).
=> Impro 1121 rename probability cubes

lib/improver/nowcasting/lightning.py, lib/improver/tests/lapse_rate/test_LapseRate.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/utilities/test_pad_spatial.py
Partially addresses #742 
Changes made in this PR:
- Updated test_LapseRate.py to use new cube setup utility, and added warnings wrapper where needed.
- Updated test_NowcastLightning.py to use new cube setup utility.  Identified potential bug in code around cube names - left as TODO in tests for reviewers to comment.
- Updated set_up_test_cubes.py to create equal area grids properly (avoiding float precision issues), and fixed minor downstream issues in test_pad_spatial.py
=> Update lapse rate and nowcast lightning tests

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py
Description:
precipitation rate now has name lwe_precipitation_rate to make it CF compliant. 
Testing:
=> Updating ecc to have the right name for precipitation rate

lib/improver/nowcasting/utilities.py, lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py, lib/improver/tests/nowcasting/utilities/test_ApplyOrographicEnhancement.py
Partially addresses #742 
Updated test_OpticalFlow.py and test_ApplyOrographicEnhancement.py to use new cube setup utilities, times in integer seconds and data / coordinates as np.float32.  Some float precision changes to optical flow outputs due to float32 change.
=> Impro983 update nowcasting tests

bin/improver-spot-extract, lib/improver/spotdata/build_spotdata_cube.py, lib/improver/tests/spotdata/spotdata/test_build_spotdata_cube.py, tests/improver-spot-extract/00-null.bats, tests/improver-spot-extract/01-help.bats, tests/improver-spot-extract/14-extract_percentile_thresholded_input.bats, tests/improver-spot-extract/15-extract_percentile_percentile_input.bats, tests/improver-spot-extract/16-extract_percentile_percentile_input_unavailable_percentile.bats, tests/improver-spot-extract/17-extract_percentile_deterministic_input.bats, tests/improver-spot-extract/18-extract_percentile_quiet_warnings.bats, tests/improver-spot-extract/19-extract_multiple_percentiles_thresholded_input.bats, tests/improver-spot-extract/20-extract_multiple_percentiles_percentile_input.bats, tests/improver-spot-extract/21-extract_percentile_realization_input.bats, tests/improver-spot-extract/22-extract_multiple_percentiles_realization_input.bats
This change helps to speed up and simplify the extraction of the 50th percentile for spot purposes, The percentile extraction is moved to occur after the spot extract, thus massively reducing the number of data points that are being processed (in line with Stephen's approach for verification preprocessing). The change also enables us to remove the percentile_extract step from the suite which usually precedes spot_extract. The CLI is written to handle thresholded, percentile, and deterministic input.
Testing:
=> IMPRO-1066: 50th percentile extract in the spot-extract CLI

lib/improver/convection.py, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, lib/improver/nowcasting/lightning.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/utilities/test_cube_checker.py, lib/improver/utilities/cube_checker.py, lib/improver/utilities/cube_manipulation.py, lib/improver/utilities/cube_manipulation_new.py, lib/improver/wxcode/weather_symbols.py
Partially addresses #833 
New function to find threshold coordinate using old form (long_name="threshold") or new form (standard_name=<diagnostic_name>, var_name="threshold").  Replaced use of "threshold" in plugins wherever possible to use this function.  Only exception is use of "threshold" string in `_equalise_cube_coords`, which requires a little more thought and may conflict with work on #835.
**Update:** see PR https://github.com/metoppv/improver/pull/842. I'll address the use of "threshold" in `merge_cubes` / `MergeCubes` in that PR, as I'd expect this one to be merged first.
Testing:
=> Impro1122 find threshold coordinate

lib/improver/tests/uv_index/test_uv_index.py, lib/improver/uv_index.py
Addresses #832 
Description
Correcting the variable name for ultraviolet_index to make sure it the same in the metadata no matter how it is viewed.
Testing:
=> Correcting the variable name for ultraviolet_index

lib/improver/tests/wind_calculations/wind_gust_diagnostic/test_WindGustDiagnostic.py, lib/improver/wind_calculations/wind_gust_diagnostic.py
Remove setting of long name and var name for the wind-gust-diagnostic cube.
Testing:
=> IMPRO-1165: Remove non-standard long name from wind gust diagnostic

doc/source/conf.py, lib/improver/utilities/statistical_operations.py, lib/improver/utilities/temporal_interpolation.py, lib/improver/wind_calculations/wind_downscaling.py, lib/improver/wxcode/wxcode_decision_tree.py
Fixes to all current sphinx compliance warnings. The equations in wind downscaling are improved but still not lovely to behold, so we may wish to consider these further if wind downscaling is remaining.
Testing:
=> Removing sources of sphinx compilation warnings

lib/improver/blending/weighted_blend.py, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, lib/improver/tests/blending/spatial_weights/test_SpatiallyVaryingWeightsFromMask.py, lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py, lib/improver/tests/blending/weights/test_WeightsUtilities.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/helper_functions.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GenerateProbabilitiesFromMeanAndVariance.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py, lib/improver/tests/utilities/cube_manipulation/test__equalise_cube_coords.py, lib/improver/tests/utilities/cube_manipulation/test_merge_cubes.py, lib/improver/tests/utilities/cube_manipulation_new/test__equalise_cube_coords.py, lib/improver/tests/utilities/cube_manipulation_new/test_merge_cubes.py, lib/improver/tests/utilities/test_cube_checker.py, lib/improver/tests/utilities/test_cube_constraints.py, lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/tests/utilities/test_load.py, lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py, lib/improver/utilities/cube_manipulation.py, lib/improver/utilities/cube_manipulation_new.py, lib/improver/utilities/cube_metadata.py, lib/improver/wxcode/weather_symbols.py
Partially addresses #833
Updated unit test setup functions and changed plugins to support new threshold coordinate convention in a backward-compatible way.  Functionality changed:
- Minor implementation changes to ECC, WeatherSymbols and cube manipulation utilities.
- WeightedBlendAcrossWholeDimension now explicitly rejects "threshold" as a coordinate name.  There was an issue with supporting var names in blending, and there is no reason to support this case.  Some unit tests for this case have been removed.
Functionality not yet fixed: some cube metadata utilities (`add_coord` and `update_coord`) don't support the new threshold coordinate metadata (standard and var names).  This and the affected unit tests will be addressed in a separate PR.
Testing:
=> Impro1122 threshold update plugins

.gitignore, doc/source/extended_documentation/ensemble_calibration/ensemble_calibration/create_coefficients_cube.rst, lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
Addresses: Part of #854 
Description
This PR adds the creation of a coefficient cube when estimating the EMOS coefficients. This PR only adds the required method, but does not use this method at present, so as to reduce the size of this PR. A follow-on PR will implement the usage of this coefficients cube.
Testing:
=> Add creation of a coefficient cube for EMOS

lib/improver/spotdata/neighbour_finding.py, lib/improver/tests/spotdata/spotdata/test_NeighbourSelection.py, tests/improver-neighbour-finding/17-wmo-ids-include-some-unset.bats
For sitelists with undefined WMO ids, the spot-data code is using values of None. When neighbour cubes were being created, the wmo_id coordinate could not describe the int values and None values in a consistent format that netcdf could handle; if they were all None, the type was not something netcdf could handle either. This change makes all WMO ids into strings such that the id numbers and Nonetypes can both be described in a single format that can be written to a netcdf file. There are no implications for this elsewhere in IMPROVER at present as the wmo_id is not used; I will need to check with verificaiton to ensure they can handle this change (e.g. add an int() to their use of the IDs).
One unit test was updated, and a new CLI test was added to capture the problem that had previously …
=> Bugfix: WMO ID now stored as a string to allow nonetypes

lib/improver/cli/spot_extract.py, tests/improver-spot-extract/00-null.bats, tests/improver-spot-extract/01-help.bats, tests/improver-spot-extract/04-lapse_rate_adjusted_uk.bats, tests/improver-spot-extract/07-alternate_metadata.bats, tests/improver-spot-extract/09-unmatched_lapse_rate_height.bats, tests/improver-spot-extract/10-missing_lapse_rate_height.bats, tests/improver-spot-extract/12-lapse_rate_for_non_temperature_data.bats, tests/improver-spot-extract/23-invalid_lapse_rate_cube.bats, tests/improver-spot-extract/24-lapse_rate_adjustment_enabled_no_lapse_rate_cube.bats
Moves the lapse-rate filepath argument to be an optional positional argument. This enables the suite to use the taskfilelist file name generator to get the correct lapse rate filename.
The lapse rate adjustment is thus employed if the argument is present, and not used if it is not provided/available.
Testing:
=> IMPRO-1157: spot-extract altered to accept lapse rate from taskfilelist

lib/improver/orographic_enhancement.py, lib/improver/tests/wind_calculations/wind_direction/test_WindDirection.py
There is an issue in pylint in combination with numpy 1.16.2 that raises errors as pylint misidentifies a numpy array as a tuple. The use of a unary operator (~) with a tuple is invalid, so pylint raises an error. This issue has been fixed in later versions of pylint than we are using, but we can remedy the issue by simplifying our code slightly to not use the unary operator in multiple places, rather simply invert the mask in question once.
Whilst making this change in preparation for numpy 1.16.2 I have also removed a warning in the wind direction unit tests where a complex number was being provided when only a float was expected and required.
Testing:
=> IMPRO-1134: Remove numpy 1.16.2+ related errors & a wind warning

lib/improver/utilities/save.py
Addresses #394 - chunk by x-y in generic save wrapper and apply (lossless) compression.
Same code logic as is used for real time demo internally.
CLI tests pass.
Implementation in the suite - no measurable difference in execution on the whole, given the large amount of noise - if anything, faster, although I seriously doubt it! For our UK ensemble, 6x saving in disk space per cycle.
=> Add save compression

lib/improver/tests/ensemble_calibration/ensemble_calibration/helper_functions.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/utilities/cube_metadata.py, lib/improver/wxcode/weather_symbols.py
Addresses #833 
Fixes required for non-standard probability cube names ("in vicinity" and non-standard cloud area fraction) used in weather symbols code.
Testing separately via suite.  However suggest extension to weather symbols unit tests may be worth considering as follow-on, to cover more of these edge-type cases.
Testing:
=> Impro1122 threshold wxsymb fixes

CONTRIBUTING.md, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py
Description
I think the `elif` statement in the unit test is simply always evaluating to true? Couldn't install `improver` locally with `pip` + `venv`. Tried a conda environment but it also failed. Noticed that Travis CI executes individual conda installation commands, but didn't try that.
Hoping it's OK to rely on Travis to run the test against this PR.
Testing:
CLA
=> Fix elif statement

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
Addresses part of #854 
Description
This PRs amends the metadata associated with the EMOS coefficients cube, so that the cube includes scalar x and y coordinates, where the bounds represent the domain that the coefficients are valid for.
There is currently no known good output for this PR. This will be generated after #875 is merged.
Testing:
=> Edits to add domain information to the EMOS coefficients cube

lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py, lib/improver/utilities/time_lagging.py
Fixes problem of not being able to create time-lagged ensembles including the 09Z MOGREPS-UK level 1 file because of the numbering of realizations.
Testing:
=> Fix time lagging of 09Z file

lib/improver/psychrometric_calculations/psychrometric_calculations.py, lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py
Addresses IMPRO-895
Fixes bugs raised where there are two few points to do the horizontal interpolation in the snow falling levels, or the points are not arranged in a triangle.
Testing:
=> Impro 895 snow falling level bug fix

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
Addresses part of #854 
Description
Add a check to ensure that the domain of the forecast cube and the domain of the EMOS coefficients cube match when the EMOS coefficients cube is applied.
Testing:
=> Ensure a matching domain when applying EMOS coefficients

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/helper_functions.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
Addresses part of #854 
Description
Remove specific CRPS assertions, as in these unit tests the CRPS is tested when calculated directly, rather than following minimisation. As the CRPS values in these unit tests are not computed through minimisation, there is no dependence on a tolerance value.
Testing:
=> Remove CRPS specific assertions

lib/improver/cli/wxcode.py, lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py, lib/improver/wxcode/wxcode_decision_tree.py, lib/improver/wxcode/wxcode_decision_tree_global.py, tests/improver-wxcode/01-help.bats, tests/improver-wxcode/02-basic.bats, tests/improver-wxcode/03-native_units.bats, tests/improver-wxcode/04-global.bats, tests/improver-wxcode/05-insufficient-files.bats
We specify that weather symbols (as currently configured) use cloud amount below 1000ft asl, but we actually tend to use low type cloud fraction in the suite, although we rename it to shoehorn it in - this makes it explicit and avoids the tricky renaming within the suite.
Data renamed (cube + filename rename), and I changed an error message to make it clearer when things fail.
=> improver wxcode: use low cloud instead of cloud below 1000ft asl

lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py
Uses built-in Iris time to datetime method rather than converting the points value using the coord units.
Testing:
I couldn't devise a test to trap the intermittent errors caused by using the old method, but this way is more pythonic.
=> Uses built-in Iris time to datetime method.

lib/improver/nowcasting/lightning.py, lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py
Fixes a bug in the nowcast lightning code that triggers when processing a forecast period of exactly 2.5 hours. This was found when testing the code for PS43.
In this case, the rescale function aborts because the min and max to rescale to are identical. Larger lead times were ok as the rescale max became negative (which is allowed).
I have also added a filter to prevent calling the rescale function when the lead time is larger than 2.5 hours as the results will be rejected anyway.
Testing:
=> Fixes a bug in the nowcast lightning code

lib/improver/cli/ensemble_calibration.py, lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/helper_functions.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py, tests/improver-ensemble-calibration/00-null.bats, tests/improver-ensemble-calibration/01-help.bats, tests/improver-ensemble-calibration/02-gaussian.bats, tests/improver-ensemble-calibration/03-trunc_gaussian.bats, tests/improver-ensemble-calibration/04-save_mean_and_var.bats, tests/improver-ensemble-calibration/05-current_forecast_probabilities.bats, tests/improver-ensemble-calibration/06-current_forecast_probabilities_error.bats, tests/improver-ensemble-calibration/07-current_forecast_percentiles.bats, tests/improver-ensemble-calibration/08-current_forecast_percentiles_error.bats, tests/improver-ensemble-calibration/09-current_forecast_rebadged_percentiles.bats, tests/improver-ensemble-calibration/10-predictor_of_mean.bats
Addresses IMPRO-1206
Removed an unused option for ensemble calibration.
=> Removing calibration method as an option for ensemble calibration.

tests/bin/bats
Add an export OMP_NUM_THREADS=1 statement into tests/bin/bats to force the testing of data using this number of threads. This speeds up CLI tests by more than a factor of 2 and also removes irregularities between testing on spice and local machines for those few tests that are somehow sensitive to the threading.
This PR requires the replacement of two KGO with new versions that exhibit precision level differences.
Testing:
=> IMPRO-1283: Fix OMP_NUM_THREADS for bats tests

lib/improver/cube_combiner.py, lib/improver/tests/cube_combiner/test_CubeCombiner.py, lib/improver/tests/utilities/cube_manipulation/test_expand_bounds.py, lib/improver/utilities/cube_manipulation.py, lib/improver/utilities/cube_units.py, lib/improver/wind_calculations/wind_gust_diagnostic.py
Factored out expand_bounds into cube_manipulation utilities. Rewrote CubeCombiner unit tests to match current standards (having checked the originals passed after the refactoring first).
This change allows me to use the expand bounds component of CubeCombiner in isolation without needing the plugin itself. I have also slightly rejigged the implementation such that expand_bounds can handle the modification of multiple coordinates, whereas previously this was achieved using a loop external to the function (in CubeCombiner.process).
Testing:
=> IMPRO-898: CubeCombiner changes

lib/improver/nowcasting/optical_flow.py, lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py
Addresses a problem in which a constant which should only be used with quantities in mm/hr was being used with other units. This is achieved by enforcing mm/hr as the working units of optical flow precip rates.
Additionally this PR also changes the treatment of masked points by setting their values to zero. This avoids the spreading of fill values across the domain which was causing the optical flow code to perform poorly when calculating velocities; it was returning only nans when working in mm/hr as the 1E36 fill values were increased by the unit conversion to a value beyond the float32 limit.
Among the new unit tests added is one that involves masked data which is included to capture the behaviour described.
Testing:
=> IMPRO-1295: Optical flow bug fixes

lib/improver/blending/calculate_weights_and_blend.py, lib/improver/blending/weights.py, lib/improver/tests/blending/calculate_weights_and_blend/test_WeightAndBlend.py, lib/improver/tests/blending/weights/test_ChooseDefaultWeightsLinear.py, lib/improver/tests/blending/weights/test_ChooseDefaultWeightsNonLinear.py, tests/improver-weighted-blending/02-basic_nonlin.bats, tests/improver-weighted-blending/03-basic_lin.bats, tests/improver-weighted-blending/12-realization_collapse.bats, tests/improver-weighted-blending/15-accum_cycle_blend.bats
Removed defaults from both `ChooseDefaultWeights` plugins.  Added re-ordering option to non-linear weights plugin (not required for linear as user has all the options!).  Updated CLI tests for weighted blending so that they work.  A later PR will change the CLI tests to do something sensible, and remove any tests that are no longer required.
Description
Testing:
=> IMPRO-1003 sort out default weights plugins & blending CLI options

doc/source/conf.py, lib/improver/blending/weights.py, lib/improver/utilities/spatial.py, lib/improver/utilities/temporal.py, lib/improver/uv_index.py
Description
Add intersphinx mappings, so that links will be created between our documentation on readthedocs and the underlying modules. I've also made a few minor docstring edits, as part of testing the intersphinx mappings and when looking at how the docstrings are displayed on readthedocs.
Note that it seems like `numpy` should be used in the docstrings, rather than `np`, so that the mapping works as intended.
Testing:
=> Add intersphinx mapping to improve readthedocs

lib/improver/psychrometric_calculations/psychrometric_calculations.py, lib/improver/psychrometric_calculations/svp_table.py, lib/improver/tests/utilities/ancillary_creation/test_SaturatedVapourPressureTable.py, lib/improver/utilities/ancillary_creation.py
The more exact answer provided to a simple calculation when using float32 means that we need an additional, but unused table entry to enable interpolation when temperatures are at the maximum temperature for which we want to use the table.
```
float64 --> 1549.9999999999995
float32 --> 1550.0
```
The calculation in float64 gave a rounded down index of 1549, and an interpolant of 1, meaning the value for the saturated vapour pressure would be equal to the value at index 1550. In float32 the index returned is 1550, and the interpolant is 0. However we still need the index+1 table position to keep our calculation general (rather than making a special case for this highest value). That is the purpose of this change.
See ticket and linked notebook for more discussion of the issue.
Testing:
=> IMPRO-1312: Ensure SVP table useable with float32 temperature above max temperature

lib/improver/cli/nowcast_extrapolate.py, lib/improver/nowcasting/accumulation.py, lib/improver/tests/nowcasting/accumulation/test_Accumulation.py, tests/improver-nowcast-extrapolate/01-help.bats, tests/improver-nowcast-extrapolate/13-accumulation_period.bats
Description
This PR is aimed at modifying the accumulation plugin to support overlapping periods. The changes are:
- nowcast_extrapolate.py - Add an `accumulation_period` CLI argument and pass this through to the accumulation period. 
- accumulation.py - Although there looks like a lot of changes, there is only a small amount of new code. The new code is predominately in _get_cube_subsets. Another change is to allow the specification of the `forecast_periods` required within the `__init__`. This allows a check for whether an accumulation period that ends at the specified forecast_period requires calculation. The rest of the changes mainly relate to putting things from `process` into methods, so that I could test the different sections more directly.
- test_accumulation.py - This has been …
=> Update precipitation accumulation plugin to support overlapping periods

lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py, lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_Utilities.py, lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperature.py, lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperatureIntegral.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/test_set_up_test_cubes.py
This PR updates the psychrometric units tests to use the centralised utility for setting up cubes. It might be good to add/modify the create cube with height levels functionality, but for now I have removed the use of this (let's discuss).
The use of float32 data in the tests led to the recently merged modifications to the SVP table, and also results in small changes to many of the tests results.
Testing:
=> IMPRO-983: Psychrometric unit tests

lib/improver/cli/weighted_blending.py, tests/improver-weighted-blending/01-help.bats, tests/improver-weighted-blending/09-model_blending.bats, tests/improver-weighted-blending/11-weights_from_dict.bats, tests/improver-weighted-blending/12-percentile_weights_from_dict.bats, tests/improver-weighted-blending/16-spatial_model_blending.bats, tests/improver-weighted-blending/18-spatial_model_blending_no_fuzzy.bats, tests/improver-weighted-blending/19-three_model_blending.bats
Description
Alter the model_id_attr argument to have None as a default and update the relevant CLI tests accordingly.
Testing:
=> Alter default model_id_attr argument for weighted blending

lib/improver/cli/spot_extract.py, tests/improver-spot-extract/17-extract_percentile_deterministic_input.bats
The spot-extract CLI has to date required that the requested percentiles for extraction be integers. This may not always be desirable and changing the option to float is straightforward.
Testing:
=> Spot-extract altered to accept percentiles as floats

lib/improver/cli/apply_emos_coefficients.py, tests/improver-apply-emos-coefficients/00-null.bats, tests/improver-apply-emos-coefficients/01-help.bats, tests/improver-apply-emos-coefficients/10-no_coefficients.bats, tests/improver-apply-emos-coefficients/11-wrong_coefficients.bats, tests/improver-apply-emos-coefficients/12-wrong_forecast_input.bats
Description
Amendment to the apply-emos-coefficients CLI, so that the coefficients filepath is an optional positional argument, so that if this filepath is not supplied then the uncalibrated forecast is returned.
Testing:
=> Return uncalibrated forecast if no EMOS coefficients are provided

CONTRIBUTING.md, lib/improver/nbhood/circular_kernel.py
Python strings should be compared using `==` to check string equality, rather than `is` which checks object identity. Fix an instance of this problem in the neighbourhood circular kernel code.
Also re-structured the if-elif to avoid `total_area` may not be defined before use later in the function.
Testing:
CLA
=> Fix use of 'is' for comparison of strings

lib/improver/nowcasting/accumulation.py, lib/improver/tests/utilities/test_cube_units.py, lib/improver/units.py, lib/improver/utilities/cube_units.py
Adds functionality to the `cube_units` module to fail if cube data or coordinates do not conform to the expected units or types (new function).  Also:
- Added substring parsing for dataset and coordinate names
- Added some more entries to the `improver.units` module
Testing:
=> Impro1286 check and fail

lib/improver/cli/apply_emos_coefficients.py, lib/improver/cli/nbhood.py, lib/improver/cli/nowcast_extrapolate.py, lib/improver/cli/nowcast_optical_flow.py, lib/improver/cli/percentiles_to_realizations.py, lib/improver/cli/probabilities_to_realizations.py, lib/improver/cli/recursive_filter.py, lib/improver/cli/spot_extract.py, lib/improver/cli/wind_downscaling.py, lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/tests/utilities/test_load.py, lib/improver/utilities/cli_utilities.py, lib/improver/utilities/load.py
The CLI's often need to optionally load cubes. This means that the cubes can be either Nonetype or a Cube. 
This move the responsibility of that to a bool kwarg rather than extra if statements throughout the CLI's.
This has taken a single check at the start of the load function and a refactor across 10 CLI's.
Testing:
=> Change load_cube to allowed None to be returned if no filepath.

lib/improver/tests/wind_calculations/wind_components/test_ResolveWindComponents.py, lib/improver/wind_calculations/wind_components.py
The for loop near the end of `ResolveWindComponents` `calc_true_north_offset` method currently carries out regridding, but then throws away the regridded cube rather than assigning back to the `ucube` and `vcube` variables. This behaviour looks like it is not how the code is intended to work and is very likely to be a bug.
Testing:
Expected outputs in unit tests have been updated.
This change affects the KGO output files, and those will need to be updated separately outside this pull request.
=> Fix ResolveWindComponents calc_true_north_offset throwing away regridding result

lib/improver/tests/utilities/test_TemporalInterpolation.py
The unit-tests in tests/utilities/test_TemporalInterpolation.py made use of the datetime.timestamp method without specifying a time-zone. This meant that the expected values defined in the unit-tests varied according to the locale of the machine running the tests.
After experimenting with setting time-zone information, I have replaced all these calls with hard-coded numbers, as used elsewhere in the IMPROVER unit-tests.
Testing:
=> IMPRO1361 timezone bugs

lib/improver/between_thresholds.py, lib/improver/tests/between_thresholds/test_between_thresholds.py
Plugin to calculate a "between_thresholds" cube from above or below thresholded probabilities.
The question of whether threshold points should be at the top, bottom or midrange of the bounds has been asked but not answered yet.  In the meantime I've written the plugin to have the upper threshold point and bounds spanning the range between which probabilities are specified.
Testing:
=> Between thresholds plugin

lib/improver/blending/weighted_blend.py
Turned two methods into static methods.
used with the `@staticmethod` decorator. 
The static method is good where you have a method that is needed by the class but isn't making use of `self.`.
Testing:
=> Making static methods

lib/improver/blending/weighted_blend.py, lib/improver/cli/nowcast_extrapolate.py, lib/improver/cli/nowcast_optical_flow.py, lib/improver/feels_like_temperature.py, lib/improver/nowcasting/lightning.py, lib/improver/spotdata/neighbour_finding.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py, lib/improver/utilities/save.py
Here are a selection of unsed variables
- blending/weighted_blend
- Unused asignment on mutable cubelist
- cli/nowcast_extrapolate
- unused index with an enumerate()
- cli/nowcast_optical_flow
- unused index with an enumerate()
- feels_like_temperature
- alpha is assigned to later without use
- nowcasting/lighting
- entire line does nothing
- spotdata/neighbour_finding
- distance is never used
- `index_nodes = []` is assigned to later before being used.
//TODO
- tests/ensemble_coupla_coupling/ensemble_coupla_coupling/test_EnsembleReordering
- declares data then declares it again
- tests/set_up_test_cubes
- time_bounds is never used.
- utilities/save
- chunksize and xy_chunksize are assigned again before use.
Testing:
=> Unused vars

lib/improver/tests/utilities/cube_manipulation/test_build_coordinate.py, lib/improver/tests/utilities/cube_manipulation/test_clip_cube_data.py, lib/improver/tests/utilities/cube_manipulation/test_compare_attributes.py, lib/improver/tests/utilities/cube_manipulation/test_compare_coords.py, lib/improver/tests/utilities/cube_manipulation/test_concatenate_cubes.py, lib/improver/tests/utilities/cube_manipulation/test_enforce_coordinate_ordering.py, lib/improver/tests/utilities/cube_manipulation/test_equalise_cube_attributes.py, lib/improver/tests/utilities/cube_manipulation/test_merge_cubes.py, lib/improver/tests/utilities/cube_manipulation/test_sort_coord_in_cube.py, lib/improver/tests/utilities/cube_manipulation/test_strip_var_names.py
Partially addresses #742 
Migrated remaining cube manipulation utility unit tests to use the new cube setup functions.  Tidied up and reduced duplication.
Testing:
=> Impro 983 cube manipulation

lib/improver/tests/utilities/test_cube_constraints.py, lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/utilities/cube_constraints.py, lib/improver/utilities/cube_extraction.py
The extract_subcube code was written when we were still using float64 values. The precision of these values made float equivalence work in most instances. Now that we are using float32 coordinate and data values, float equivalence tends to fail and requires a small tolerance to be added.
The changes in this PR introduce a small amount of tolerance (relative to the value being compared) that lead float equivalence to work. This is achieved using numpy.close for single value matching, and by slightly expanding the range when using range matching.
Existing units tests were modified to use a cube with float32 data and coordinates. This required introducing some tolerance where the constraint was not created by the new function.
Note that the test_cube_extraction.py: Test_extract_subcube tests …
=> IMPRO-1397: Extract subcube made to work with float32 values

.travis.yml
See the links under 'Linux installers' here:
https://docs.conda.io/en/latest/miniconda.html
=> Update miniconda version from Python 2 to 3

lib/improver/blending/calculate_weights_and_blend.py, lib/improver/nbhood/circular_kernel.py, lib/improver/nbhood/square_kernel.py, lib/improver/tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py, lib/improver/tests/utilities/test_spatial.py, lib/improver/utilities/pad_spatial.py, lib/improver/utilities/spatial.py
Added function to calculate grid length from equally-spaced spatial coordinates tidied up some mess in spatial functions, largely around `convert_distance_to_grid_cells`.  Further refactoring work is required in neighbourhood processing applications.
Testing:
=> Calculate grid length

lib/improver/cli/standardise.py, lib/improver/metadata/attributes.py, lib/improver/metadata/constants/attributes.py, lib/improver/metadata/set_attributes.py, lib/improver/tests/metadata/test_attributes.py, lib/improver/tests/metadata/test_set_attributes.py, lib/improver/tests/utilities/test_cube_metadata.py, lib/improver/units.py, lib/improver/utilities/cube_metadata.py
Changes:
- Added `improver.metadata` directory including `improver.metadata.attributes` with functions to update the level 1 nowcast, level 3 blended and any-level spot data attributes
- Fixed functions in `improver.utilities.cube_metadata` to return a cube without modifying the input cube
- Made appropriate functions in `improver.utilities.cube_metadata` private to that module, anticipating further rearrangement of the metadata modules in the next PR
Testing:
=> Impro 1347 global attributes: PR 1 of 3

lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py, lib/improver/utilities/time_lagging.py, tests/improver-time-lagged-ensembles/05-renumbered_realizations.bats
The time lagging functionality within IMPROVER renumbers ensemble members when creating a time lag if there is not an existing unique number for each ensemble member. For example, lagging two MOGREPS-G cycles will result in this renumbering as both cycles include member 0.
This PR ensures that the newly created realization coordinate is of type int32, ensuring compliance with metadata, which is enforced by the save wrapper. A new test is added that would have captured this issue and ensures it is covered in case of future changes.
Testing:
=> IMPRO-1381: Ensure recreated ensemble numbers are of type int32

lib/improver/cli/apply_emos_coefficients.py, lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/ensemble_calibration/ensemble_calibration_utilities.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration_utilities/test_ensemble_calibration_utilities.py, lib/improver/tests/utilities/test_cube_checker.py, lib/improver/utilities/cube_checker.py
Refactoring of the apply ensemble calibration plugin to make it adhere to our more typical style. This shrinks the init, passes cubes to the process method (rather than the init), and splits the processing into smaller functions.
The unit tests have necessarily been changed quite substantially, but the results data are all unchanged. The CLI tests pass as before.
Testing:
=> IMPRO-1323: ApplyCoefficientsFromEnsembleCalibration refactor

lib/improver/tests/orographic_enhancement/test_OrographicEnhancement.py, lib/improver/tests/spotdata/spotdata/test_build_spotdata_cube.py, lib/improver/tests/threshold/test_BasicThreshold.py
Partly addresses #742 
Minor changes to orographic enhancement, spotdata and threshold unit tests.
Testing:
=> Update misc unit tests to use integer time in seconds

lib/improver/ensemble_calibration/ensemble_calibration_utilities.py, lib/improver/tests/ensemble_calibration/ensemble_calibration_utilities/test_SplitHistoricForecastAndTruth.py
Description
The SplitHistoricForecastsAndTruth plugin currently uses the Iris cube.merge_cube functionality. This has been switched for the IMPROVER merge_cubes functionality functionality, so that files with mismatching history attributes are handled correctly.
Testing:
=> Update merging of historic forecasts and truth for EMOS

lib/improver/utilities/cube_manipulation.py
Made this change a long time ago - from memory this shaves a small (but non-trivial) amount of time from all improver calls.
Testing:
=> Remove unconditional cube transpose - only do so if dims change order

lib/improver/tests/utilities/test_cube_extraction.py, lib/improver/utilities/cube_extraction.py
Description
Add option to support not reconverting the units of the coordinates of the cube back into the original units.
This PR aims to:
- Add an option to the `apply_extraction` function, so that the coordinates within the cube to not have to be re-converted into the original coordinate units. This allows the extracted cube to be returned with its units converted.
Testing:
=> Support cube extraction without reconverting units

lib/improver/metadata/check_datatypes.py, lib/improver/tests/metadata/test_check_datatypes.py
Follow-up from #978 
Added bounds checking to `check_datatypes` and made functional unit tests for `check_cube_not_float64`.  Last commit is code rearrangements with no functional changes - suggest reviewers look at all but the last commit for a clear picture of what has changed.
Testing:
=> Tidy-up of datatypes checking

lib/improver/tests/utilities/test_spatial.py, lib/improver/utilities/spatial.py
Removing unused functions and their tests.
- lat_lon_transform
- get_nearest_coords
Testing:
=> IMPRO-1456: Remove unused code in spatial/utilities

lib/improver/cli/nowcast_extrapolate.py, lib/improver/cli/nowcast_optical_flow.py, lib/improver/nowcasting/forecasting.py, lib/improver/nowcasting/optical_flow.py, lib/improver/tests/nowcasting/forecasting/test_CreateExtrapolationForecast.py, lib/improver/tests/nowcasting/optical_flow/test_generate_optical_flow_components.py
Stripped a ton of processing that shouldn't have been there out of the nowcasting CLIs and into plugins / utilities.  Cut-n-paste programming.  Added some basic unit tests, but coverage is already provided by CLI tests - there are no new features here.
Testing:
=> Strip verbosity out of nowcasting CLIs

lib/improver/cli/nbhood.py, lib/improver/cli/recursive_filter.py, lib/improver/nbhood/recursive_filter.py, lib/improver/tests/nbhood/recursive_filter/test_RecursiveFilter.py, tests/improver-nbhood/09-recursive-filter-alpha-basic-square.bats, tests/improver-nbhood/10-recursive-filter-alphas-basic-square.bats, tests/improver-nbhood/11-recursive-filter-alpha-internal-mask-with-re-mask.bats, tests/improver-nbhood/12-recursive-filter-alpha-internal-mask-no-re-mask.bats, tests/improver-nbhood/13-recursive-filter-alpha-external-mask-with-re-mask.bats, tests/improver-nbhood/14-recursive-filter-alpha-external-mask-no-re-mask.bats, tests/improver-recursive-filter/02-basic_alpha.bats, tests/improver-recursive-filter/04-external_mask_with_re_mask.bats, tests/improver-recursive-filter/05-external_mask_no_re_mask.bats, tests/improver-recursive-filter/06-internal_mask_with_re_mask.bats, tests/improver-recursive-filter/07-internal_mask_no_re_mask.bats
Capped the alphas values at 0.5.
given warnings at any more iterations than 2.
changed the cubes and bats to be acceptable and therefore changed the KGO to allow for this.
Tested for the errors and warning.
Testing:
=> IMPRO-1330: Cap alpha values

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py, lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py
Description
Add support to filtering within ensemble calibration for diagnostics that have bounds e.g. 1 hour max temperature.
This PR adds:
- Updates to the _filter_non_matching_cubes method within the EstimateCoefficientsForEnsembleCalibration class. This method ensures that the historic forecasts and truth dataset match in terms of validity time with this functionality being extended to support matching for diagnostics that have bounds e.g. 1 hour max temperature.
- Update the iris_time_to_datetime function to support the desire to process the bounds information.
- Add unit tests.
Testing:
=> Support filtering for EMOS for bounded variables

lib/improver/cli/orographic_enhancement.py, lib/improver/orographic_enhancement.py, lib/improver/tests/orographic_enhancement/test_OrographicEnhancement.py, tests/improver-orographic-enhancement/01-help.bats, tests/improver-orographic-enhancement/02-basic.bats, tests/improver-orographic-enhancement/03-boundary_height.bats, tests/improver-orographic-enhancement/04-unit_convert_boundary_height.bats
To conform to the "one output object per CLI" rule, the oropgraphic enhacement cli and plug in now only returns one cube.
Are any other changes required in the cli?
- orographic_enhancement
- _create_output_cube
- process
- cli/orographic_enhancement
- main
- process
- removing standard from bats
- 02-basic
- 03-boundary_height
- 04-unit_convert_boundary_height
- unit tests
- Test__create_output_cubes
- Test_process
Testing:
- [N/A] Added new tests for the new feature(s)
=> Impro 1445: Remove standard output from orographic enhancement

lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
Description
Edits to ensure that the mean CRPS is calculated, rather than the CRPS sum
This PR:
- Ensures that the mean of the CRPS values is computed, rather than the sum. This is more correct and allows for easier interpretability of the CRPS values being computed. None of the values for the coefficients computed have changed for either the unit tests or the CLI tests.
- calculate_normal_crps and calculate_truncated_normal_crps have been updated to calculate the mean.
- Update value of CRPS computed in the unit tests.
The equations updated in this PR follow equations 5 and 6 from [Gneiting et al., 2005](https://journals.ametsoc.org/doi/full/10.1175/MWR2904.1) for the Gaussian distribution and the equations from section 2.3 of [Thorarinsdottir & Gneiting, …
=> Update EMOS to calculate CRPS mean

lib/improver/spotdata/neighbour_finding.py, lib/improver/tests/spotdata/spotdata/test_NeighbourSelection.py, tests/improver-neighbour-finding/12-alternative-site-coordinate-system.bats
The motivation for this change was a CLI test that was not actually checking the result. The fix to this was simply to update the sitelist being used, which should match the global test site list input but using a Lambert Azimuthal Equal Areas coordinate system. Unfortunately the global list was changed without updating the LAEA site list.
Updating this list made the neighbour data match, in that the grid point neighbours identified by both lists were the same; CLI tests 7 and 12 share the same KGO, which has not been changed.
The output data do not share the same coordinates, because there has been a long standing unaddressed issue of non-lat/lon input sitelists (which we don't use) returning non-lat/lon site coordinates that are labelled as latitude and longitude in the neighbour cubes. …
=> Bug: Spot site lat/lons as lat/lons regardless of input coordinate system

doc/source/conf.py, lib/improver/ensemble_calibration/ensemble_calibration.py, lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_FromMeanAndVariance.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromMeanAndVariance.py, lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GenerateProbabilitiesFromMeanAndVariance.py
Description
Edits to be able to specify the distribution used when creating either percentiles or probabilities from the mean and variance. This is primarily for the purposes of converting from mean and variance for EMOS where currently either a normal or truncated normal distribution are support when minimising the CRPS.
The contents of this PR is:
- Minor docstring amendment to ensemble_calibration.py
- Modification to the `GeneratePercentilesFromMeanAndVariance` and `GenerateProbabilitiesFromMeanAndVariance` to accept the specification of a distribution when computing percentiles or probabilities from the mean and variance.
The details are:
- Addition of a `FromMeanAndVariance` class, so that the `GeneratePercentilesFromMeanAndVariance` and `GenerateProbabilitiesFromMeanAndVariance` …
=> Specify the distribution when creating percentiles/probabilities from the mean and variance

lib/improver/blending/weighted_blend.py, lib/improver/metadata/forecast_times.py, lib/improver/nbhood/nbhood.py, lib/improver/tests/blending/weights/test_ChooseWeightsLinear.py, lib/improver/tests/metadata/test_forecast_times.py, lib/improver/tests/set_up_test_cubes.py, lib/improver/tests/utilities/test_temporal.py, lib/improver/utilities/temporal.py, lib/improver/utilities/time_lagging.py
- Moved temporal utilities which assume a specific cube structure (forecast period and cycletime coordinates) into a separate metadata module, away from the more general time parsing utilities.
- Renamed a function so that "cycletime" is used consistently within both modules
- Removed unused `set_utc_offset` function
Testing:
=> Temporal utilities

tests/improver-nowcast-extrapolate/02-basic.bats, tests/improver-nowcast-extrapolate/03-metadata.bats, tests/improver-nowcast-extrapolate/05-model_winds.bats, tests/improver-nowcast-extrapolate/07-unavailable_pressure_level.bats, tests/improver-nowcast-optical-flow/02-basic.bats, tests/improver-nowcast-optical-flow/03-metadata.bats
Replaces the orographic-enhancement data that are input to the nowcast-optical-flow and nowcast-extrapolate CLI tests as the generating code behaviour changed in #943. 
Extends the nowcast-extrapolate 02-basic test from a 30-minute forecast to a 90-minute forecast to ensure that multiple orographic-enhancement fields are being used and to be more in line with how the code is used.
Testing:
=> IMPRO-1495 test 90 minute extrapolation

.readthedocs.yml, doc/rtd_environment.yml, environment.yml
Description
Minor edits to reduce Read the Docs memory consumption.
This PR contains:
* An update to `.readthedocs.yml` that:
1. Only builds the documentation in the htmlzip format, as used on the webpages.
2. Set `system_packages: true`, so that common packages e.g. numpy and sphinx from the Read the Docs environment are used, rather than re-downscaling them within the conda environment.
* Remove `numpy` and `sphinx` from `environment.yml`, as these packages are available within the default Read the Docs environment.
These updates follow the recommendations in  https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html. 
Failing Read the Docs build using master: https://readthedocs.org/projects/improver-gavinevans/builds/10057853/
Successful Read the Docs build: …
=> Minor edits to reduce Read the Docs memory consumption

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
Problem with improver-percentile outputting messy percentile values of the form:
```
>> print(cube.coord('percentile'))
DimCoord(array([  0.      ,   5.      ,  10.      ,  15.000001,  20.      ,
30.000002,  40.      ,  50.      ,  60.000004,  70.      ,
80.      ,  85.      ,  90.      ,  95.      , 100.      ],
dtype=float32), standard_name=None, units=Unit('%'), long_name='percentile', var_name='percentile')
```
when given a list of int / float inputs.  This was traced to unnecessary processing of the input percentile values, which has been fixed in this PR.
Testing:
=> Fixed bug caused by unnecessary processing of percentile values

.travis.yml, bin/improver-tests
The coverage reporting path for `pytest-cov` was previously set incorrectly, causing no coverage data file to be created.
This PR also applies coverage testing to the acceptance tests, so acceptance test coverage is appended to the unit test coverage and the combined coverage result gets reported to codacy and codecov. This will currently have no effect, as all the acceptance tests are skipped on Travis CI.
=> Fix codacy coverage and report combined unit/acceptance coverage

lib/improver/cli/__init__.py
Fixes two bugs with Clize CLIs:
- `(ERROR/3) Unknown interpreted text role "exc".` - Fixed by adding a filter to cli.__init__.docutilitze.
- Error messages printed twice. - Fixed by removing a print statement (and surrounding try block)
You can reproduce these things on `master` with the command `bin/improver apply_lapse_rate` which returns:
```
process:33: (ERROR/3) Unknown interpreted text role "exc".
process:40: (ERROR/3) Unknown interpreted text role "exc".
process:44: (ERROR/3) Unknown interpreted text role "exc".
process:45: (ERROR/3) Unknown interpreted text role "exc".
process:46: (ERROR/3) Unknown interpreted text role "exc".
process:33: (ERROR/3) Unknown interpreted text role "exc".
process:40: (ERROR/3) Unknown interpreted text role "exc".
process:44: (ERROR/3) Unknown …
```
=> Fix duplicate clize output and errors

lib/improver/metadata/forecast_times.py, lib/improver/tests/metadata/test_forecast_times.py, lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py
Following from #1019 , this PR tidies up the unit tests for `improver.metadata.forecast_times.forecast_period_coord` and restricts this function to generate a coordinate with the IMPROVER-expected units and datatype.  Some tidy-up of existing unit tests was required.
Testing:
=> Improve forecast times

lib/improver/cli/wind_gust_diagnostic.py, lib/improver/tests/acceptance/test_wind_gust_diagnostic.py
Description
This PR converts the `wind_gust_diagnostic` CLI to use Clize.
Testing:
=> Convert wind-gust-diagnostic CLI to use Clize

lib/improver/cli/threshold.py, lib/improver/tests/acceptance/test_threshold.py, lib/improver/threshold.py
I have changed the interface a bit: where `threshold_values` used to be a list of space-separated values, now it is comma-separated values in line with the clize options.
Testing:
=> Clize threshold

.github/workflows/tests.yml, environment.yml
Adds `pylint -E` to the actions tests.
It is faster in parallel (GH action runners have 2cores available), but making it a separate job (to run in parallel with the other steps) would mean duplicating the install step as they run on different VMs. 
Caching dependencies is possible, but not straightforward if you are using the the Conda base environment. Activating named environments currently doesn't work with actions.
=> Pylint with Github Actions 

lib/improver/cli/__init__.py
Updated the help string supplied with `--output` to describe the expected behaviour when no output is supplied.
=> Describes behaviour if optional output file is not supplied.

lib/improver/tests/acceptance/test_neighbour_finding.py
Enables a neighbour-finding CLI test that is no longer expected to fail by removing the xfail decorator and simplifying the KGO compare method.
Testing:
=> Enable neighbour-finding CLI test that was marked as failing

lib/improver/utilities/save.py
This allows to poll for netcdf files directly without need for `.done` files.
=> save atomically by writing to a temporary file and then renaming

lib/improver/cli/wind_downscaling.py, lib/improver/tests/acceptance/test_wind_downscaling.py
(Height levels cube input is left as a kwarg, given that it is not used in the typical use case)
(cc @TomekTrzeciak)
Testing:
=> wind-downscaling CLI to clize

lib/improver/cli/orographic_enhancement.py, lib/improver/tests/acceptance/test_orographic_enhancement.py
As this is part of nowcasting, it is a PR to master and not the clize feature branch.
The output directory has ben removed as a normal --output will do here.
The load_and_extract has been changed into extract_and_check.
This is because each cube is loaded via clize, but they still need extracting and then checking.
Testing:
=> IMPRO-1517: Update Orographic enhancement to use clize.

lib/improver/cli/nowcast_optical_flow.py, lib/improver/tests/acceptance/test_nowcast_optical_flow.py
As this is part of nowcasting it will not be going into the clize feature branch.
- the three radar files now get input as separate cubes and merged into a cubelist.
This is becase clize saw them as variable length and it clased with the orographic enhancement cube which could be `None`.
Testing:
=> IMPRO-1523: Convert optical flow to clize

lib/improver/lapse_rate.py, lib/improver/nbhood/circular_kernel.py, lib/improver/nbhood/square_kernel.py, lib/improver/tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py, lib/improver/utilities/warnings_handler.py, lib/improver/wind_calculations/wind_downscaling.py
Removed the surviving classes which inherit from object.
So
```python
class My_Class(object):
```
becomes
```python
class My_Class:
```
Testing:
=> IMPRO-1554: Removing useless-object-inheritance

lib/improver/cli/generate_orographic_alphas.py, lib/improver/tests/acceptance/test_generate_orographic_alphas.py, lib/improver/tests/utilities/test_OrographicAlphas.py, lib/improver/utilities/ancillary_creation.py
We already had the code for this, but no corresponding CLI.
I created this because:
* There is a desire to put both "alphas" cubes into a single file to simplify the clize version of the recursive-filter CLI
* The "alphas" files might want to be generated alongside the other ancillaries (e.g: at startup in the suite).
TO-DO (later work):
* The docstring was copied from the underlying plugin (and adapted slightly), it could do with being improved but I don't have the background knowledge of the underlying processing, so would need to consult with someone with some expertise on this.
* On a related note: "alpha" or "alphas" is a fairly terrible name and presumably relates to a constant in an equation - can we come up with name that's more descriptive?
* The `invert_alphas` option seems kind …
=> generate-orographic-alphas CLI

lib/improver/tests/metadata/test_amend.py
fixed assignment-from-none error in a test due to a change of it returning None rather than a bool.
Testing:
=> IMPRO-1560: fix assigntment-from-none pylint error

lib/improver/standardise.py, lib/improver/tests/standardise/test_StandardiseGridAndMetadata.py
Met Office specific grid attributes should be inherited from the target grid after regridding.  If not present on the target grid, these attributes should be removed as they are no longer correct.  This PR removes incorrect grid attributes as part of the regridding algorithm.
Testing:
=> Remove incorrect grid attributes

lib/improver/cli/convert_to_realizations.py, lib/improver/tests/acceptance/test_convert_to_realizations.py
This fixes a small bug in the convert-to-realizations CLI and adds some tests.
Previously, when a realization-coordinate cube was passed in (without a threshold or percentile coordinate), an error would occur:
```python
File "/opt/improver/lib/improver/cli/convert_to_realizations.py", line 64, in process
elif cube.coord(var_name='threshold'):
File "/opt/iris/cube.py", line 1463, in coord
raise iris.exceptions.CoordinateNotFoundError(msg)
iris.exceptions.CoordinateNotFoundError: 'Expected to find exactly 1  coordinate, but found none.'
```
Now fixed by using `coords(...)`.
Testing:
I added a new invalid input file to my version of improver_tests, which is a symlink to a no-realization/no-threshold/no-percentile NetCDF file.
=> Fix convert to realizations for realizations

lib/improver/cli/__init__.py
If you run the command `bin/improver apply-emos-coefficients --help`, you see an unhelpful extra message before the Usage is printed:
`process:23: (ERROR/3) Unknown interpreted text role "data".`
This PR silences this message.
Testing:
=> Silences "interpreted-text" warning when parsing apply-emos-coefficients CLI.

improver_tests/acceptance/test_estimate_emos_coefficients.py
Change two currently xfailed tests to pass and explain the use of tolerances on EMOS coefficients.
Testing:
=> Set specialised tolerances for estimate-emos-coefficients

improver/cli/__init__.py, improver/cli/estimate_emos_coefficients.py, improver_tests/acceptance/test_estimate_emos_coefficients.py
Description
Alter the behaviour when either the historic forecasts or truths are missing when estimating EMOS coefficients, so that in this case, nothing will be returned, rather than raising an error. This helps support routine running given that the apply-emos-coefficients CLI already supports the EMOS coefficients being optional.
This PR:
* Updates the estimate-emos-coefficients CLI so that if either the historic forecasts or truths are missing, then nothing is returned. This helps supports routine running during a spin-up period where multiple truths might exist without any historic forecasts available.
* Make a minor edit to `improver/cli/__init__.py` to support returning nothing, even if an output is specified.
* Test that no output file is created within the relevant CLI test. …
=> Alter behaviour of estimate-emos-coefficients CLI when either historic forecasts or truths missing

improver/cli/neighbour_finding.py, improver/ensemble_calibration/ensemble_calibration.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver/orographic_enhancement.py, improver/spotdata/neighbour_finding.py, improver/spotdata/spot_extraction.py, improver/threshold.py, improver/utilities/cube_manipulation.py, improver/utilities/load.py, improver/utilities/pad_spatial.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py, improver_tests/spotdata/spotdata/test_SpotLapseRateAdjust.py, improver_tests/utilities/cube_manipulation/test_enforce_coordinate_ordering.py
- Removed the return statement from the enforce_coordinate_ordering function which acts in place anyway.
- Updated all uses of the function to remove any assignment to new variable names.
- Updated the names of variables where necessary due to the removal of assignment.
- Deleted return type test for enforce_coordinate_ordering function.
Testing:
=> IMPRO-1562: enforce_coordinate_ordering in place only

improver/utilities/compare.py, improver_tests/acceptance/acceptance.py
If the RECREATE_KGO environment variable is set (to any value), the KGO files get updated in place in IMPROVER_ACC_TEST_DIR. This arrangement had issues with symlinks to central KGO stores, as the overwrite would follow symlinks before writing.
The KGO update is done **before comparison** between test output and KGO, so tests that update KGOs will pass.
The RECREATE_KGO environment variable specifies a path where updated KGO files will be placed. This could be a new directory in order to easily identify and collect the updated files, or it could be the same directory as IMPROVER_ACC_TEST_DIR.
The KGO update is done **after comparison** between test output and KGO, so only missing KGOs or comparison failures now result in updated KGOs. Tests that result in updated KGOs will fail, with a …
=> RECREATE_KGO user friendliness

improver/blending/weighted_blend.py, improver/blending/weights.py, improver/psychrometric_calculations/psychrometric_calculations.py, improver/utilities/cube_manipulation.py, improver/utilities/mathematical_operations.py, improver_tests/psychrometric_calculations/psychrometric_calculations/test_PhaseChangeLevel.py, improver_tests/utilities/cube_manipulation/test_sort_coord_in_cube.py, improver_tests/utilities/test_mathematical_operations.py
Fix use of positive attributes on height coordinate
Changed the use of a string that can be 2 options to use a bool instead.
It may be best to view via the two different commits.
Testing:
=> IMPRO-1577: Fix use of positive attributes on height coordinate

improver/calculate_sleet_prob.py, improver/cli/sleet_probability.py, improver_tests/acceptance/test_sleet_probability.py, improver_tests/calculate_sleet_prob/test_calculate_sleet_probability.py
Adds optional argument to demote snow-rain mismatch errors to warnings and sets sleet to zero in these cases so that we can run the new sleet-chains while a separate investigation is undertaken to fix the underlying science.
Testing:
=> Add work-around to sleet-probability code

improver/cli/__init__.py, improver/cli/compare.py, improver/cli/wxcode.py, improver/constants.py, improver/utilities/compare.py, improver/wxcode/utilities.py, improver/wxcode/weather_symbols.py, improver/wxcode/wxcode_decision_tree.py, improver/wxcode/wxcode_decision_tree_global.py, improver_tests/cli/test_init.py
Speed up command line help by avoiding importing heavy modules and reinstate Google docstring processing after #1101 broke it.
| command | master[*] | this branch |
|-|:-:|:-:|
| `improver help` | 4.438s | 2.977s |
| `improver help wxcode` | 2.733s | 1.257s |
[*] after applying fix to `clizefy` from this PR.
Testing:
=> Speed up command line help

improver/nowcasting/forecasting.py, improver_tests/acceptance/test_nowcast_extrapolate.py, improver_tests/nowcasting/forecasting/test_CreateExtrapolationForecast.py
IMPRO-1602
Modified test that checks extrapolate can run without orographic
enhancement to use cloud fraction rather than rainfall rate
See ticket for acceptance test data changes
Testing:
=> Nowcast extrapolate raise error if no orographic enhancement field for rainfall

.github/workflows/tests.yml
Switch GitHub Actions back on for PRs - need this to get the check at the bottom of pull request pages.
=> Switch GitHub Actions back on for PRs

improver/psychrometric_calculations/psychrometric_calculations.py, improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
The result of an investigation into whether the iteration should include updates to the latent heat term as the temperature value is adjusted. See IMPRO-1566 for full details.
This ticket contains a commit where the iteration does include this update so that a notebook could be derived to see its impact. The impact is only significant where the relative humidity is low, which is unlikely to be where precipitation is falling, so will not have an adverse effect on the discrimination between snow, sleet and rain phases.
Testing:
=> IMPRO-1566 wet-bulb temperature accuracy

improver/cli/phase_change_level.py, improver/cli/wet_bulb_temperature.py, improver/psychrometric_calculations/psychrometric_calculations.py, improver/utilities/mathematical_operations.py, improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py, improver_tests/psychrometric_calculations/test_WetBulbTemperature.py, improver_tests/utilities/test_mathematical_operations.py
Due to extra task on the ticket.
Address the use of a string for a binary value.
Address makeing the individual plugins extract the required cubes they need from a CubeList.
- WetBulbTemperature uses all [CF standard names](http://cfconventions.org/Data/cf-standard-names/70/build/cf-standard-name-table.html)
- PhaseChangeLevel uses `wet_bulb_temperature_integral` which is not a CF standard.
Use generator instead of a function
Adds randomised order to a test.
Testing:
=> IMPRO-1568: Randomised list of cli inputs.

improver/cli/apply_emos_coefficients.py, improver_tests/acceptance/test_apply_emos_coefficients.py
Remove the use of the realizations_count option when re-creating the realizations within the apply_emos_coefficients cli.
Testing:
=> Ensure number of realizations output by the apply_emos_coefficients CLI matches the input

improver/cli/apply_emos_coefficients.py, improver_tests/acceptance/test_apply_emos_coefficients.py
Addresses IMPRO-1613
Changed the behaviour of the Apply EMOS CLI so it fails if it is passed only a coefficients cube. Before it would return this cube unchanged as it assumed the cube was a forecast cube.
Testing:
=> Apply EMOS CLI fails if only a coefficients file provided.

improver/utilities/load.py, improver_tests/acceptance/acceptance.py, improver_tests/acceptance/test_standardise.py
Enable reading nimrod radar files with iris while waiting for scitools/iris#3647 to make it through the pipeline.
Testing:
=> nimrod monkey patch

improver/blending/blend_across_adjacent_points.py, improver_tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py
It was found that triangular time blending was not returning the expected cube validity time/forecast period when blending period diagnostics (those with bounds on their time coordinates).
This PR makes the iris extraction used to extract the user specified time coordinate check the time point rather than the entire time coordinate; when checking the entire coordinate if the point falls within the bounds it is deemed a match.
I've added bounds to the unit test data. These now fail without the modifications made here.
Testing:
=> IMPRO-1607: Fix triangular time blending for bounded times

improver/blending/calculate_weights_and_blend.py, improver_tests/acceptance/test_weighted_blending.py, improver_tests/blending/calculate_weights_and_blend/test_WeightAndBlend.py
In cycle blending the latest cube is currently used to set the cycle time (forecast reference time). If a file is missing for a particular validity time in the cycle in which the blending occurs, the cycle time for the output will be set as the most recent cycle for which data was available. This results in the forecast reference times for the blended output files from a given cycle potentially differing from one another.
There is an associated suite PR which adds the ```--cycletime``` argument for cycle blending.
We may wish to consider adding a CLI test for this behaviour, but I have not had time.
This work:
- Ensures that if a cycletime argument is provided, even if we are processing a single cube in cycle blending, the cycletime of the output is updated.
- I've added a unit test to …
=> IMPRO-1606: Ensure cycle time updated in cycle blending

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_ConstructReliabilityCalibrationTables.py
Modify reliability calibration cubes to include a forecast reference time coordinate. This replaces use of the cycle_hour coordinate. 
The forecast reference time coordinate point is equal to the latest forecast cube that contributes to populating the table. The bounds of the coordinate describe the range of forecast FRTs that contributed.
This coordinate will provide one of the two components of metadata required for determining applicability (the cycling hour), and will also act as the provenance metadata.
Testing:
=> IMPRO-1623: Add forecast reference time coordinate to reliability calibration tables

improver/cli/nowcast_extrapolate.py, improver_tests/acceptance/test_nowcast_extrapolate.py
Description
Edits to support passing multiple orographic enhancement files into the nowcast extrapolate CLI, rather than a single file with multiple leadtimes.
Testing:
=> Pass multiple orographic enhancement files to nowcast-extrapolate CLI

improver/cli/generate_topography_bands_mask.py, improver/cli/generate_topography_bands_weights.py, improver/cli/nbhood_land_and_sea.py, improver/cli/neighbour_finding.py, improver/cli/standardise.py, improver/generate_ancillaries/generate_ancillary.py, improver/generate_ancillaries/generate_topographic_zone_weights.py, improver/psychrometric_calculations/psychrometric_calculations.py, improver/spotdata/neighbour_finding.py, improver/standardise.py
Whilst doing the work for IMPRO-1569 it became obvious that it is very easy to get confused as to the convention for land-sea mask. This PR ensures that all docstrings describing land-sea inputs say that land points are set to one and sea points are set to zero in the land-sea mask cube. Hopefully this will help avoid future confusion.
Testing:
=> Tidy up land sea docstrings

improver/calibration/utilities.py, improver/cli/apply_emos_coefficients.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver/ensemble_copula_coupling/utilities.py, improver_tests/acceptance/test_apply_emos_coefficients.py, improver_tests/calibration/utilities/test_utilities.py, improver_tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py, improver_tests/ensemble_copula_coupling/ensemble_copula_coupling/test_RebadgePercentilesAsRealizations.py, improver_tests/ensemble_copula_coupling/ensemble_copula_coupling/test_utilities.py
Addresses the last points of IMPRO-1569:
* Ensures that EnsembleReordering plugin handles masked data.
* Adds a function for combining calibrated land data with uncalibrated sea data.
* Adds CLI tests using the land sea option for apply-emos-coefficients CLI - a notebook showing the new data will follow
There were a couple of other minor changes I made, which are in separate commits so it's easier to see what they are.
Testing:
=> Impro 1569 apply emos land sea

improver/cli/__init__.py, improver/cli/nowcast_accumulate.py, improver/cli/nowcast_extrapolate.py, improver_tests/acceptance/test_nowcast_accumulate.py, improver_tests/acceptance/test_nowcast_extrapolate.py, improver_tests/cli/test_init.py
This PR is currently dependent on #1166 
Description
This PR modifies `create_constrained_inputcubelist_converter` so that multiple possible constraints can be provided, as long as only one constraint is valid. The purpose of this is to support multiple possible inputs being provided to the nowcast-extrapolate and nowcast-accumulate CLIs.
Testing:
=> Handle multiple possible names for nowcast advection velocity cubes

environment.yml
To conda-pack IMPROVER the dependencies of the pip dependencies (clize) must also be defined to be included in the conda env
=> explicitly define pip dependency dependencies

improver/threshold.py, improver_tests/threshold/test_BasicThreshold.py
Description
Minor edit and unit test for when trying to threshold a masked cube using fuzzy bounds.
This PR:
- Ensures that the output from thresholding is masked if the input is masked and fuzzy bounds are used. 
- Add a unit test to check the behaviour.
Testing:
=> Support thresholding a masked input with fuzzy bounds

improver/cli/convert_to_realizations.py, improver/cli/probabilities_to_realizations.py, improver_tests/acceptance/test_convert_to_realizations.py
Description
This PR exposes the `raw_cube` and `random_seed`  arguments already supported by the `percentiles_to_realizations` and `probabilities_to_realizations` CLI.
This PR:
- Adds `raw_cube` and `random_seed` arguments to the `convert_to_realizations`. The `random_seed` argument is needed to support testing of the CLI.
- Correction of typos in `probabilities_to_realizations` CLI.
- Addition of acceptance tests for the `convert_to_realizations` CLI. These tests are copies of existing tests for the `probabilities_to_realizations` and `percentiles_to_realizations` CLIs, respectively.
Testing:
=> Modify convert_to_realizations CLI to accept the raw_cube argument

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py
This plugin applies reliability calibration for the simple case of a consolidated (collapsed x/y) reliability table to a forecast cube. This consolidation helps ensure a sufficient sample count in the reliability table, which avoids issues such as unpopulated bins etc. It also allows a very fast application of the calibration using ```np.interp```.
An associated notebook demonstrates how the code can be extended to work with non-consolidated reliability tables.
There are currently no new unit tests as I would appreciate a review of the simplifications assumed before writing these in case the code changes substantially.
Testing:
=> IMPRO-1506: Plugin for applying reliability calibration.

.github/workflows/tests.yml
Secrets are only available to the repo owner, so the codacy-coverage actions shouldn't run on forks.
=> Remove codacy coverage running on forks

improver/wxcode/wxcode_decision_tree.py, improver/wxcode/wxcode_decision_tree_global.py, improver_tests/wxcode/wxcode/__init__.py, improver_tests/wxcode/wxcode/test_wxcode_decision_tree.py, improver_tests/wxcode/wxcode/test_wxcode_decision_tree_global.py
Addresses IMPRO-1601
Make weather_symbol tree definitions consistent.
Unit-tests for the weather symbols trees now include checks for consistency in the nested list structures and the similar lists that should have one fewer list-nesting level.
Updates the weather symbols trees to comply with these new tests.
Testing:
=> Impro1601 wxcode consistency checks

improver/cli/__init__.py, improver/memprofile.py
Closes #1180 memory profiling.
Description
Tracks the maximum memory usage of the code and creates a tracemalloc snapshot at the peak. I've also added a command line argument to call the memprofiling in line with the profile command: --memprofile=FILENAME.
Testing:
=> 1180 memory profiling

improver/utilities/save.py
Modified save wrapper to include all attributes on a cube that include ```mosg__``` as global attributes.
Testing:
=> IMPRO-1632: Ensure all mosg__ attributes are set as globals

improver/calculate_sleet_prob.py, improver/cli/interpolate_using_difference.py, improver/cli/sleet_probability.py, improver/utilities/interpolation.py, improver_tests/acceptance/test_interpolate_using_difference.py, improver_tests/acceptance/test_sleet_probability.py, improver_tests/calculate_sleet_prob/test_calculate_sleet_probability.py, improver_tests/utilities/test_InterpolateUsingDifference.py
Designed for use with phase-change-levels, this new plugin and CLI allow masked values in a field to be filled. The values used are calculated by subtracting the field where available from a complete reference field and then interpolating this difference field. The masked regions are replaced with the result of ```reference_field - interpolated_difference_field```, the rest of the field if left unchanged.
Testing:
=> IMPRO-1618: Interpolation using a difference field

.github/workflows/tests.yml
Fixes codecov only reporting on the latest master it has a record of (which doesn't update on PRs).
Means we have duplicates tests on PRs, but GitHub actions doesn't have a nice way around this.
=> Actions on pushes again (codecov fix)

improver/nowcasting/accumulation.py, improver_tests/nowcasting/accumulation/test_Accumulation.py
This PR adds the ```sum: time``` cell method to cubes produced by nowcast-accumulate. This cell method does **not** include an interval, as specified by the metadata standards document.
Testing:
=> IMPRO-1646: Accumulation cell method added to nowcast accumulations

improver/utilities/save.py, improver_tests/utilities/test_save.py
Addresses awkwardness of dealing with `prefix_list` variable.
Metadata cube `prefix_list` makes it difficult to use IMPROVER data with Iris, e.g. this cube has to be explicitly filtered out in `iris.load_cube` or it will fail. The standard on which the metadata cube is based is not released yet (even in draft) and may still change. After discussing it with metadata working group conclusion was reached that it's better to wait for the new metadata standard to reach more stable status. For now we should just use name-spaced attribute names for anything outside CF conventions to reduce the risk of future name collisions.
Testing:
=> remove prefix cube

codecov.yml
Adds a codecov yaml file to exclude the CLI directory from coverage statistics.
Testing:
=> Exclude cli/ from codecov statistics

improver/cli/__init__.py
Stray `*` characters in CLI doctring cause`Inline emphasis start-string without end-string`  warnings in help output.
=> fix docutils warning

improver/cli/combine.py, improver/cube_combiner.py, improver/utilities/cube_manipulation.py, improver_tests/cube_combiner/test_CubeCombiner.py, improver_tests/utilities/cube_manipulation/test_expand_bounds.py
There was an issue when calculating precipitation type rates and accumulations by multiplying a total precip rate / accumulation by probability of precipitation type (eg probability of snow).  Since the probability of type was a point time, the bounds on the time coordinate were being incorrectly removed.  This change prevents removal of bounds when combining cubes, and causes `expand_bounds` to raise an error if it would cause the removal of valid bounds from a coordinate.
Description
Testing:
=> Prevent removal of bounds when combining cubes

.github/workflows/tests.yml
Coverage is not currently being reported to Codacy from PRs or master branch. This appears to be due to the 'repo-owner' condition not being met.
Based on some trials in my personal fork, this check for the CODACY_PROJECT_TOKEN environment variable appears to work as intended. I was unable to get the if-condition to directly check `secrets`.
The actions run https://github.com/tjtg/improver/actions/runs/73630023 with this change correctly skipped codacy reporting and the run https://github.com/tjtg/improver/actions/runs/73635114 picked up the environment variable correctly but (intentionally) failed due to using a dummy/invalid codacy API token from secrets in my personal fork. Both of those actions runs are on the same commit ID as this PR - 9a1252a.
Testing:
=> Change codacy action to check environment variable

improver/utilities/spatial.py
The ```OccurrenceWithinVicinity``` plugin should not propagate values from underneath masked regions. It attempts to do this by only modifying points that are not masked in the input cube, but the vicinity process constructs neighbourhoods that do stretch into masked regions.
The ```maximum_filter``` function, imported from scitools, does not handle nan values, but ```OccurenceWithinVicinity``` uses np.nan values to fill masked data elements in the array before applying the filter. The filter thus returns np.nan values as maximums within the neighbourhoods, and these are assigned to unmasked points about which the neighbourhoods were constructed.
This PR fixes this issue by using ```-np.inf``` as the fill value instead, meaning that the maximum_filter will never choose these values as the …
=> IMPRO-1662: Alter occurrence within vicinity fill value.

improver/cli/apply_reliability_calibration.py, improver_tests/acceptance/test_apply_reliability_calibration.py
Description
This PR aims to update the `apply_reliability_calibration` CLI to support not supplying a reliability table. In this instance, the uncalibrated forecast will be passed through. 
Testing:
=> Support applying reliability calibration without a reliability table

improver/cli/__init__.py, improver/cli/nbhood_land_and_sea.py, improver/nbhood/use_nbhood.py, improver_tests/acceptance/test_nbhood_land_and_sea.py, improver_tests/cli/test_init.py, improver_tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py, improver_tests/nbhood/use_nbhood/test_CollapseMaskedNeighbourhoodCoordinate.py
The idea - collapse over topographic bands while looping over x-y slices rather than afterwards to avoid large intermediates.
Doesn't work yet, complains about zero weight sum during weight normalisation. @fionaRust, could you have a look and see if anything obvious jumps out.
CC: @BelligerG
=> Slim down topographic neighbourhood

improver/nbhood/recursive_filter.py, improver/nbhood/square_kernel.py, improver/utilities/pad_spatial.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py, improver_tests/utilities/test_pad_spatial.py
This PR modifies the ```pad_cube_with_halo``` function to accept any np.pad method. It then uses this functionality in the ```RecursiveFilter``` plugin to implement the padding using the symmetric method.
- Unit tests are updated to reflect the change in values.
- Additional tests added to cover a few more pad options (non-exhaustive).
- KGO updated and plotted in associated notebook.
Testing:
=> IMPRO-1331: Recursive filter modified to use symmetric padding

doc/rtd_environment.yml, improver/memprofile.py
Addresses #1229
Two minor documentation fixes:
- CLI documentation is not available on readthedocs. This is due to the readthedocs environment not including clize, so sphinx fails when processing the CLI modules which use clize. The fix here is to add clize to the environment.yml used for the docs generation.
- The asterisks in memprofile docstrings cause sphinx warnings as it attempts to interpret them as italics but they don't follow the expected format. The fix is to add escape slashes before each asterisk.
=> Read the docs fixes

improver/utilities/compare.py, improver_tests/utilities/test_compare.py
The comparison code was originally written to only be used from within tests, so used assertions to detect and report identified differences. It was converted to report errors and be usable as a CLI (outside of tests), but this instance of `assert` was missed in the conversion.
This is a minor fix to clean it up after noticing it when [reviewing other code](https://github.com/metoppv/improver/pull/1212#discussion_r414514951).
Testing:
=> Remove assert usage in comparison code

doc/source/frontpage.rst
Changes the build badge on the docs to point at github actions. Previously we were pointing at travis, but that is now defunct and shows as failed.
Testing:
=> Update build badge in readthedocs documentation

improver/cli/__init__.py, improver/cli/nowcast_accumulate.py, improver/cli/nowcast_extrapolate.py, improver/cli/recursive_filter.py, improver_tests/cli/test_init.py
Second attempt at loading multiple named cubes or strings.
This makes use of the new load_cube [PR #1228](#1228).
Error handling is weak due to how clize deals with errors.
Replaces #1183.
Testing:
=> IMPRO-1627: Take 2 on loading cubes or strings.

improver/cli/regrid.py, improver/cli/standardise.py, improver_tests/acceptance/test_regrid.py, improver_tests/acceptance/test_standardise.py
Splits standardise CLI out into `improver-standardise` and `improver-regrid`.  All code and tests cut & pasted from standardise to the new regrid CLI and tests.  No new code; one KGO file renamed and one removed.
Used existing CLI tests with one exception (where regridding and standardisation functionality were called in the same test).
Testing:
=> Regrid CLI

codecov.yml
We frequently run into issues where coverage appears to drop vs current master, but actually has not. We think this is based on a comparison between the very latest master and the PR, where the addition of extra tests on master since the PR base makes the coverage appear to decrease.
Tried to make codecov report against PR parent commits (https://docs.codecov.io/docs/commit-status#base), and always pass PR status (https://docs.codecov.io/docs/commit-status#informational).
Testing:
=> Disable codecov PR status

improver/nowcasting/optical_flow.py, improver_tests/nowcasting/optical_flow/test_OpticalFlow.py
Added option to optical flow plugin to calculate perturbation between a forecast and observation cube.  Plus a little minor refactoring of the `process` method.
Testing:
=> Optical flow as perturbation

improver/cli/generate_percentiles.py, improver/cli/generate_realizations.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver_tests/acceptance/test_generate_percentiles.py, improver_tests/acceptance/test_generate_realizations.py, improver_tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py
The ignore_ecc_bounds option is made available via the generate_realizations and generate_percentiles CLIs. This is primarily for use with global data.
Testing:
=> IMPRO-1713: Restore ignore_ecc_bounds option to PDF CLIs

improver/cli/threshold.py, improver/threshold.py, improver_tests/threshold/test_BasicThreshold.py
Adds ability to process each threshold cube while they are generated, rather than afterwords. Avoids creating large, intermediate arrays if there are many thresholds and realizations.
Resource use for engl feelsliketemp:
master:  mem 28GB, walltime 1:05 (user: 27s, system: 37s)
this PR: mem 1.3GB, walltime: 0:44 (user: 18s, system: 24s)
=> More memory efficient threshold

improver/blending/blend_across_adjacent_points.py, improver/blending/calculate_weights_and_blend.py, improver/blending/weighted_blend.py, improver_tests/acceptance/test_weighted_blending.py, improver_tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py, improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
Addresses #1246 
Reducing the memory requirements for weighted blending by slicing the data and not creating large weights arrays.
Feels like temperature:
- Before:
- 5148.673 MB
- 26.708 s
- After
- 225.746 MB
- 33.633 s
Blend adjacent points:
- Before:
- 1006.643 MB
- 11.041 s
- After
- 312.639 MB
- 10.754 s
Testing:
=> Weighted blend memory reduction

CONTRIBUTING.md, improver/cli/__init__.py, improver/utilities/save.py, improver_tests/cli/test_init.py, improver_tests/utilities/test_save.py
Description
Add `no_compression` option across all CLIs. Went with `no_compression`  as `zlib` was originally hardcoded True, so set compression as default.
Created unit tests.
closes #1268
Testing:
CLA
=> 1268 implement compression control

improver/cli/compare.py, improver/utilities/compare.py, improver_tests/acceptance/acceptance.py, improver_tests/acceptance/test_compare.py, improver_tests/utilities/test_compare.py
This change enables us to set a variety of attributes as ignorable, 
which will reduce the number of times we must update acceptance test 
data for trivial changes that are unimportant for checking data 
integrity.
Testing:
=> IMPRO-1725: Provide a list of ignorable attributes to the netcdf compare utility

improver/standardise.py, improver_tests/standardise/test_StandardiseMetadata.py
Located standardise bug to the case where an input field is an integer, but unit conversion escalates that to float.  Fixed bug by simple re-ordering, added comment and unit test.
Testing:
=> Fixed standardise bug and added unit test to cover broken case

improver/wxcode/wxcode_decision_tree.py, improver/wxcode/wxcode_decision_tree_global.py
A tiny fix to a non-issue in the weather symbol decision tree definitions.
Testing:
=> Remove breaks in strings in weather symbol decision tree definitions.

improver/nbhood/nbhood.py, improver_tests/convection/test_DiagnoseConvectivePrecipitation.py, improver_tests/nbhood/nbhood/test_BaseNeighbourhoodProcessing.py, improver_tests/utilities/test_DifferenceBetweenAdjacentGridSquares.py, improver_tests/utilities/test_OccurrenceWithinVicinity.py, improver_tests/wxcode/wxcode/test_utilities.py
Description
I changed a variety of unit tests to use the set_up_cubes.py code. However there is still a bug in test_DiagnoseConvectivePrecipitation.py. I have put comments in the code to try and explain what is happening. I don't think it is an IMPROVER issue right now.  
Testing:
There is a ValueError for one of the unit tests in test_DiagnoseConvectivePrecipitation which says "ValueError: 'time' is not in list"
=> Updating units tests to use set_up_variable_cube.

improver/grids.py, improver_tests/set_up_test_cubes.py, improver_tests/spotdata/spotdata/test_SpotLapseRateAdjust.py, improver_tests/test_set_up_test_cubes.py
Addresses #1273 / IMPRO-1760
Description
- Use kwargs for functions that use `set_up_variable_cube()` and removed duplicate docstrings
- Add `grid_spacing` and `domain_corner` args to `set_up_variable_cube()` and `construct_xy_coords()`
- Use `grid_spacing` and `domain_corner` to set up grid, using previous values if neither provided and around 0,0 if only `grid_spacing` provided
- Raise error if `domain_corner` provided but no `grid_spacing`
- Add `_create_y_x_arrays()` for to use by `construct_xy_coords()` to create x and y numpy.ndarray
Testing:
=> Modify set_up_test_cubes.py to allow for grid setup to be specified

improver/grids.py, improver_tests/blending/calculate_weights_and_blend/test_WeightAndBlend.py, improver_tests/metadata/test_utilities.py, improver_tests/nbhood/circular_kernel/test_check_radius_against_distance.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py, improver_tests/psychrometric_calculations/precip_phase_probability/test_PrecipPhaseProbability.py, improver_tests/set_up_test_cubes.py, improver_tests/standardise/test_RegridLandSea.py, improver_tests/test_set_up_test_cubes.py, improver_tests/utilities/test_TemporalInterpolation.py, improver_tests/utilities/test_pad_spatial.py, improver_tests/utilities/test_spatial.py
Addresses #1273 / [IMPRO-1770](https://exxconfigmgmt:6391/browse/IMPRO-1770)
Description
Added new default `grid_spacing` values to `construct_yx_coords()` then modified unit tests that relied on the previous test grid setup to either use the new values or set up a grid using the `domain_corner` and `grid_spacing` arguments. Hard coded default grid setup removed from set_up_test_cubes.py.
Testing:
=> Impro 1770

improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py, improver_tests/test_PostProcessingPlugin.py
Addresses #911 Part 1.
Improved testing for WeightedBlendAcrossWholeDimension
This includes:
- better boundry checking
- following the clean path of the code
This PR right now does not question if the functions should be changed, but that can be open for discussion.
Better testing of the if statement 
`improver/__init__.py`
```python
if (
"title" in cube.attributes.keys()
and cube.attributes["title"] != default_title
and "Post-Processed" not in cube.attributes["title"]
):
```
Tests that the function returns normally when the percentile coord has enough points to blend.
Tests that the function doesn't throw an error when the validity times are the same but `self.timeblending` is `False`
reduced cube length down to 2 for better boundry checking.
Tests the path of invalid shape.
Tests when a …
=> Mutation testing 1

environment.yml, improver/generate_ancillaries/generate_timezone_mask.py, improver_tests/generate_ancillaries/test_GenerateTimezoneMask.py
This PR includes a new plugin for creating masks of timezone information to be used as ancillaries.
Note that it uses a package not currently in the stack. See the ticket for information.
Testing:
=> IMPRO-1778: Plugin for timezone mask creation

improver/cli/wind_downscaling.py, improver_tests/spotdata/spotdata/test_SpotLapseRateAdjust.py, improver_tests/spotdata/spotdata/test_build_spotdata_cube.py, improver_tests/synthetic_data/test_set_up_test_cubes.py
Adds pylint subscription exemptions where required. These can probably be removed when we have a newer pylint version; recorded in stack upgrade sticky ticket.
I have also removed a chunking fix from the wind downscaling CLI. This relies upon an iris variable that no longer exists in the newer version of iris. The reason for this fix is well documented in #669 which also states that the fix can be removed when dask is upgraded beyond version 0.19.3 ([comment](https://github.com/metoppv/improver/issues/669#issuecomment-435075462)). The os43-2 stack and the other stacks we commonly use (default-current, experimental-current) all now include dask v1.0.0.
Testing:
=> Pylint fixes following stack change

improver/generate_ancillaries/generate_timezone_mask.py, improver_tests/generate_ancillaries/test_GenerateTimezoneMask.py
The timezonefinder module is imported in the init of the GenerateTimezoneMask plugin. This is instantiated for all the unit and acceptance test, so they must all be skipped if the module is not available. Pylint further checks that imports are available, so to work around this a check has been added to the import that satisfies pylint in the absence of the module.
Testing:
=> Modify import and test skipping for timezonefinder module

improver/synthetic_data/set_up_test_cubes.py, improver_tests/calibration/ensemble_calibration/helper_functions.py, improver_tests/calibration/ensemble_calibration/test_ApplyEMOS.py, improver_tests/calibration/ensemble_calibration/test_CalibratedForecastDistributionParameters.py, improver_tests/calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py, improver_tests/metadata/test_utilities.py, improver_tests/synthetic_data/test_set_up_test_cubes.py, improver_tests/utilities/test_cube_extraction.py, improver_tests/utilities/test_load.py
Addresses #1273 
- Add ability to add height/pressure level as a dimension coordinate.
- Add tests to test new dimension.
- Add bounds to y and x coordinates using guess_bounds().
- Modify tests that failed as a result of adding bounds.
Testing:
=> 1273 Modify set_up_test_cubes to provide additional functionality for metdata cube generation CLI.

improver/calibration/ensemble_calibration.py, improver/calibration/utilities.py, improver_tests/calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
This PR adds the forecast period bounds to the emos coefficient cubes coordinates. This is required as the entire coordinate is checked when applying the coefficients, so without these bounds an exception is raised when calibrating period diagnostics.
An alternative approach would be to only check the coordinate point and ignore the bounds, but the chosen approach has the benefit of ensuring that we cannot apply the coefficients for an instantaneous temperature to a period temperature minimum/maximum.
Testing:
=> IMPRO-1801: Added the forecast period bounds to emos coefficients cubes

improver/calibration/reliability_calibration.py, improver/cli/apply_reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py
Adds a user configurable bin fraction to determine whether a threshold can be calibrated. This allows thresholds for which there are incomplete forecast bins (as measured against the minimum_forecast_count) to still be calibrated.
This may need slight modification following work in IMPRO-1810/1811.
Testing:
=> IMPRO-1812: Configurable bin fraction for reliability calibration

doc/source/conf.py
Description
Update intersphinx mapping for Iris due to an update to the url of the latest Iris build. The latest version of Iris is now documented at https://scitools-iris.readthedocs.io/en/latest/.  The previous url (https://scitools.org.uk/iris/docs/latest/) now automatically redirects to the latest webpage, however, this redirection doesn't work for fetching the intersphinx inventory that sphinx requires.
Currently affecting: #1322, #1317  
Testing:
=> Update intersphinx mapping for Iris

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_ManipulateReliabilityTable.py
Description
Alter the behaviour of the `assume_constant_observation_frequency` method within the ManipulateReliabilityTables plugin to work from the bin with the highest sample count to the bin with the lowest sample count, rather than the previous logic to always work from the lowest probability bin to the highest probability bin. This helps because usually the probability bins with lowest sample counts are more likely to show non-monotonic behaviour, so any anomalous behaviour of low sample count bins, either for the low or high probability bins, can be removed, in order to guarantee a monotonic observation frequency. A monotonic observation frequency is desirable to avoid odd spatial behaviour when calibrating.
Testing:
=> Update to constant observation frequency assumption

improver/cli/field_texture.py, improver/field_texture.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_field_texture.py, improver_tests/test_field_texture.py
This PR:
1. Amends the field texture plugin to support deterministic field texture input i.e. an input without a realization coordinate.
2. Adds support for blending field texture by adding the specification of a `model-id-attr` argument, similar to e.g. the [uv-index](https://github.com/metoppv/improver/blob/master/improver/cli/uv_index.py) or [feels-like-temp](https://github.com/metoppv/improver/blob/master/improver/cli/feels_like_temp.py) CLIs. The `model_id_attr` attribute is then available to enable model blending.
Testing:
=> Support deterministic field texture input and blending of field texture output

improver/field_texture.py, improver_tests/acceptance/SHA256SUMS
Numpy divide is modifying data where the input is zero. This is not the expected behaviour and means the plugin is not producing the expected output.
This PR modifies the division to use indexing instead which does work as expected.
Testing:
=> Replace np.divide with indexed division in texture plugin

improver/cli/convection_ratio.py, improver_tests/acceptance/SHA256SUMS
Description
This PR removes the automatic collapsing of realizations within the convective_ratio cube that is output from the convection_ratio CLI.
Testing:
=> Remove collapsing of realizations in the convection_ratio CLI

.github/workflows/tests.yml
Added an option to reset the cache to combat caching an outdated library in conda.
We came across an issue with the forks using a different version of sphinx to master, this was down to master using a cached conda build. Github caches expire automatically after 7 days of not writing to them, but do not provide an explicit way to empty a cache, so by providing a `cache_number` we can reset the cache as required if this problem should ever arise again in the future.
=> Added a cache version number, to reset cache as needed

improver/field_texture.py, improver_tests/test_field_texture.py
Follow up from #1310 
Main issues addressed in this PR:
- plugin class instance re-used as a constant between tests (generate fresh plugin instances for each test case)
- duplication in fixtures (moved to other fixture or test function)
- duplication in similar tests (combined using parametrize)
- FieldTexture class used a variable `self.cube_name` only for passing to an internal method (replaced with explicit variable in method call) 
The github diff display struggles with test_field_texture.py. For reviewing, it may be best to look at complete files before/after side by side.
Testing:
=> Clean up of FieldTexture tests

improver/calibration/reliability_calibration.py, improver/utilities/cube_manipulation.py, improver_tests/utilities/cube_manipulation/test_MergeCubes.py
Lowers the memory cost of construct reliability calibration table from ~3.6 GB to ~2.1 GB. Increases the time from 264.074s to 266.197s.
Description
Testing:
=> Construct reliability calibration mem reduction

improver/cli/recursive_filter.py, improver/nbhood/recursive_filter.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py
This PR modifies the recursive filter plugin and CLI to alter the way the coefficients cubes are passed in. The CLI is modified to simply accept a list without any checks. The plugin is modified to order the cubes such that the x and y coefficient cubes can be identified.
Additional changes:
- Remove the _set_smoothing_coefficients method as it didn't do a great deal. Move the padding into the _validate_and_pad_coefficients method so that it can be done within a loop.
- Modify various of the tests in _validate_and_pad_coefficients to make use of the loop.
- Added an additional test to show the symmetrical padding is working as expected (though this is tested in the padding code as well) and one to show return order is correct regardless of input order.
- Modified tests to work with new …
=> IMPRO-1865: Modify recursive filter plugin to receive coefficients as cubelist

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_AggregateReliabilityCalibrationTables.py, improver_tests/calibration/reliability_calibration/test_ConstructReliabilityCalibrationTables.py
Description
This PR primarily updates the `ConstructReliabilityCalibrationTable`s plugin to support a masked truth. This affects the populating of the reliability table and adding the reliability tables for each timestep. The addition of the reliability tables with masked data is designed, so that only points that are always masked will be masked in the resulting reliability table. This avoids temporary outages, as might occur within, for example, a radar field, where a point might otherwise always be masked, if it is masked within one timestep within the training dataset.
Testing:
=> Handle masked truth within reliability calibration

improver/utilities/ancillary_creation.py
Modification of mandatory attributes in place seems to affect multiple tests.
This PR modifies the code to use a copy of the mandatory attributes rather than the original when creating a new smoothing coefficients cube. When running the parallel pytest acceptance tests it is found that modifying this default dictionary effects 
multiple tests.
I have no idea why the default dictionary being overwritten in one acceptance test affects the others, but it does.
Testing:
=> IMPRO-1890: Fix issue with parallel acceptance tests caused by modification of default attributes

improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py, improver_tests/wxcode/wxcode/test_utilities.py
Completes work to replace all unit tests using time in "hours" to use integer seconds, via the standard test cube setup functions.
Testing:
=> Finish integer seconds

improver/utilities/ancillary_creation.py, improver_tests/utilities/ancillary_creation/test_OrographicSmoothingCoefficients.py
This small change ensures we are using the absolute value of the orographic gradient when generating smoothing coefficients. This only impacts coefficients generated using a power that is odd or less than 1. The unit tests have been modified to include a negative gradient to test this change.
Testing:
=> IMPRO-1840: Modify recursive filter coefficient generation

improver/ensemble_copula_coupling/constants.py
Adds bounds for data named `lwe_thickness_of_sleetfall_amount` and `thickness_of_rainfall_amount` (identical to values for snow) so that engl sleet chain can extract a 50th percentile.
Testing:
=> IMPRO-1815 sleetacc and rainacc bounds for ECC

improver/cube_combiner.py, improver_tests/cube_combiner/test_CubeCombiner.py
The CubeCombiner plugin now throws a `TypeError` if the specified combine operation results in float64 data.
Testing:
=> IMPRO-1815: reject float64 data in combine plugin

.github/workflows/tests.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ and https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
=> Update add-path in Actions

improver/blending/spatial_weights.py, improver/blending/weighted_blend.py, improver/field_texture.py, improver/utilities/cube_manipulation.py, improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py, improver_tests/utilities/cube_manipulation/test_collapsed.py
Cube collapsed wrapper demotes data and coordinate types that have been escalated to float 64.
There is a change to the output of a weighted blending unit test.  The plugin should not have been changing the datatype of a coordinate irrelevant to the blending functionality.  The new implementation only de-escalates types that were escalated by the iris `collapsed` call, and does not "correct" non-standard types on the input cube.
Testing:
=> Demotion of datatypes in "collapsed" wrapper

improver/cli/apply_night_mask.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_apply_night_mask.py
The apply-night-mask CLI was written and tested for use with UV values.  However we've needed to apply it in the suite to post-processed probabilities, to ensure night values aren't smoothed out by neighbourhood processing.  This PR adds additional checks for safe use of probabilities with this CLI.
Testing:
=> Unsafe night mask

improver/cli/combine.py, improver/cube_combiner.py, improver_tests/cube_combiner/test_CubeCombiner.py, improver_tests/cube_combiner/test_CubeMultiplier.py
Single responsibility principle.  Splits `CubeCombiner` into two plugins: a "parent" plugin to apply linear operators, and a `CubeMultiplier` plugin to do the additional work of broadcasting to threshold coordinates in the "multiply" case.
Unit tests have not been changed or extended - existing tests have been copied for `CubeMultiplier` with updated calls.  This, and the passing of the "combine" CLI tests, show that functionality is unchanged with this refactor.
Testing:
=> Refactor CubeCombiner

.github/workflows/tests.yml, CONTRIBUTING.md, environment.yml
Addresses #1382 
Run bandit and safety as part of CI. Bandit finds common security issues in Python code. Safety checks installed dependencies for know security vulnerabilities. 
If bandit/safety find any issues the tests will _not_ fail. However, the output is written to the log (in GitHub Actions) for inspection.
Testing:
CLA
=> Add security checks

improver/wxcode/weather_symbols.py, improver_tests/wxcode/wxcode/test_WeatherSymbols.py
In an attempt to apply some Python training, I've refactored the "invert_condition" function in WeatherSymbols to remove an if..elif..elif..elif block. The code will no longer allow unrecognised comparators rather than returning them unchanged.
Testing:
=> Reduces code complexity in one part of weather_symbols.py.

improver_tests/acceptance/test_map_to_timezones.py, improver_tests/acceptance/test_nowcast_accumulate.py, improver_tests/acceptance/test_nowcast_extrapolate.py, improver_tests/acceptance/test_nowcast_optical_flow_from_winds.py, improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py, improver_tests/nowcasting/pysteps_advection/test_PystepsExtrapolate.py, improver_tests/orographic_enhancement/test_OrographicEnhancement.py, improver_tests/precipitation_type/snow_fraction/test_SnowFraction.py
A collection of fixes to a few issues:
- Acceptance tests for the map-to-timezones CLI were not being skipped when the acceptance test KGOs were not present
- Unit tests using pysteps were being skipped if pysteps was not available, but acceptance tests using pysteps were attempting to run
- Some tests used the [iris.cube.xml](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/cube.html#iris.cube.Cube.xml) method to compare cubes, but didn't actually call the method. This caused the test to compare two references to the method/function, rather than XML representations of the cube.
- Numpy allclose was being used inside other test assertions. This produced a true/false output on failure, rather than a useful explanation of the differences between the arrays.
Testing:
=> Collection of minor bug fixes

environment.yml
Relates to #1397
Looking at the functions of the failing tests and the location of the failing points suggests that scipy.interpolate.griddata is the cause.
Downgrading scipy to 1.3.3 results in the acceptance tests passing.
Downgrading scipy to 1.4.1 results in 5 (of the original 8) tests failing:
```
FAILED improver_tests/acceptance/test_interpolate_using_difference.py::test_filling_without_limit
FAILED improver_tests/acceptance/test_interpolate_using_difference.py::test_filling_with_maximum_limit
FAILED improver_tests/acceptance/test_phase_change_level.py::test_phase_change[snow-sleet-snow_sleet-T
rue]
FAILED improver_tests/acceptance/test_interpolate_using_difference.py::test_filling_with_minimum_limit
FAILED improver_tests/acceptance/test_phase_change_level.py::test_phase_change[sleet …
```
=> Pin scipy to 1.3.3 in environment.yml

improver/cli/threshold.py, improver/threshold.py, improver_tests/acceptance/test_threshold.py, improver_tests/threshold/test_BasicThreshold.py
Minor tidy-up of threshold plugin and CLI.  Main points:
- Factored various bits of complexity out of `__init__` method
- Changed `add_threshold_coord` to use scalar coordinate and merging, rather than creating lots of new cubes to concatenate
- Changed realization collapse to only collapse over realizations using simple code, rather than unnecessarily calling the much more complex weighted blending code.  This change should be followed by the simplification noted in the TODO in the cli, which has not been implemented in this PR to avoid changes to the suite at this time.
Testing:
=> Threshold simplification

improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver/metadata/probabilistic.py, improver/threshold.py, improver_tests/ensemble_copula_coupling/test_ConvertProbabilitiesToPercentiles.py, improver_tests/metadata/test_probabilistic.py, improver_tests/threshold/test_BasicThreshold.py
Final part of metadata standard.
Cell methods on an initial dataset (eg maximum temperature in period) don't apply directly to the thresholded probabilities (it is not a maximum probability in time, but a probability of maximum in time.  The cell method can't be transferred to the relevant coordinate (https://github.com/SciTools/iris/issues/3946). This PR updates the cell method to clarify that it refers to the threshold-type coordinate, rather than the probability data and reverses this in the ECC to-percentiles plugin.
Testing:
=> Update cell methods for probability data

improver/cli/convection_ratio.py, improver/precipitation_type/convection.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_convection_ratio.py
- This is passed to the plugin
- This triggers copying the named attribute from the input cube to the output cube
- Acceptance test updated to use this new argument
- Acceptance test data KGO updated
Allows the output to be consumed by the weighted-blending CLI.
Testing:
=> Adds model-id-attr to convection-ratio CLI

improver/between_thresholds.py, improver/calibration/__init__.py, improver/cube_combiner.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver/metadata/probabilistic.py, improver/precipitation_type/shower_condition.py, improver/wxcode/weather_symbols.py, improver_tests/calibration/ensemble_calibration/helper_functions.py, improver_tests/cube_combiner/test_CubeMultiplier.py, improver_tests/ensemble_copula_coupling/test_ConvertProbabilitiesToPercentiles.py, improver_tests/metadata/test_probabilistic.py
Cube names were not being regenerated correctly for "in vicinity" diagnostics through ECC.  Traced issue to utility being inappropriately used.  Wrapped utility for different purposes and renamed wrapper functions to specify clearly the intended usage.
Testing:
=> Vicinity names

.github/workflows/tests.yml, improver/__init__.py, setup.cfg, setup.py
Use `setuptools_scm` to automatically get version from git tags (as suggested by/discussed with Tom & Tomek).
Description
Testing:
- [N/A] Ran tests and they passed OK
- [N/A] Added new tests for the new feature(s)
CLA
- [N/A] If a new developer, signed up to CLA
=> Use setuptools_scm to automatically obtain version

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_AggregateReliabilityCalibrationTables.py
Description
This PR makes a minor edit to the reliability calibration error handling to support aggregation when the reliability table has been constructed using a single forecast and truth pair.
Testing:
=> Minor edit to checking of overlapping forecast reference time bounds

improver/synthetic_data/set_up_test_cubes.py, improver/wxcode/weather_symbols.py, improver_tests/synthetic_data/test_set_up_test_cubes.py
Weather symbols tidy up PR #1421 has some things in it that ought to break the tests, but don't.  This PR fixes the underlying issues, namely:
- Temporary clause in weather symbols code that allows for non-conformant metadata.  Now that we have a finalised metadata standard this should not be necessary.
- Error setting up "in vicinity" probability metadata in unit test setup functions
The blending suite has been run and confirmed that weather symbols are correctly produced from individual model suites at version 0.16.0.
Testing:
=> Weather symbols vicinity inputs

improver/calibration/ensemble_calibration.py, improver/cli/estimate_emos_coefficients.py, improver_tests/calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
Description
Minor PR to update the default tolerance within the estimate-emos-coefficients CLI. 
Relates to #1394, #1400.
Testing:
=> Use 0.02 as default EMOS tolerance

.github/workflows/tests.yml
Slow conda environment creation has been noticed recently, such as in [PR #1411 review comment](https://github.com/metoppv/improver/pull/1411#pullrequestreview-586505977) and [PR #1424 actions logs](https://github.com/metoppv/improver/pull/1424/checks#step:4:7). The py36 environment in particular takes a long time for conda to do its dependency solving.
Github actions cache minimises the time required once the cache is warm, but initial runs with a cold cache are very slow.
The main change here is to use the [mamba](https://github.com/mamba-org/mamba#mamba) package to do the dependency solving. Mamba is much faster due to using an external C++ solver (same library as the RPM package manager). Install times are reduced from over an hour to around 2 minutes.
The second change is to use …
=> Reduced conda environment installation time on GH actions

.github/workflows/tests.yml
Now that #1386 is resolved, allow bandit to fail if new issues are introduced.
=> Allow bandit to return failure

setup.cfg
Due to unavailability of scipy 1.3.3 for Windows on conda-forge (https://anaconda.org/conda-forge/scipy/files?version=1.3.3), widen scipy version requirement. See https://github.com/conda-forge/staged-recipes/pull/13867 for details of Windows build.
Have tested that the acceptance tests pass for 1.3.0, 1.3.1, 1.3.2 and 1.3.3
cc @tjtg 
Testing:
- [N/A] Ran tests and they passed OK
- [N/A] Added new tests for the new feature(s)
CLA
- [N/A] If a new developer, signed up to CLA
=> Widen scipy requirement

improver/blending/weighted_blend.py, improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
Addresses #1215
Speed up `PercentileBlendingAggregator` using a more vectorised approach. This gives around a 5x speedup using the test script below. There is probably room for further improvement using numba.
I increased the tolerance in one of the tests slightly because it was failing, I think this is just a floating point issue since the calculation is essentially the same.
```
import numpy as np
import time
from improver.blending import weighted_blend
perc_values = np.random.rand(50, 10)
perc_values = np.sort(perc_values, axis=1)
percentiles = np.linspace(0, 1, 10)
weight = np.random.rand(50)
t = time.time()
ans = weighted_blend.PercentileBlendingAggregator.blend_percentiles(perc_values, percentiles, weight)
print(time.time() - t)
```
Testing:
=> Speed up PercentileBlendingAggregator (fixes #1215)

envs/environment_py37_iris24.yml, setup.cfg
Addresses #1435 
Add missing dependencies to `setup.cfg`. These are packages that are imported directly in IMPROVER code but were not listed as dependencies.
This PR also updates the Python 3.7 / Iris 2.4 Conda environment file. This includes removing pip and packages installed with pip from PyPI as all packages are now available from conda-forge.
There is also a PR for the conda-forge feedstock adding these changes there too: see https://github.com/conda-forge/improver-feedstock/pull/2
Testing:
=> Add missing dependencies

bin/improver-tests, improver_tests/test_licence.py
Move the licence header check from `bin/improver-tests` into pytest. This avoids needing to run a separate tool for this task and also makes the licence check run as part of CI on Github Actions.
Resolves #1416 
Testing:
=> Move licence check into pytest

improver/blending/calculate_weights_and_blend.py
While explaining code to a colleague, it became obvious that the CLI and plugin associated with weighted blending had different doc-strings. The CLI is clearly better, so I've copied the text to the relevant places in the plugin.
Testing:
=> Copies more descriptive docstrings from weighted-blending CLI to WeightAndBlend plugin

.github/workflows/tests.yml, improver_tests/acceptance/test_interpret_metadata.py
Fix acceptance tests for the metadata interpreter missing the `skip_if_kgo_missing` check. This causes the acceptance tests to fail rather than be skipped when running without KGO data available (eg. `IMPROVER_ACC_TEST_DIR` environment variable not set).
Change the github actions configuration to remove the marker specification - this was causing the acceptance tests to be ignored during pytest test discovery rather than the tests skipping being checked on Github actions. This change will cause the other issue to be picked up as part of Github actions.
Testing:
=> Fix metadata interpreter acceptance tests skipping

improver_tests/acceptance/test_regrid.py
Addresses #1464 
Description:   
Add one more acceptance test for bilinear without land-sea mask awareness , as suggested by Fiona.
The new bilinear-2 regridding option should produce the same result as the original bilinear regridding option.
Therefore, this added test shares the existing kgo.nc with  the original bilinear regridding test, and no new acceptance data file is required.
It addressed the last item in https://github.com/metoppv/improver/issues/1464. 
Testing:
- [Y] Ran tests and they passed OK
- [ Y] Added new tests for the new feature(s)
=> Add one more acceptance test for new regridding

doc/source/extended_documentation/regrid/bilinear_land_sea.rst
Description: 
Every significant word in headings of the regridding document should be capitalized. Just a minor fixing for consistence with the documentation style.
Testing:
- [Y] Ran tests and they passed OK
=> capitalize words for heading in regridding doc 

doc/source/Code-Style-Guide.rst
Drop back to bare versions after talk with @tjtg - then we can amend the improver feedstock on conda forge too.
Amend to use annotated tags via command line rather than GitHub's web interface lightweight tags.
=> Amend tagging instructions

improver/utilities/cube_manipulation.py, improver/wind_calculations/wind_components.py, improver_tests/utilities/cube_manipulation/test_compare_coords.py
The compare_coords function now accepts an additional argument that takes the form of a list of coordinate names. This list is checked when cycling through the cubes to ensure that the presence / absence of a coordinate in this list from one or more cubes is not flagged as a difference. Differences in values for an ignored coordinate are also ignored.
Testing:
=> compare_coords function modified to accept ignored_coords list

improver/regrid/grid.py, improver/utilities/spatial.py, improver_tests/utilities/test_spatial.py
I had several running errors during running neighbourhood processing and regridding. 
"ValueError: Coordinate longitude points are not equally spaced"
It is from calculate_grid_spacing function.  It happened for several BOM-commonly-used grids.
Grid spacing is from np.diff(coord). I think that it is reasonable to add rtol=7.0e-5 which made all failure grids passed.
Testing:
=> add rtol for calculating grid spacing

doc/source/Code-Style-Guide.rst
We jumped the gun a bit, a bit hypocritically, with making the last tag. I've added text to the release process to help us not do that in the future.
=> Update making a release guidelines

envs/environment_py37_iris30.yml, envs/environment_py38_iris30.yml, setup.cfg
Testing of environment related to #1555 
Description
This PR is intended to test the cause of unit test failures in #1555 that are unrelated to the contents of that PR.
Testing:
=> Move statsmodels in environment yml files

improver/cli/threshold.py, improver_tests/acceptance/test_threshold.py
Moves position of land-sea-mask in threshold CLI to be positional so that the suite can supply it as a node.
Addresses #1518 
The suite now supplies ancillary files in the list of input cubes. Therefore, this must be a positional argument, not a keyword argument.
Testing:
=> Moves position of land-sea-mask in threshold CLI

improver/lightning.py, improver_tests/lightning/test_LightningFromCapePrecip.py
Addresses #1518
We need this so we can generate data for days 6-8 when only 3h data are available.
Testing:
=> Modifies LightningFromCapePrecip plugin to accept 3h precipitation-rate-max data

doc/source/conf.py
Stylesheets are currently broken on readthedocs  and the resulting appearance of the documentation is degraded. This is caused by the readthedocs sphinx theme not applying due to broken configuration. Similar stylesheet issues occur on local documentation builds via sphinx.
Current readthedocs: https://improver.readthedocs.io/en/latest/index.html
This PR branch: https://improver-tjtg.readthedocs.io/en/fixdocscss/index.html
Testing:
=> Fix Sphinx documentation stylesheet

improver/cli/estimate_emos_coefficients_from_table.py, improver_tests/acceptance/test_estimate_emos_coefficients_from_table.py
Related to https://github.com/metoppv/mo-blue-team/issues/108
Description
This PRs amends the estimate_emos_coefficients_from_table to add filtering by cycletime (blend_time) as part of loading of the parquet file. This reduces the time taken to load from the parquet files (from 2 minutes 45 seconds to ~2 minutes for a test dataset) but also significantly reduces the memory usage. Please see comment: [#1](https://github.com/metoppv/mo-blue-team/issues/108#issuecomment-960539811) and [#2](https://github.com/metoppv/mo-blue-team/issues/108#issuecomment-961243485).
As we're now filtering on diagnostic and cycletime, rather than just diagnostic, we now expect there to be instances where the forecast dataframe is empty but we don't want to fail e.g. because we're trying to calibrate at a …
=> Add filtering by cycletime to estimate_emos_coefficients_from_table.py

improver/calibration/dataframe_utilities.py, improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py
Related to https://github.com/metoppv/mo-blue-team/issues/108
Description
This PR moves the filtering by experiment earlier within the preparation of the dataframes for conversion into cubes. This is because of an issue with different experiments having different values for the latitude and longitude for the same WMO ID. This inconsistency was causing issues when trying to use the latitude and longitude from the forecasts for use within the truth dataframes as the latitude and longitude within the truth dataframes are themselves subject to correction and adjustment, which could lead to mismatches when combining latitude and longitudes from multiple dates into a single cube.
Testing:
=> Move filtering by experiment within EMOS

improver/calibration/dataframe_utilities.py, improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py
Related to https://github.com/metoppv/mo-blue-team/issues/108
Description
This PR adds resilience by removing duplicates in the forecasts and truths. These duplicates would typically arise in the form of a whole cycle of duplicates. Support is also provided for a one-off duplicate.
Testing is described in [this comment](https://github.com/metoppv/mo-blue-team/issues/108#issuecomment-964995604).
Testing:
=> Remove duplicates in the forecast and truth for EMOS

improver/cli/apply_emos_coefficients.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver_tests/acceptance/test_apply_emos_coefficients.py, improver_tests/ensemble_copula_coupling/test_ResamplePercentiles.py
Closes: https://github.com/metoppv/improver/issues/1618
Description
This PR provides a simpler solution compared to https://github.com/metoppv/improver/pull/1615 by making a minor extension to the `ResamplePercentiles` plugin to support passing in a list of percentiles that are not necessarily quantiles.
Testing:
=> Extend ResamplePercentiles to simplify ensuring of consistent percentiles within EMOS

.github/workflows/ci.yml, .github/workflows/scheduled.yml, .github/workflows/tests.yml, doc/source/Dependencies.rst, doc/source/Running-at-your-site.rst, doc/source/index.rst, envs/conda-forge.yml, envs/environment_a.yml, envs/environment_b.yml, envs/latest.yml, improver/metadata/amend.py, improver/psychrometric_calculations/psychrometric_calculations.py, improver_tests/acceptance/test_checksums.py, improver_tests/acceptance/test_interpolate_using_difference.py, improver_tests/acceptance/test_phase_change_level.py, improver_tests/generate_ancillaries/test_GenerateTimezoneMask.py, improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py, setup.cfg
This PR is intended to improve handling of dependencies and conda environments used for testing.
- Pin package versions in existing example environments so that these environments are more explicit.
- Rename existing example environments to avoid naming which is specific to the package versions used.
- Add two more environments:
+ **latest** - full set of packages, as recent versions and minimal pinning as possible
+ **conda-forge** - a minimal environment intended to match required dependencies listed on the [conda-forge feedstock](https://github.com/conda-forge/improver-feedstock)
- Remove dependencies from `setup.cfg`.
+ The expectation is that direct usage of setup.cfg (eg. `pip install -e .`) is by developers who will provide their own environment such as from conda.
+ Other …
=> Better handling and documentation of dependencies

improver/calibration/ensemble_calibration.py, improver/cli/apply_emos_coefficients.py, improver_tests/calibration/ensemble_calibration/test_CalibratedForecastDistributionParameters.py
This is one way of working around an issue we've had with using coefficients that happen to be an hour out. They are still the best available coefficient, so add an option to try to use this. May end up abandoned if we figure out we want a different solution!
=> Add time mismatch tolerating for apply emos

improver/cli/threshold.py, improver/threshold.py, improver_tests/threshold/test_BasicThreshold.py
Addresses #https://github.com/MetOffice/improver_suite/issues/1048
Unit conversion is currently causing noise in the representation of the thresholds coordinate.
This is due to floating point arithmetic which is made worse by representation of the thresholds as 32-bit floats.
This PR proposes to define these thresholds as 64-bit but converting them to 32-bit post unit conversion before returning the final cube.
Confirmed that this gives reasonable representation for thresholds defined in the [precip_accumulation_thresholds.json](https://github.com/MetOffice/improver_suite/blob/master/etc/precip_accumulation_thresholds.json)
Testing:
=> Fix noise in precip accumulation thresholds

bin/improver-tests
This tiny PR makes flake8 report that it is okay when running improver-tests. Currently it is being run silently, which is not reassuring.
Testing:
=> Flake8 test success printing

improver_tests/ensemble_copula_coupling/test_ConvertProbabilitiesToPercentiles.py, improver_tests/ensemble_copula_coupling/test_ResamplePercentiles.py
#1621 describes a potential issue with the errors returned when ECC bounds are exceeded. There are some logs from suites suffering ECC bounds exceeded errors available (added to ticket), but these do not show the problem described. This PR simply makes the unit tests more rigorous by checking the entire returned error to ensure the expected values are included.
Closes #1621 
Testing:
=> IM-1621: Make ECC error and warning tests more rigorous

improver/wxcode/weather_symbols.py, improver_tests/wxcode/wxcode/test_WeatherSymbols.py
This PR speeds up the creation of gridded weather symbols by a factor of 5 by using the first opportunity in the code to thin down the amount of data that is processed thereafter.
Notes on the profiling etc. can be found here: https://github.com/metoppv/mo-blue-team/issues/180
Testing:
=> MOBT-180: Weather symbol speed up

improver/cli/__init__.py, improver/cli/blend_adjacent_points.py, improver/cli/nowcast_accumulate.py, improver/cli/phase_change_level.py, improver/cli/wxcode.py, improver_tests/cli/nowcast_accumulate/test_name_constraint.py, improver_tests/cli/test_init.py
Addresses #1612
Description
- Ensures no lazy loading in the following improver CLI calls: `blend-adjacent-points`, `nowcast-accumulate`, `nowcast-extrapolate`, `phase-change-level` and `wxcode`.
- Introduces new `cli.inputcube_nolazy` type (a non-lazy load type).
Testing:
----
lazy vs non-lazy comparison of these function calls as per https://github.com/metoppv/improver/issues/1612#issuecomment-968841368:
```
min % diff	min t lazy(s)	min t nolazy(s)	mean % diff	mean t lazy(s)	mean t nolazy(s) max % diff	max t lazy(s)	max t nolazy(s)	ncalls lazy	ncalls nolazy	Command
* 119%		34		8		129%		83		17		93%		103		37		980		1120		improver blend-adjacent-points --coordinate --central-point --blend-time-using-forecast-period --units --width
* 25%		129		99		24%		139		109		28%		168		126		17		21 …
```
=> ENH: Avoiding lazy loading in select command calls

improver/nbhood/circular_kernel.py, improver/nbhood/nbhood.py, improver/nbhood/recursive_filter.py, improver/nbhood/square_kernel.py, improver/nbhood/use_nbhood.py, improver_tests/nbhood/circular_kernel/test_CircularNeighbourhood.py, improver_tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py, improver_tests/nbhood/nbhood/test_BaseNeighbourhoodProcessing.py, improver_tests/nbhood/nbhood/test_GeneratePercentilesFromANeighbourhood.py, improver_tests/nbhood/nbhood/test_NeighbourhoodProcessing.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py, improver_tests/nbhood/square_kernel/test_SquareNeighbourhood.py, improver_tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py
Part of https://github.com/metoppv/mo-blue-team/issues/157
Removes repr methods and associated tests from all neighbourhood related plugins
Testing:
=> Remove __repr__ methods from all neighbourhood plugins

improver/calibration/dataframe_utilities.py
Addresses https://github.com/metoppv/mo-blue-team/issues/207
Description
This PR makes a minor correction to a docstring listing the input columns for the truth dataframe.
Testing:
=> Minor correction of docstring listing truth dataframe columns

doc/source/extended_documentation/calibration/ensemble_calibration/ensemble_calibration.rst, improver/calibration/ensemble_calibration.py, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver_tests/calibration/ensemble_calibration/test_CalibratedForecastDistributionParameters.py, improver_tests/ensemble_copula_coupling/test_ConvertLocationAndScaleParametersToPercentiles.py, improver_tests/ensemble_copula_coupling/test_ConvertLocationAndScaleParametersToProbabilities.py
Addresses https://github.com/metoppv/mo-blue-team/issues/204
Description
Modifications to code, documentation and tests, particularly to improve and clarify the usage of the scale parameter. Primarily this involves moving the square rooting of the scale parameter from the ECC code and into the apply EMOS code (specifically the `CalibratedForecastDistributionParameters` class). This is partly to consolidate the squaring and square rooting operations for ease of understanding and maintenance. 
Testing:
=> Consolidate scale parameter usage across EMOS and ECC

improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py
[Pandas 1.4](https://pandas.pydata.org/docs/dev/whatsnew/v1.4.0.html) contains more strict checking of `DataFrame.at` usage, which results in a unit test failing - see [example test failure on my personal fork](https://github.com/tjtg/improver/runs/4948060509?check_suite_focus=true). This will likely affect other forks whenever the cached conda environments get refreshed.
`.at` is intended as a faster alternative to `.loc`, but it only works on scalar indices, not more advanced usage such the slicing used in this test case.
This change was in #1651, but I've split it out as a separate PR as the test failure is now also happening on the conda-forge environment.
Testing:
=> Unit test fix for Pandas 1.4

improver/calibration/dataframe_utilities.py, improver/calibration/ensemble_calibration.py, improver/synthetic_data/set_up_test_cubes.py
Addresses https://github.com/metoppv/mo-blue-team/issues/209
Description
Warnings removed:
- Remove deprecation warning from improver/synthetic_data/set_up_test_cubes.py: ```DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.```
- Remove `SettingWithCopyWarning` in improver/calibration/dataframe_utilities.py: ```SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame```
- Remove deprecation warning from improver/calibration/ensemble_calibration.py : ```DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use …
```
=> Remove raising of unnecessary warnings from calibration code

doc/source/extended_documentation/calibration/reliability_calibration/reliability_calibration_examples.rst, improver/calibration/reliability_calibration.py
Following from https://github.com/metoppv/improver/pull/1170, removes remaining mentions of cycle/cycle_hour in reliability calibration.
ping @bayliffe who created the original PR.
Testing:
- [n/a] Ran tests and they passed OK
=> DOC Remove mention of cycle_hour from reliability calibration

doc/source/conf.py
Fix numpy and scipy intersphinx links as docs currently failing (see #1667) with error:
> intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
Note ongoing hosting issue for scipy hosting: https://github.com/scipy/scipy/issues/14267
I linked to scipy 1.6.2 as this is what we test with in CI but can switch this to 1.8.0 (`https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/`)
Testing:
=> DOC Fix intersphinx links for docs

doc/source/conf.py
Following on from #1668, there are some more links that have changed and need updating to ensure that the documentation builds successfully. There are for:
- cf_units
- python 3
Testing:
=> Update doc-build intersphinx links

.readthedocs.yml
Closes https://github.com/metoppv/mo-blue-team/issues/234
This PR reduces the memory requirements for building read-the-docs pages by:
- replacing conda with mamba for the environment building step.
- removing the `htmlzip` build process, which seems unlikely to be getting much use.
These are the steps recommended in the read-the-docs documentation.
Testing:
=> Reduce the memory requirements for read-the-docs

CONTRIBUTING.md, doc/source/about.rst
Addresses https://github.com/metoppv/mo-blue-team/issues/237
Description Corrects the Example of a CLI on the Read the docs page to be a working CLI. Also updates the text below to reflect these changes.  
Testing:
CLA
=> Corrects example of a CLI in the Read the Doc documentation

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/conftest.py, improver_tests/calibration/reliability_calibration/test_AggregateReliabilityCalibrationTables.py, improver_tests/calibration/reliability_calibration/test_ConstructReliabilityCalibrationTables.py, improver_tests/calibration/utilities/conftest.py, improver_tests/calibration/utilities/test_utilities.py
Closes #1658
* `ConstructReliabilityCalibrationTables` accepts site cubes as well as grid cubes
* Current tests pass
* Add tests for site functionality
Testing:
=> Enable site cube input to ConstructReliabilityCalibrationTables

improver/utilities/cube_manipulation.py, improver_tests/utilities/cube_manipulation/test_filter_realizations.py
Addresses https://github.com/metoppv/mo-blue-team/issues/127
Testing the use of the `--minimum-realizations` option with MOGREPS-G data showed that we have implemented the wrong merge-cubes method in `filter_realizations`. This PR changes it to use IMPROVER's `MergeCubes` plugin which silently removes attributes such as history on merging.
Testing:
=> MOBT127 tiny tweak to filter_realizations

doc/Makefile
Confirmed that removal of the sphinx apidoc exclusions have no effect, given the target dir.
Closes https://github.com/metoppv/improver/issues/1676
=> DOC: Removal of unnecessary exclusions in sphinx apidoc build

improver/blending/utilities.py, improver/utilities/cube_checker.py, improver_tests/blending/test_utilities.py, improver_tests/utilities/test_cube_checker.py
Removes flawed interpretation of the blend_time coordinate as evidence of model blending having occurred. See https://github.com/metoppv/mo-blue-team/issues/246 for a long description of what's going on here.
Testing:
=> MOBT-246: Remove flawed interpretation of the blend_time coordinate

improver/lapse_rate.py, improver/lightning.py, improver/precipitation_type/freezing_rain.py, improver/precipitation_type/snow_fraction.py, improver/psychrometric_calculations/precip_phase_probability.py, improver/regrid/landsea.py, improver/threshold.py, improver/utilities/cube_checker.py, improver/utilities/probability_manipulation.py, improver/utilities/spatial.py, improver/utilities/temporal.py, improver_tests/precipitation_type/freezing_rain/conftest.py, improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py, improver_tests/utilities/test_cube_checker.py, improver_tests/utilities/test_probability_manipulation.py
Addresses #1660 
This is the first PR of two. It does the following, which can be reviewed by selecting each commit in turn:
1. Creates a utility to invert probabilities, updating the relevant metadata on the output cube.
2. Adds a plugin to calculate the freezing rain probability by the agreed method.
3. Adds unit tests for the freezing rain plugin.
The probability inversion plugin was not necessary, but seemed like a useful generic utility to have available. Factoring out the `_comparison_operator_dict` from `BasicThreshold` was necessary as the freezing rain plugin needs to check whether the temperature data has been thresholded above or below the threshold values. The `spp__relative_to_threshold` attributes should be defined in only one place, such that changing these attributes is …
=> Adds a freezing rain plugin

improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/conftest.py, improver_tests/calibration/reliability_calibration/test_ManipulateReliabilityTable.py
Addresses #1669
Adds `point_by_point` to `ManipulateReliabilityTable`. This is similar to what has been done in EMOS #1170
Considerations:
* independent processing is done via for loop, looping over x, y slices. This is similar to what has been done in EMOS but it is slow - not sure if there is a better way to do this with iris (@anja-bom says there is not)
* the min forecast count processing results in variable sized probability bin coord, this means that reliability tables independently processed cannot be merged. Currently this is handled by using a CubeList. With this functionality the output is a CubeList of CubeLists, when both thresholds and points are independently processed. This is not a nice/clean data structure but I could not think of a better solution. Happy to change to …
=> ENH Add independent point processing to `ManipulateReliabilityTable`

improver/cli/nbhood.py, improver/cli/nbhood_iterate_with_mask.py, improver/cli/nbhood_land_and_sea.py, improver_tests/acceptance/test_nbhood.py, improver_tests/acceptance/test_nbhood_iterate_with_mask.py, improver_tests/acceptance/test_nbhood_land_and_sea.py
Partially addresses https://github.com/metoppv/mo-blue-team/issues/157
Add square as the default neighbourhood shape to all neighbourhood CLIs. Also made sure at least one test for each CLI used the default value rather than passing it in explicitly
Testing:
=> Added square as the default neighbourhood shape to neighbourhood CLIS.

.github/workflows/scheduled.yml
Github actions cache [expires after no usage in 7 days](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).
As the latest environment tests action is scheduled to run daily, the conda environment in cache never expires, so it would never update with newly available package versions from conda. 
This commit removes the cache which will increase time to run these tasks, but this only affects scheduled tasks rather than tasks triggered by pushes and pull requests. The time increases from ~4 minutes to ~7 minutes. 
Scheduled actions only run [on the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule). In this repository, that's the master branch, so I have run …
=> Remove cache from scheduled actions run using latest environment

improver/ensemble_copula_coupling/constants.py, improver/precipitation_type/freezing_rain.py, improver_tests/precipitation_type/freezing_rain/conftest.py, improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py
In order that percentiles of freezing rain accumulation can be generated, ECC bounds are required. This PR adds them.
Edit: In addition, this PR now tweaks the way in which the model configuration attribute is set to capture mixed model inputs.
Testing:
=> Add freezing rain precip bounds for ECC

improver/cli/threshold.py, improver/psychrometric_calculations/psychrometric_calculations.py, improver/regrid/landsea.py, improver/utilities/spatial.py, improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py, improver_tests/regrid/test_AdjustLandSeaPoints.py, improver_tests/utilities/test_OccurrenceWithinVicinity.py
Modifications to allow OccurrenceWithinVicinity to work using a grid point radius (N grid points) rather than a distance in metres.
This change allows the vicinity plugin to be called directly with a grid point radius. Doing so avoids the need to calculate such a radius within the code, and thus removes the enforcement that the projection be equal areas. This allows us to use a vicinity neighourbourhood in the phase change level code for a global lat-lon grid. Doc-strings have been updated to indicate that the user must tread carefully here as a grid point radius applied to some projections will lead to a very strange effective kernel shape.
Testing:
=> MOBT-273: OccurrenceWithinVicinity invoked using a grid point radius.

.github/workflows/ci.yml, .github/workflows/scheduled.yml, envs/environment_a.yml, envs/environment_b.yml
Applying the same change as @BelligerG made in https://github.com/MetOffice/improver_suite/pull/1282 to this repo.
That is to remove the json files under cache.
Additionally pinned 'click' to avoid issue with the version of black we are pinning, as per https://github.com/MetOffice/paraflow/pull/42
There is now a [recent version of black](https://github.com/psf/black/issues/2964) (>=22.3.0) which fixes/avoids the issue.  I tried updating black but this resulted in a number of formatting issues found by this more recent version of black.  Fixing these would be out of scope of this PR (updating black can be discussed in a separate issue).
- Removal of cache as per https://github.com/mamba-org/mamba/issues/488
- Pinning of 'click' (dependency of black) due to a failure of black (with the …
=> github actions mamba error workaround

.github/workflows/scheduled.yml
Originally raised in https://github.com/metoppv/improver/pull/1702#issuecomment-1109210445
This PR simply references the PR that removed the cache usage from scheduled actions (so that this context remains with the file).
=> DOC: No cache context

CONTRIBUTING.md, improver/cli/__init__.py, improver/cli/generate_clearsky_solar_radiation.py, improver/cli/generate_solar_time.py, improver/generate_ancillaries/generate_derived_solar_fields.py, improver_tests/cli/test_init.py, improver_tests/generate_ancillaries/test_GenerateClearskySolarRadiation.py
This PR adds a skeleton for CLIs and plugins for generation of derived solar fields that are required as inputs for RainForests calibration of precipitation accumulations.
Future PRs following on from this will add in functionality and tests, however the CLI interfaces should remain unchanged from those presented herein.
Testing:
CLA
=> Add skeleton for generation of derived solar fields for RainForests

improver/precipitation_type/freezing_rain.py, improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py
The freezing rain diagnostic produced by the nowcast is constructed using advection precipitation accumulations, but the temperature diagnostic comes from the UKV model. Prior to this change the model_configuration attribute was recording both as sources of data. However it has been decided that the resulting diagnostic is a nowcast product and should be recorded as such.
This change removes an issue that was manifesting in blending as a result of the original change; the model "ncuk uk_det" is not a single model and no single weight could be ascertained to use when model blending it with other models.
Testing:
=> MOBT-271: Freezing rain calculation to record a single model configuration

improver/cli/feels_like_temp.py, improver/feels_like_temperature.py
During the course of documenting the feels like temperature plugin, it was noted that the pressure input was misrepresented as MSLP instead of surface pressure. This and a reference to an outdated class location has now been amended in this PR.
Testing:
CLA
=> Amendments to outdated doc strings

improver/generate_ancillaries/generate_derived_solar_fields.py, improver_tests/generate_ancillaries/test_GenerateClearskySolarRadiation.py
This PR builds on #1705, and adds in functionality to construct the solar radiation cube based on the inputs provided. Calculations of clearsky irradiance will be added in a follow-up PR, so the emphasis here is on the cube properties and adding in the steps to extract solar radiation from irradiance values.
Testing:
=> RainForests clearsky solar radiation cube functionality

improver/cli/__init__.py, improver/cli/map_to_timezones.py
- Adds a UI accesible from paraflow (`command_executor`).
- @TomekTrzeciak's `tee` argument which enables saving to disk AND passing through the output (not used for Python execution right now but def. will come in handy).  Argument now `pass_through_output`.
- New `TimeIt` class for printing execution elapsed time when running with verbose.
A variation of the implementation represented in https://github.com/MetOffice/improver_suite/pull/1203
https://github.com/MetOffice/improver_suite/issues/1141
Dependency of https://github.com/MetOffice/improver_suite/pull/1218
=> changes aiding makefile migration to python execution

doc/source/conf.py
Tests run against latest package versions [failed](https://github.com/metoppv/improver/runs/6648768416?check_suite_focus=true#step:5:10) due to newly released [Sphinx 5.0.0](https://www.sphinx-doc.org/en/master/changes.html#release-5-0-0-released-may-30-2022) requiring the configuration file set [language](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language). The existing `None` value now results in a warning.
Testing:
=> Sphinx 5.0 requires setting language

.github/workflows/ci.yml
Currently the codecov report is generated on `environment_a.yml` only. Any tests that are run only on `environment_b.yml` will be skipped in the coverage report and get reported as not being covered by associated unit tests; this brings down the project coverage, despite the relevant code being covered by unit tests.
Codecov allows for automatic merging or reports, so by running tests with coverage on both `environment_a.yml` and `environment_b.yml`, a better coverage report can be generated by uploading both reports to codecov. This PR updates `ci.yml` to allow running of pytest on both environment a and b, with both reports uploaded to codecov.
Testing:
=> Update workflow to run coverage on both a and b envs.

envs/conda-forge.yml, envs/environment_a.yml, envs/environment_b.yml, envs/latest.yml, improver_tests/conftest.py
The current approach of setting environment variables inside pytest is not effective, as these libraries check the environment variables once at startup rather than as the process runs - setting inside pytest is too late. This is now mentioned in the [dask docs](https://docs.dask.org/en/stable/array-best-practices.html#avoid-oversubscribing-threads): "You need to run this before you start your Python process for it to take effect"
The [threadpoolctl library](https://github.com/joblib/threadpoolctl) is about 20kb on [conda-forge](https://anaconda.org/conda-forge/threadpoolctl/files) and has no required dependencies - it works with a variety of maths and thread libraries such as Intel MKL, OpenBLAS and OpenMP depending on what is in use on the system.
This PR adds the library as a …
=> Replace environment variable threads setting with threadpoolctl library

envs/conda-forge.yml, improver/psychrometric_calculations/psychrometric_calculations.py, improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
We sometimes get NaNs passing through in falling level interpolation, even when horizontal interpolation is used.
This adds a fix to just interpolate without anything fancy when we get NaNs falling through the rest of the interpolation. It may just be for discussion and comment rather than going in as-is, but I think the work is useful either way.
As the method was getting a little long I split it out, but the actual substantive change is the block with the comment saying 'This should be rare'.
I've added unit tests that cover the behaviour, all of which except the peaked grid radius 2 case pass through NaNs and fail when the code change is commented out.
Testing:
=> Fix snow falling level nan/masked issue

improver_tests/test_source_code.py
This change excludes hidden directories and their sub-directories from the init check test. This accommodates IDEs that store information in hidden directories, i.e. vscode, without attempting to maintain an explicit list of directories to be excluded.
Testing:
=> Modify __init__ presence test

improver/expected_value.py, improver_tests/acceptance/test_expected_value.py, improver_tests/expected_value/test_expected_value.py
As a follow up to #1719, implement processing of threshold data by numerical integration over probability thresholds, removing the quick-to-implement but poor performance implementation using ConvertProbabilitiesToPercentiles.
The acceptance test data is unchanged for this PR.
The time to run the acceptance test on threshold data reduced from ~1.5 seconds down to ~0.2 seconds on my workstation. There are significant performance improvements on larger data sets, such as whole-country sized grids.
Testing:
=> Implement expected value via integration over probability thresholds

improver/ensemble_copula_coupling/constants.py
Humidity data is often expressed as dew point temperatures within BOM and we would like to process this quantity within IMPROVER, rather than processing as specific humidity and converting later.
Lack of the parameter name in the bounds dictionary blocks the parameter from being processed (eg. exception raised in [get_bounds_of_distribution](https://github.com/metoppv/improver/blob/571412fae65ebcb6234c861fb76449f404332fae/improver/ensemble_copula_coupling/utilities.py#L190)).
Lower and upper bounds here added here are the same as the existing air_temperature, feels_like_temperature and temperature_at_screen_level bounds.
Testing:
=> Add dew point temperature to ECC bounds

improver/ensemble_copula_coupling/constants.py
ECC bounds are missing for medium and high type cloud which BOM would like to process. This leads to the same error as discussed in #1756. I have chosen the lower and upper bounds to be the same as the existing low and total cloud bounds, i.e. zero to unity (as expected for a cloud fraction).
Testing:
=> Add medium and high type cloud to ECC bounds

improver/lightning.py, improver_tests/acceptance/SHA256SUMS, improver_tests/lightning/test_LightningFromCapePrecip.py
The lightning filter plugin does not inherently create a vicinity diagnostic, this is only applicable when using coarse resolution data. As such this change removes the in_vicinity name component from the plugin output; this should be set specifically for coarse data if so desired using another approach (i.e. renaming in the suite).
Testing:
=> Remove in_vicinity name component from lighting plugin

.github/workflows/stale.yml
Modified version of the configuration for `actions/stale` from `SciTools/iris`
More info on the action here: https://github.com/actions/stale
To be discussed:
- Choosing a suitable number of days before the action will assign the "Stale" label to a issue/PR (60 days right now).
- Choosing a suitable number of days **after** issue/PR being marked as stale before issue/PR is actually closed (30 days right now).
- Any further label exclusions?
Hopefully will work (permissions on improver repo. setup to allow).
=> github actions for marking issues and PRs as stale

improver/regrid/grid.py, improver_tests/regrid/test_grid.py
The regridding code calls `create_regrid_cube` which generates a new cube with regridded data. The way in which it does this results in an "unknown" variable name if the input cube does not have a standard name. The tests added here fail if used with the original code. This PR fixes that bug.
I discovered the issue while testing CAPE processing in improver_suite_bom. The CAPE data from our ingest (stage_suite_bom) does not have a standard name, rather a long name. The regridding code fails to name the variable in the regridded cube correctly leading to "unknown" as the variable name.
Testing:
=> Fix cube name in regridding

improver/expected_value.py, improver_tests/expected_value/test_expected_value.py
Values outside bounds were found in expected values for diagnostics bounded below (eg. precipitation >= 0 millimetres) and double bounded (eg. cloud cover >= 0% and <= 100%).
These out of bounds values were caused by the addition of extra thresholds to ensure the distribution covers the complete probability range from when converting from CDF to PDF representation. The method in #1734 uses a combination of mean threshold spacing and ECC bounds, which intended to neatly handle the situation where a continuous diagnostic (eg. air temperature) isn't sufficiently represented by a wide enough range of thresholds.
This PR changes the extra thresholds to be tightly constrained by the existing thresholds - a small value near zero and the minimum floating point increment for larger values. This …
=> Fix out of bounds expected values for bounded diagnostics

improver/calibration/rainforest_calibration.py, improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationLightGBM.py
An error was encountered using `apply_rainforests_calibration` on deterministic models. The source of the error was that the realization dimension was dropped when converting `error_probability_cube` into `error_percentiles_cube` using `ConvertProbabilitiesToPercentiles`. This PR adds a small fix to ensure the realization dim coord is restored after being demoted in the convserion.
Tests are also added to test this case and use of the process function using deterministic inputs.
Testing:
=> Rainforests: fix for deterministic usage

improver/metadata/utilities.py, improver_tests/metadata/test_utilities.py
Addresses #1770 
Adds a metadata utility method that checks that for all input cubes, the specified model ID attribute is present and has one unique value.
Testing:
=> Adds method to check and extract the model id attribute value from a list of input cubes

improver/calibration/rainforest_calibration.py, improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationLightGBM.py, improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationTreelite.py
A mixup in #1771 resulted in paths being passed to LightGBM as strings and to Treelite as pathlib Paths. However, ~~Treelite is the library~~ both libraries require string paths.
This PR fixes that issue and adds assertions to existing unit tests in order to make sure that this remains correct in the future.
Testing:
=> Fix treelite requirement for string paths

LICENSE
Addresses #1776
- Github uses licensee to identify licensee to identify which license is used indicate on the right hand panel for the repo.
- Updated our license as per https://choosealicense.com/licenses/bsd-3-clause/ so that it can be correctly identified.
- From experimentation, the substitute copyright symbol `(c)` is used to identify the copyright line (to exclude it) and so allow an exact match on the license.
I ran licensee locally on my own machine using this updated license file and got a 100% match.
N/A
=> Licensee match

improver/cli/freezing_rain.py, improver/precipitation_type/freezing_rain.py, improver_tests/acceptance/SHA256SUMS, improver_tests/precipitation_type/freezing_rain/conftest.py, improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py
Modifies calculation of freezing-rain such that realization collapse occurs within the plugin.
The realization collapse is now performed (assuming an equal weight for each realization) by summing the freezing rain probability from each realization slice weighted by 1/n_realizations. This removes the need to hold all of the realizations in memory at the same time to perform the averaging calculation. It also removes the need for a realization_collapse step in the suite.
Memory usage is reduced by a factor of ~8 and the need for a separate realization collapse step is removed.
Testing:
=> MOBT-272: Reduce memory usages in freezing-rain calculation

improver/blending/utilities.py, improver/blending/weighted_blend.py, improver_tests/blending/test_utilities.py, improver_tests/blending/weighted_blend/test_MergeCubesForWeightedBlending.py, improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
The weighted blending plugins at the moment presume a `forecast_period` coordinate exists, even when it is not being used for blending. This presumption is not necessary, it largely relates to appending comments (stating that `forecast_period` is deprecated!) and recalculating the value of the forecast period. This change ensures that if the `forecast_period` is not present on the input, and is not being used in the blending, it is not required.
The motivation for this change is the blending of local-timezone products on the UK domain for which there is no `forecast_period` as it has no meaning for the data contained within the cube which is an amalgam of data from different forecast periods.
Testing:
=> MOBT-345: Remove expectation of forecast_period coordinate when blending

.github/workflows/ci.yml, improver_tests/synthetic_data/test_set_up_test_cubes.py
Fix long lines causing warnings in flake8 version 5.
Flake8 version 5.0.0 was released a few weeks ago and includes changes which check line length inside triple-quoted strings (usually docstrings). See "Fix physical line plugins not receiving all lines in the case of triple-quoted strings" in the [release notes](https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html).
This didn't cause any errors on metoppv/improver due to the actions cache, but I encountered it on my personal fork - see [logs of failing job](https://github.com/tjtg/improver/actions/runs/3081134398/jobs/4979327949#step:8:7).
Testing:
=> Fix flake8 long lines E501 error

improver/utilities/flatten.py, improver_tests/utilities/test_flatten.py
Related to https://github.com/metoppv/mo-blue-team/issues/354
Description
This PR adds a function with tests for flattening an arbitrarily nested list. This is intended to help when the argument to a CLI is provided as a list, which is a mixture of individual cubes and cubelists, such as in #1792. The `flatten` function in this PR would help with flattening this nested list.
Testing:
=> Add function and test for flattening an arbitrarily nested iterable

improver/ensemble_copula_coupling/constants.py
This PR is associated with [MOBT-350](https://github.com/metoppv/mo-blue-team/issues/350) which increases the thresholds in temperature, precipitation rate and visibility diagnostics.
One aspect of MOBT-350 is increasing the precipitation rate threshold upper bound from 128mm to 400mm in order to better capture global precipitation rate events. This PR increases the ECC bounds in line with the these changes.   
The related suite PR testing this change is found here: [Suite-1404](https://github.com/MetOffice/improver_suite/pull/1404)
Testing:
=> MOBT-350: Increasing ECC upper bound for precipitation rate in line with thresholds

improver/cli/nbhood.py, improver/nbhood/nbhood.py
Updates nbhood docstrings to specify the different inputs expected for probability and percentile processing.
Addresses #1813
Clarifies the intended input data for probability nbhood and percentile nbhood.
Doc-strings only - no testing needed.
=> Updates nbhood docstrings

improver/calibration/__init__.py, improver/cli/apply_emos_coefficients.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/acceptance.py, improver_tests/acceptance/test_apply_emos_coefficients.py, improver_tests/calibration/test_init.py
Addresses https://github.com/metoppv/mo-blue-team/issues/376, https://github.com/metoppv/mo-blue-team/issues/380
Description
This PR adds the capability to filter by validity time when applying EMOS. This helps ensure that forecasts will only be calibrated, if they match the desired validity times. This PR also adds a comment to the file to indicate that EMOS has not been applied successfully, either because the validity time of the forecast does not match the desired list of validity times, or because no coefficients have been supplied. This is aimed at helping to make it clear within the output files whether calibration has been applied or not.
Testing:
=> Filter validity times when apply EMOS and update metadata

improver/cli/apply_emos_coefficients.py, improver_tests/acceptance/test_apply_emos_coefficients.py
Related to: https://github.com/metoppv/improver/pull/1820
Description
This PR ensures that a consistent set of percentiles are able to be returned when EMOS is not applied successfully due to the application of validity time filtering (#1820).
Testing:
=> Ensure consistent percentiles from EMOS

.github/workflows/ci.yml, .mailmap, CONTRIBUTING.md, improver/ensemble_copula_coupling/ensemble_copula_coupling.py, improver_tests/ensemble_copula_coupling/test_EnsembleReordering.py, improver_tests/ensemble_copula_coupling/test_RebadgePercentilesAsRealizations.py
Addresses #1724 
Description
Percentiles should be evenly spaced, centered on 50, and evenly partition percentile space. Added unit tests for new features. Changed some existing unit tests to adhere to new requirements when rebadging percentiles as realizations.
Testing:
CLA
=> Add additional checks when rebadging percentiles as realizations

improver/ensemble_copula_coupling/constants.py
Related to [MOBT-398](https://github.com/metoppv/mo-blue-team/issues/398) 
Suite ticket: [Suite-496](https://github.com/MetOffice/improver_suite/pull/1496)
Description:
This PR is a sister to this suite PR: 
It adds lwe_thickness_of_graupel_and_hail_fall_amount to the list of ECC constants so that percentile send tasks can added to the hailacc1/3h chains.
=> Add hail accumulation to list of ECC constants.

improver/blending/utilities.py, improver_tests/blending/test_utilities.py
Add explicit error handling for instances where old record_run attributes are encountered by the new code. These lack weights and this needs to be flagged to the user to make the failure easy to understand.
This is being seen in the recently stood up operational mix suite into which is being fed data from model suites that are using an older version of IMPROVER.
Testing:
=> MOBT-417: Error handling for old record_run attributes

improver/cli/apply_emos_coefficients.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_apply_emos_coefficients.py
Addresses https://github.com/metoppv/mo-blue-team/issues/416
Description
If no coefficients are provided to the apply EMOS CLI and a probability template is provided, the probability template is returned as the uncalibrated forecast. This probability template is, however, not currently updated with a comment to indicate that this is not calibrated. This PR ensures that the probability template cube is updated with a comment.
Testing:
=> Ensure comment present if EMOS calibration is not applied

improver/standardise.py, improver_tests/standardise/test_StandardiseMetadata.py
Removal of "above_surface_pressure below_surface_pressure" coord by re-introducing the original NaN values.  This is done within the standardise plugin.
Closes https://github.com/MetOffice/improver_suite/issues/1523
`impr_engl_temp_plev_standardise` task is now failing in fpostest (release) with out of memory (OO Killer).  This is due to a change in how the data is now represented via stage.
Below that of the surface altitude we used to set to NaNs in the data.  Now a flag (kind of a mask) is used instead to indicate which values are above/below the surface level pressure.
```
byte flag(realization, pressure, latitude, longitude) ;
flag:standard_name = "air_temperature status_flag" ;
flag:flag_meanings = "above_surface_pressure below_surface_pressure" ;
flag:flag_values = 0b, 1b ;
```
The …
=> Last minute "above_surface_pressure below_surface_pressure" coord removal

README.md
Remove reference to Better Code Hub since it is being retired https://bettercodehub.com/
Closes #1811
Description
Removes the Better Code Hub reference from the ReadMe file. This removes the Better Code Hub badge from the IMPROVER codebase. Better Code Hub is being retired, so we should remove the badge from the codebase. 
Testing:
CLA
=> Remove reference to Better Code Hub from the IMPROVER README.md file

doc/rtd_environment.yml
Sphinx must be pinned to enable the docs to built using python 3.7 following changes in sphinx release 6.
https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022
This PR pins the version in the read-the-docs environment.
Successful read-the-docs build with this change: https://readthedocs.org/projects/bens-improver-fork/builds/19074227/
Testing:
=> Pin sphinx to version 5.3.0

.github/workflows/ci.yml, .github/workflows/scheduled.yml, envs/conda-forge.yml
Recent actions using the latest environment have been failing - see [recent example of the scheduled run](https://github.com/metoppv/improver/actions/runs/3927180994/jobs/6713568771).
The CI job actions aren't currently failing on metoppv, but this is because they're [using existing caches](https://github.com/metoppv/improver/actions/runs/3912012569/jobs/6686099418#step:3:14). These CI jobs will also start to fail if the caches become stale and get regenerated. As an example, this happened on my [personal fork](https://github.com/tjtg/improver/actions/runs/3927383494/jobs/6713958567).
This failure seems to be due to the conda version packaged in the current version of the runner VM images from Github Actions not working with mamba. See actions/runner-images#6910 for details.
The proposed …
=> Change conda dependency solver to libmamba-solver

.github/dependabot.yml, .github/workflows/stale.yml
Stale action failure due to commit SHA no longer existing.
Switch to using tags.  At the same time, use dependabot to automatically open new PRs for updating the tag of action tags (as per `improver_suite`, see https://github.com/MetOffice/improver_suite/pull/1503).
[link to failed action download](https://github.com/metoppv/improver/actions/runs/3954527266)
I'll [enable dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-version-updates-on-forks) on merge of this PR.
=> Fix stale PR action checkout failure

improver/psychrometric_calculations/hail_size.py, improver/utilities/cube_extraction.py, improver_tests/psychrometric_calculations/hail_size/test_hail_size.py, improver_tests/utilities/cube_extraction/test_ExtractPressureLevel.py
Closes #1832
An investigation into the behaviour of the hail size plugin found that it wasn't generating a 268K isotherm pressure correctly. This is within the `ExtractPressureLevel` plugin and additional unit tests showed that the presence of `np.nan` values, where the source variable-on-pressure-levels fell below the NWP model surface, was causing the issue. The existing `fill_invalid` method was working, but if more than one level were missing, both received the same infill value which caused the `stratify.interpolate` method to fail (I didn't dig deeply, but I think it couldn't determine the direction of change in the column)
While playing with unit tests, it became apparent that the code was not robust to data ordered differently. It is reasonable to define a pressure coordinate that …
=> Fix hail size

doc/source/index.rst, doc/source/metadata/Principles.rst
Description
An initial draft of the Principles metadata document (a re-working of information currently hosted on an internal Met Office site). This creates a Principles.rst file.
=> Updated metadata documentation part 2 - principles

.github/workflows/scheduled.yml
To hopefully address the failing [scheduled actions](https://github.com/metoppv/improver/actions/workflows/scheduled.yml).
Recently we switched (https://github.com/metoppv/improver/pull/1850) to using the libmamba solver as per [docs](https://conda.github.io/conda-libmamba-solver/getting-started/#set-as-default).
For some reason, the conda env update is sometimes taking 2m while at other times tasking an hour.  More recently, taking more consistently taking long enough to timeout.
This proposed change is to understand whether the solver is actually being changed via the documented means and also whether specifying the solver for the update makes the difference.
At some point it might be preferable to move back to mamba the tool as that provides parallel resolution (as I recall anyway - …
=> Debug scheduled action

.github/workflows/scheduled.yml
Looks like the [switch](https://github.com/metoppv/improver/pull/1850) to conda-libmamba brought with it a new set of problems.  The environment resolving within minutes at times, while at other times, timing out after over an hour. Let's see whether conda provided with the ubuntu image works with the mamba tool once more and what difference that makes on resolving the environment.
Note how the change to libmamba solver ran fine for 1 day then produced inconsistent results thereafter (sometimes failing and sometimes succeeding).
Previous attempt to fixing/debugging the issue:
https://github.com/metoppv/improver/pull/1888
=> DEBUG: Using mamba tool once more

improver/cli/blend_with_vicinity_and_rename.py, improver/cube_combiner.py, improver/ensemble_copula_coupling/constants.py, improver/metadata/amend.py, improver/metadata/probabilistic.py, improver/utilities/spatial.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_blend_with_vicinity_and_rename.py, improver_tests/metadata/test_amend.py, improver_tests/utilities/test_spatial.py
Part of https://github.com/MetOffice/improver_suite/issues/1610
To achieve the meta-data changes requested here (https://github.com/MetOffice/improver_suite/pull/1611#discussion_r1165375538), I have created a new CLI to call `weighted-blending`, then modify the meta-data of the resulting cube before it is returned.
The metadata changes are:
- File name: `f"precipitation_accumulation_in_variable_vicinity-PT{period:02d}H"`
- Cube name: `probability_of_lwe_thickness_of_precipitation_amount_in_variable_vicinity_above_threshold`
- Cube coordinate: `radius_of_vicinity`, Value: 10000 m, With the addition of this comment attribute in the nowcast period only: `comment: "Maximum"`
Implementing this required these changes to allow me to reuse existing code:
- Refactors `update_diagnostic_name` and …
=> Add CLI to perform blending with mismatching vicinities and the option to rename the cube

improver/cli/clip.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_clip.py
Required for metoppv/mo-blue-team#516
Acceptance_test_PR: metoppv/improver_test_data#17
Adds in a CLI calling a pre-existing function in IMPROVER to clip data in a cube between an upper and lower bound. This is required to be able to clip cloud bases to 0m in the suite. This PR also includes some acceptance tests for the new CLI. 
Testing:
=> Add CLI for clipping cubes

improver/metadata/constants/time_types.py, improver/metadata/forecast_times.py, improver/synthetic_data/set_up_test_cubes.py, improver/wxcode/weather_symbols.py, improver_tests/metadata/test_forecast_times.py, improver_tests/synthetic_data/test_set_up_test_cubes.py, improver_tests/wxcode/wxcode/test_WeatherSymbols.py
Addresses https://github.com/metoppv/mo-blue-team/issues/521
The output cube from the weather code plugin will contain either a forecast_reference_time coord or a blend_time coord, but the value of this auxiliary coordinate will be taken from either the last supplied cube that has time bounds, or the first cube if none have time bounds. (This becomes `self.template_cube`).
In practise, the weather code plugin receives data from different models and the blended data have different update frequencies. This can mean that the reference time on the output cube can be several hours older than the newest reference time passed in. Given that we update the weather code when any of the input data changes, this is not appropriate.
This PR adds handling of the reference time and selects the newest …
=> Correct handling of reference time in weather_code plugin

improver/calibration/dz_rescaling.py, improver_tests/calibration/dz_rescaling/test_apply_dz_rescaling.py
This change addresses an issue in the dz adjustment of wind speeds. The leniency applied for finding a dz adjustment match in the ancillary did not span across midnight, meaning a 23Z forecast reference time was unable to use a 00Z forecast reference time with a leniency of +- 1 hour. This change simply adds a modulus about 24 hours to ensure the looping around to 00Z occurs as required.
The unit tests have been modified to span the midnight line to check that this works as expected.
Testing:
=> Fix to the wind vertical displacement adjustment implementation

README.md
The tests badge was showing as failed. This was pointing at an old automated test that has not been running for sometime. I deleted the old test run, and thus fully broke the tests badge. This PR replaces it with a badge pointing at the current scheduled tests of the master branch.
=> Recreate tests badge based on scheduled tests of master branch.

improver/psychrometric_calculations/psychrometric_calculations.py, improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
Addresses https://github.com/metoppv/mo-blue-team/issues/558
Notebook: https://github.com/MetOffice/improver_aux/pull/399
Description
Updates vertical interpolation of precipitation falling-levels for sea points to account for orography. 
Adds test for new functionality.
The notebook linked above demonstrates how the negative sleet probabilities arise and also shows that this change does actually fix the problem.
Testing:
=> Account for orography when vertically interpolating falling-levels at sea points

improver/calibration/dz_rescaling.py, improver/cli/estimate_dz_rescaling.py
Related to https://github.com/metoppv/mo-blue-team/issues/507
Description
Minor docstring edits to make it clearer that the output scaled dz will match, in terms of the sites, the neighbour cube provided. The forecasts and truths do not have to match the neighbour cube, although there is expected to be overlap between the sites present in the forecasts, truths and neighbour cube.
Testing:
=> Docstring clarification for the wind dz rescaling

improver/nbhood/nbhood.py, improver/nbhood/use_nbhood.py, improver_tests/nbhood/nbhood/test_NeighbourhoodProcessing.py, improver_tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py
Reduces size of data array handled in nbhood to exclude rows and columns of only zeros or only ones.
Replaces https://github.com/metoppv/improver/pull/1936
Addresses https://github.com/metoppv/mo-blue-team/issues/556
Topographic neighbourhooding is mostly processing masked data and lots of other nbhood calls contain complete arrays of zeros or ones. This PR takes advantage of this and crops those arrays so that areas of excluded data don't require huge amounts of compute time. Where no unmasked data exist, the calculations are bypassed entirely.
The result is that ALL neighbourhood processing benefits from this method when the non-extreme values (points that are not 1 or 0) are sparse or non-existent.
Testing:
- The linked ticket shows how this reduces the computation time of the most …
=> Neighbourhood efficiency improvements

improver/cli/recursive_filter.py, improver/nbhood/recursive_filter.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py
This PR removes the warning about using more than 3 iterations with the recursive filter. It also removes the associated brief discussion of conservation of probability as a concept that we should be particularly concerned with when using the recursive filter.
This change will enable more iterations of the recursive filter to be used without clogging the logs with superfluous warnings.
Testing:
=> IM-1933: Remove iteration warning from the recursive filter

improver/calibration/dataframe_utilities.py, improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py
Addresses https://github.com/metoppv/mo-blue-team/issues/570
Add function and unit tests to ensure that the altitude, latitude and longitude columns have the same, consistent value for a given site. This will ensure that site EMOS is robust to updates to the altitude, latitude and longitude that may occur if corrections are made to the position of the sites. 
Testing:
=> Enforce consistent altitude, latitude and longitude for site EMOS

improver/cli/wet_bulb_freezing_level.py
Currently the wet bulb freezing level cube is called "wet_bulb_freezing_level". However the hail size cli requires the name the be "wet_bulb_freezing_level_altitude" to extract it from a cubelist.
This PR updates the cube name so it can be used with the hail size plugin.
Updated acceptance test data:  https://github.com/metoppv/improver_test_data/pull/35
Testing:
=> Update wet bulb freezing level cube name

improver_tests/acceptance/SHA256SUMS
Following #1956
The above PR had an associated change to acceptance test data (https://github.com/metoppv/improver_test_data/pull/35), but the checksums were not updated, and the testing was insufficient (my fault! sorry).
This PR updates the checksum for the modified file.
Testing:
=> Updates checksums for WBFL KGO

improver/calibration/dz_rescaling.py, improver/cli/apply_dz_rescaling.py, improver_tests/calibration/dz_rescaling/test_apply_dz_rescaling.py
Loosen dz scaling application to use the longest forecast period scaling coefficient available if no scaling coefficient has a forecast period that is longer than the forecast itself.
This will enable us to e.g. use a T+7 day scaling coefficient when calibrating a T+8 days forecast.
It also means we have no warning that such use if going on. So for example, once we implement 14-day forecasts if we fail to update this ancillary with a greater range of forecast periods it will silently use the longest available.
Testing:
=> MOBT-572: Loosen dz-scaling usage restriction.

improver/calibration/dz_rescaling.py, improver/cli/apply_dz_rescaling.py, improver_tests/calibration/dz_rescaling/test_apply_dz_rescaling.py
Merges #1959 into the release branch 1.6.x.
Tests run against acceptance test data branch 1.6.x.
Testing:
=> Merge #1959 into 1.6.x branch

doc/source/about.rst
Addresses https://github.com/metoppv/mo-blue-team/issues/425
Description
Adds links to the IMPROVER BAMS paper and Zenodo archive to the 'Papers and publications' section of documentation. Also adds a sentence to this section suggesting that, when citing IMPROVER, authors should reference these 2 sources.
Testing:
=> Add links to IMPROVER BAMS paper and Zenodo archive to docs.

improver/cli/max_in_height.py, improver/utilities/cube_manipulation.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_max_in_height.py, improver_tests/utilities/cube_manipulation/test_maximum_in_height.py
Adds in the ability to update the name of a cube when calculating the maximum over a vertical coordinate. This is required for the EPP PR: https://github.com/MetOffice/epp_workflows/pull/17
Acceptance test data: https://github.com/metoppv/improver_test_data/pull/37
Testing:
=> Optionally set a new name in max_in_height

README.md
As per title
I have been providing guidance to people installing improver via conda.  Having it defined here makes sense to me so that I can point people to it.
Note the instructions are put together to reflect issues we encountered within actions previously (https://github.com/metoppv/improver/pull/1962).  Mainly, separating the environment containing mamba, with that containing improver.
=> DOC: Installation instructions via conda

improver/metadata/amend.py, improver/standardise.py, improver_tests/metadata/test_amend.py
Addresses https://metoffice.atlassian.net/browse/EPPT-650
Updates `amend_attributes` method, used by `standardise` CLI, to allow attributes to be modified in these ways:
- `"{}"` in the new value will be populated with the existing attribute value on the cube.
- `"{now:[date-format]}"` will be populated with the current wall-clock, formatted as specified.
This allows us to update the history attribute of a cube and to append the current date-time and a string describing the process that has been applied.
Testing:
=> amend_attributes can now add to an existing value, and add timestamps.

improver/cli/copy_attributes.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_copy_attributes.py
Adds CLI to copy attributes from one NetCDF file to another. Includes acceptance test.
Addresses https://github.com/MetOffice/epp_workflows/pull/24
For the EPP Precipitation Type workflow, we need a new CLI to copy attribute values from one cube to another so that the precipitation type output can contain StaGE attribute values inherited from a precipitation rate cube.
Acceptance test data can be found in https://github.com/metoppv/improver_test_data/pull/41
Testing:
=> Adds CLI to copy attributes from one NetCDF file to another.

.github/workflows/ci.yml, .github/workflows/scheduled.yml
=> Revert "Bump codecov/codecov-action from 3 to 4"

improver/precipitation_type/snow_splitter.py, improver_tests/acceptance/SHA256SUMS, improver_tests/precipitation_type/snow_splitter/test_snow_splitter.py
Addresses https://metoffice.atlassian.net/browse/EPPT-650
While testing the EPP Precipitation Type workflows, I have found that the output cube names for rain/snow rate/accum data are not the same as the same data found on StaGE. For accumulation data, the rain and snow outputs had the names of the precipitation cube. This PR modifies the new cube name generation, which is generated from a precipitation cube name, so that:
- "precipitation" is replaced with either "rainfall" or "snowfall" (not "rain" or "snow")
- "lwe_", which means liquid water equivalent, is removed if the output is rain.
Testing:
=> SnowSplitter output cube names are now the same as their StaGE couterparts

envs/latest.yml
Currently the scheduled tests are failing:
```
improver_tests/calibration/rainforests_calibration/conftest.py:299: ModuleNotFoundError
=========================== short test summary info ============================
ERROR improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationLightGBM.py::test__check_num_features[treelite] - ModuleNotFoundError: No module named 'treelite_runtime'
ERROR improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationLightGBM.py::test__empty_config_warning[treelite] - ModuleNotFoundError: No module named 'treelite_runtime'
ERROR improver_tests/calibration/rainforests_calibration/test_ApplyRainForestsCalibrationLightGBM.py::test__evaluate_probabilities[treelite] - ModuleNotFoundError: No module named …
```
=> Fix pinning to treelite rather than lightgbm.

improver/blending/utilities.py, improver/metadata/constants/time_types.py, improver/synthetic_data/set_up_test_cubes.py, improver/utilities/temporal.py, improver_tests/blending/test_utilities.py, improver_tests/blending/weights/test_ChooseWeightsLinear.py, improver_tests/calibration/dz_rescaling/test_apply_dz_rescaling.py, improver_tests/calibration/dz_rescaling/test_estimate_dz_rescaling.py, improver_tests/categorical/modal_code/test_ModalCategory.py, improver_tests/categorical/test_utilities.py, improver_tests/precipitation_type/hail_fraction/test_HailFraction.py, improver_tests/precipitation_type/snow_fraction/test_SnowFraction.py, improver_tests/regrid/test_AdjustLandSeaPoints.py, improver_tests/regrid/test_RegridWithLandSeaMask.py, improver_tests/synthetic_data/test_set_up_test_cubes.py, improver_tests/utilities/solar/test_DayNightMask.py, improver_tests/utilities/test_DifferenceBetweenAdjacentGridSquares.py, improver_tests/utilities/test_OccurrenceWithinVicinity.py, improver_tests/utilities/test_cube_checker.py, improver_tests/utilities/test_spatial.py
Addresses https://github.com/metoppv/mo-blue-team/issues/430
- Adds the following helper functions for use in creating unit tests that use spot-cubes:
- set_up_spot_variable_cube
- set_up_spot_percentile_cube
- set_up_spot_probability_cube
- Adds associated unit tests
- Modifies calls to the existing gridded functions where these did not use the keyword arguments explicitly.
- Modifies some unit tests as an example of how this can be used.
- Centralises the date-time format "%Y%m%dT%H%MZ" as we use this in several places and have never done so.
The commits are broken up as follows:
1. new functions, tests, fix-up existing calls, and (sorry) a partially modified choose weights test.
2. centralise the date-time format
3. modify some unit tests as examples of usage.
Testing:
=> MOBT-430: Synthetic data utilities for creating spot-cubes

improver/cli/generate_orographic_smoothing_coefficients.py
As an IMPROVER scientist, I like it when equations in doc-strings accurately represent the actual calculations being carried out, rather than bamboozling me.
This (~ancient~ surprisingly young) [PR](https://github.com/metoppv/improver/pull/1359) changed the `generate_orographic_smoothing_coefficients` method so that it no longer required a `coefficient` to be specified, but rather normalised the calculated smoothing coefficients between user specified min and max values. The plugin doc-strings were updated accordingly, but a vestigial reference to a `coefficient` in the CLI doc-string remains. This PR removes that reference.
=> Correct generate_ororgraphic_smoothing_coefficients doc-string

improver/calibration/reliability_calibration.py
Speed up ApplyReliabilityCalibration by replacing scipy interpolation with faster numpy version. Gives approximately 25% improvement with 7 reliability bins.
Testing:
=> Speed up ApplyReliabilityCalibration

improver/cli/integrate_time_bounds.py, improver/utilities/temporal.py, improver_tests/acceptance/SHA256SUMS, improver_tests/acceptance/test_integrate_time_bounds.py, improver_tests/utilities/temporal/test_temporal.py
This change adds a function and CLI to multiply average rates / frequencies within periods by the length of the period over which they are defined to yield an accumulation / count over the same period. This is to be used in the first instance for converting lightning flash frequencies into counts.
Acceptance test data: https://github.com/metoppv/improver_test_data/pull/49
Testing:
=> MOBT-719: Frequency to count for time period averages

envs/conda-forge.yml
Changes in environment resulting in failure in `CI Tests / Sphinx-Pytest-Coverage (conda-forge)`
Most recent working `CI Tests / Sphinx-Pytest-Coverage (conda-forge)` run:
package | version | CI
--- | --- | ---
pandas | 2.0.0 (py39h2ad29b5_0) | [link](https://github.com/metoppv/improver/actions/runs/9091630360/job/24986612615?pr=1997#step:5:153)
pillow | 10.0.1 (py39h444a776_1) | [link](https://github.com/metoppv/improver/actions/runs/9091630360/job/24986612615?pr=1997#step:5:156)
Most recent (broken) `CI Tests / Sphinx-Pytest-Coverage (conda-forge)` run:
package | version | CI
--- | --- | ---
pandas | 2.2.2 (py39hfc16268_1) | [link](https://github.com/metoppv/improver/actions/runs/9810862589/job/27091941214#step:5:156)
pillow | 10.4.0 (py39h16a7006_0) | …
=> BLD: Fix CI Tests / Sphinx-Pytest-Coverage (conda-forge) failing

envs/latest.yml
Scheduled sphinx build fails.  Same failure as the one I fixed from the other environment yml impacting CI for PRs previously.
This PR pulls over pinned packages introduced to the `conda-forge.yml` into the `latest.yml` file as I did in https://github.com/metoppv/improver/pull/2011
See [here](https://github.com/metoppv/improver/actions/runs/10138073967/job/28029201432#step:5:21)
```
...
Exception occurred:
File "/usr/share/miniconda/envs/imlatest/lib/python3.9/site-packages/PIL/_typing.py", line 10, in <module>
NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
The full traceback has been saved in /tmp/sphinx-err-y5_5n0y9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better …
```
=> BUG: Fix Scheduled Tests Sphinx-Pytest-Coverage

envs/conda-forge.yml
Related to https://github.com/metoppv/improver/pull/2023
Description
This copies the solution to #2010 from #2011 into the 1.6.x release branch to fix an issue with the Sphinx builds failing for the environment built using conda-forge.yml.
Testing:
=> Fix CI tests in 1.6.x release branch

improver/wxcode/modal_code.py, improver_tests/wxcode/wxcode/test_ModalFromGroupings.py
Adds missing brackets in calculation of start file and end file for middle of the day emphasis. This didn't matter for hourly inputs, which is what the unit tests focus upon. However, for 3-hourly data it is vital as otherwise the day length is not scaled by the interval to give a number of files from which to count back.
I've added a unit test to demonstrate that this is working as expected; data taken from case I found in the test suites that was wong.
Testing:
=> Bug fix: WX groupings PR miscalculating day length as number of files

improver_tests/wxcode/wxcode/test_ModalCode.py, improver_tests/wxcode/wxcode/test_ModalFromGroupings.py
Addresses https://github.com/metoppv/mo-blue-team/issues/766
Description
Simplify weather symbols day weighting unit tests, so that the weather codes do not need to be provided in a time-reversed order.
Testing:
=> Simplify weather symbols day weighting unit tests

improver/wxcode/modal_code.py, improver_tests/wxcode/wxcode/test_ModalFromGroupings.py
Related to https://github.com/metoppv/mo-blue-team/issues/742
Description
Edit to include the influence of day weighting when performing the intensity categorisation.
Testing:
=> Include influence of day weighting in the intensity categorisation

improver/api/__init__.py, improver/cli/standardise.py, improver/standardise.py, improver_tests/standardise/test_StandardiseMetadata.py
Some left over changes to IMPROVER api to support eppgl_precip_type configuration for EPP.
- `improver.utilities.cube_manipulation` missing from api list (needed for EPP).
- Updated `StandardiseMetadata` plugin so that arguments have been moved to the init to make in line with IMPROVER guidelines.
- https://github.com/MetOffice/epp_workflows/pull/68
- https://github.com/MetOffice/improver_suite/issues/2253
- https://github.com/MetOffice/epp_workflows/pull/55
=> Improver api changes

improver_tests/test_api.py
While reviewing @cpelley's changes for DAG-runner, I found that this API lookup didn't have a unit test to prove that all the targets actually point to a usable object. This could result in unexpected behaviour. I've added a simple test that passes if each item points to an object that is callable.
Testing:
=> Adds unit test for improver.api

improver/categorical/decision_tree.py, improver_tests/categorical/decision_tree/test_ApplyDecisionTree.py
Ticket: https://metoffice.atlassian.net/browse/EPPT-1683
This ticked is fixing a bug with the categorical plugin when using deterministic data and requiring multiple diagnostics/floats to be evaluated for a node. 
It also fixes the order of operation part of the code which previously always evaluated operators in the order divide,multiply, add,subtract. This isn't quite write as divide and multiply have the same precidence and should be evaluated from left to right. Ditto for add and subtract.
Testing:
=> Categorical fix for Deterministic data

improver/cli/copy_attributes.py, improver/utilities/copy_attributes.py, improver/utilities/cube_extraction.py, improver_tests/utilities/copy_attributes/test_CopyAttributes.py, improver_tests/utilities/cube_extraction/test_ExtractLevel.py
- Support EPP execution with dagrunner.
- Supporting IMPROVER execution with dagrunner.
1. Enforce python int type for powers.
```python
File "/path/to/cylc-run/epp_demo/lib/python3.9/site-packages/improver/utilities/cube_extraction.py", line 416, in fill_invalid    v_increment = sign * 10 ** (-cube.attributes.get("least_significant_digit", 2))
...
ValueError: Integers to negative integer powers are not allowed
```
2. `CopyAttributes` bad arguments passing (template cube).
- https://github.com/MetOffice/improver_suite/issues/2253
=> Fixes in support of configuration execution which call plugins directly (i.e. not via CLI)

improver/calibration/rainforest_calibration.py
Addresses #2046 
Rainforests config files contain a list of paths to the individual Treelite or LightGBM files.
This change adds parsing of these strings for environment variables using os.path.expandvars.
Testing:
=> Allow environment variables in Rainforests config

doc/source/Code-Style-Guide.rst, doc/source/Dependencies.rst, doc/source/Guidance-for-Reviewing-Code.rst, doc/source/How-to-implement-a-command-line-utility.rst, doc/source/Running-at-your-site.rst, doc/source/Ticket-Creation-and-Definition-of-Ready.rst, doc/source/about.rst
Addresses https://github.com/metoppv/mo-blue-team/issues/795
This PR updates the best practices sections on the Readthedocs site in line with our current ways of working.
To build the webpages locally attempt the following:
- Activate the conda environment 
- Navigate to the improver top directory and enter: bin/improver-tests doc
- Then: firefox doc/build/html/index.html
=> Updated Readthedocs documentation in line with current practices.

improver/utilities/spatial.py, improver_tests/acceptance/SHA256SUMS, improver_tests/utilities/spatial/test_GradientBetweenAdjacentGridSquares.py
EPP ticket: https://metoffice.atlassian.net/browse/EPPT-1826
Acceptance_test_data: https://github.com/metoppv/improver_test_data/pull/60
Updates the name of output cubes from the gradient-between-adjacent-modules so that the two output cubes can be distinguished.
Testing:
=> Update name of cubes from gradient module

improver/utilities/copy_metadata.py, improver_tests/utilities/copy_metadata/test_CopyMetadata.py
Addresses https://metoffice.atlassian.net/browse/EPPT-1717
This PR updates the ability of the copy attributes plugin to include an exception for copying the history attribute if there are multiple input template cubes. In this case the most recent time stamp is used. 
I've also slightly altered its ability to take in multiple cubes. Originally you could provide 1 template cubes and the attributes were copied from this cube onto all other provided cubes. I've now changed this to take in 1 cube and multiple template cubes requiring that the template cube attributes we are copying all match.
Testing:
=> Update copy_attribute plugin to include copying history attribute

.mailmap, CONTRIBUTING.md, improver/virtual_temperature.py, improver_tests/virtual_temperature/test_VirtualTemperature.py
Address: https://metoffice.atlassian.net/browse/EPPT-1965
This PR adds a plugin to calculate the virtual temperature based on the air temperature and humidity mixing ratio.
No CLI added due to the move to the DAG runner.
This is a replacement for the closed #2058 to avoid history rewrites and git configuration issues.
Testing:
Ran tests and they passed OK
Added new tests for the new feature(s)
CLA
If a new developer, signed up to CLA
=> Adding a plugin to calculate the virtual temperature (version 2)

.github/workflows/ci.yml, .github/workflows/scheduled.yml, envs/environment_a.yml
Switching to [micromamba](https://github.com/mamba-org/setup-micromamba) (the recommended approach to installation for mamba).  As per changes made to [improver_suite](https://github.com/MetOffice/improver_suite/pull/2403).
`environment_a` was having trouble with dependencies being resolved as micromamba fetches only from conda-forge by default (that is, using main was implicit before with conda mamba).  e.g. opencv related packages are from main as we see from a [recent action job run](https://github.com/metoppv/improver/actions/runs/12282461896/job/34273728578?pr=2065)).  Intriducing an explicit 'main' dependency fixes the issue.
Fixes scheduled IMPROVER CI:
Haven't/can't test `scheduled.yml` workflow but can make an additional change if a mistake has creeped in.
- …
=> TEST: Fix scheduled.yml and switch CI to using micromamba

.github/workflows/ci.yml, envs/conda-forge.yml
- Stop test duplication (limit push to default branch).
- Include setuptools in conda-forge environment.
```
WARNING: autodoc: failed to import module 'cli.wet_bulb_freezing_level' from module 'improver'; the following exception was raised:
No module named 'pkg_resources'
```
=> conda-forge sphinx doc build failure CI

.mailmap, CONTRIBUTING.md, improver/precipitation_type/freezing_rain.py, improver_tests/acceptance/SHA256SUMS, improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py
Added a cell method to indicate an accumulation for freezing rain where non-instantaneous.
Addresses: [#599](https://github.com/metoppv/mo-blue-team/issues/599)
Testing:
CLA
=> Added a cell method to indicate an accumulation for freezing rain where non-instantaneous

improver/cli/time_lagged_ensembles.py, improver/cli/vicinity.py, improver/cli/wind_direction.py, improver/cli/wind_gust_diagnostic.py, improver/utilities/spatial.py, improver/utilities/time_lagging.py, improver_tests/regrid/test_RegridLandSea.py
More CLI refactoring for simplified implementation of dagrunner
Testing:
=> More cli refactoring

doc/source/extended_documentation/spotdata/build_spotdata_cube/build_spotdata_cube_examples.rst, improver/metadata/constants/time_types.py
Remove references to UTC_offset coordinates as we no longer handle timezone information within IMPROVER.
Testing:
=> Remove references to UTC_offset

improver/cli/generate_percentiles.py, improver/percentile.py, improver_tests/percentile/test_PercentileConverter.py
This PR enables the retention of scalar coordinates that are generated when collapsing coordinates to generate percentiles. It also ensures that if these retained coordinates are time related (time, forecast_period, forecast_reference_time), they are modified to ensure that the point is aligned to the upper bound, adhering with IMPROVER's metadata standards.
The purpose of this change is to enable the production of typical wind speed diagnostics with our existing tooling. The suite chain will become:
```mermaid
flowchart TD
A(wind speed in 3-hours) --> B(merge CLI: construct 24-hour cube with time coordinate) --> C(generate_percentiles CLI: collapse time and realization coordinates to generate percentiles)
```
This change ensures that the time period covered by the diagnostic is available …
=> MOBT-797: Coordinate retention in percentile generation

improver/cli/generate_percentiles.py, improver/nbhood/nbhood.py, improver/percentile.py, improver_tests/percentile/test_PercentileConverter.py
This adaption to the is_iterable branch allows the percentiles attribute of `MetaNeighbourhood` to be set by a single value in a similar way to this adaption.
=> Make is_iterable changes applicable to percentiles option

improver/nbhood/__init__.py, improver/nbhood/nbhood.py, improver/utilities/common_input_handle.py, improver_tests/utilities/common_input_handle/test_as_iterable.py
Addresses: N/A
Description:
1. Added new `as_terable` to improver utilities, with a similar mindset to the previously added `as_cube` and `as_cubes` functions there.  This intends to improve the robustness of the plugin UI so that it does not unnecessarily require an iterable of an object when technically it should accommodate 1 of that object.
2. Made use of this `as_iterable` in the radius_by_lead_time.
Testing:
CLA
=> ENH: as_iterable for improved plugin argument handling + radius_by_lead_time using it

.mailmap, CONTRIBUTING.md, improver/calibration/reliability_calibration.py, improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py
This PR fixes a bug with applying reliability calibration to a cube with only a single threshold.
When reliability calibration was applied to a cube with only a single threshold the code would fail due to the method _ensure_monotonicity_across_thresholds of ApplyReliabilityCalibration.
As there are no dimensions associated with the threshold coordinate, assigning it to a variable leads to a ValueError. With a single threshold there is no need to check for monotonicity across thresholds so we can return straight away when there are no dimensions associated with the threshold coordinate.
New unit tests are added to cover this single threshold use case.
Testing:
CLA
=> Bug fix for reliability calibration of single threshold cube

improver/calibration/ensemble_calibration.py, improver_tests/calibration/ensemble_calibration/test_ApplyEMOS.py
Addresses #https://github.com/metoppv/mo-blue-team/issues/844
This PR removes the potential for cell methods to be duplicated within the ApplyEMOS plugin, when, for example, a probability forecast describing a period is provided.
Testing:
=> Avoid cell method duplication in ApplyEMOS

improver/cli/spot_extract.py, improver/spotdata/spot_manipulation.py, improver_tests/spotdata/test_SpotManipulation.py
The SpotManipulation plugin has some logic within in which determines which plugin is called to produce the desired forecast representation from the input forecast. The SpotManipulation plugin allows a skip_ecc_bounds input to be given, however this input is not passed along to the ResamplePercentiles plugin when converting a forecast containing one set of percentiles to another set of percentiles.
This PR fixes this small bug and adds a unit test for the fix.
Testing:
=> MOBT-810: Fix SpotManipulation skip_ecc_bounds bug

CONTRIBUTING.md, improver/api/__init__.py
Addresses [#GitHubissuenum]
https://metoffice.atlassian.net/browse/EPPT-2352
Description
Add virtual temperature to improver list of processing modules. This is called by the EPP-Workflows application - https://github.com/MetOffice/epp_workflows/pull/160
Testing:
- [Y] Ran tests and they passed OK
- [N] Added new tests for the new feature(s) (already tested in improver_tests/test_api.py)
all tests in improver_tests:
`5550 passed, 647 skipped, 1 xfailed, 3602 warnings in 392.08s (0:06:32)`
improver_tests/test_api.py:
`115 passed, 2 warnings in 1.16s`
CLA
=> add VirtualTemperature to PROCESSING_MODULES

improver/ensemble_copula_coupling/constants.py
Precipitation fraction, which is a fraction of a period of time, has ECC bounds that run 0-1. These need to be added to the ECC bound set.
Testing:
=> Add ECC bounds for precipitation fraction.

improver/api/__init__.py, improver/precipitation/snow_probability_at_surface.py, improver_tests/precipitation/snow_probability/test_snow_probability.py, improver_tests/precipitation/snow_probability_at_surface/test_snow_probability_at_surface.py
EPP ticket: https://metoffice.atlassian.net/browse/EPPT-2318
This PR adds in a plugin to calculate the probability that snow could occur at the surface based on a provided wet bulb temperature integral.
Testing:
=> Add in plugin to calculate the probability of snow at the surface

improver/nbhood/recursive_filter.py, improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py
I have made changes to the recursive filter to allow an option to mask zero values. This takes into account any previous mask and reapplies at the end so there is no change to any original masking. 
Testing:
=> Change to the recursive filter to allow an option to make zero values.

improver/psychrometric_calculations/condensation_trails.py, improver_tests/psychrometric_calculations/condensation_trails/test_CondensationTrailFormation.py
[Ticket](https://metoffice.atlassian.net/browse/EPPT-2305)
Description:
The engine mixing ratio is a required calculation in the estimation of condensation trail formation height. This PR sets up the basic class for formation calculations and adds in the method required to calculate the engine mixing ratio from specified values of engine contrail factors.
Testing:
=> EPPT-2305 contrails engine mixing ratio

improver/metadata/forecast_times.py, improver_tests/metadata/test_check_datatypes.py, improver_tests/metadata/test_utilities.py
Addresses [#913](https://github.com/metoppv/mo-blue-team/issues/913) and [#150](https://github.com/metoppv/mo-strategic-issues/issues/150).
This PR updates the metadata unit tests as required so that they are compatible with the updated IMPROVER conda environment. The fixes are listed below.
**improver/metadata/forecast_times.py**
- Since the release of cftime 1.1.0, num2date by default returns a cftime.datetime object instead of the datetime.datetime object the tests want. I have therefore set the kwarg only_use_cftime_datetimes to False.
**improver_tests/metadata/test_check_datatypes.py**
- Iris.tests.IrisTest depracated. Therefore can't call 'assertStringEqual'. Replaced test class inheritance from IrisTest to UnitTest as seen this has been done elsewhere, and called assertEqual …
=> Mobt913: Environment upgrade - Metadata

improver/developer_tools/metadata_interpreter.py, improver_tests/developer_tools/test_MOMetadataInterpreter.py, improver_tests/developer_tools/test_display_interpretation.py
Developer_tools: Updates metadata interpreter to print dict-like strings from CubeAttrsDict objects
Addresses https://github.com/metoppv/mo-blue-team/issues/908
The main issue in the developer_tools section is that `Cube.attributes` has changed from being a standard dict object to a [CubeAttrsDict](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.cube.html#iris.cube.CubeAttrsDict) object. This still has a `keys()` method, but the accompanying `__str__` method prints both keys and values, which is unhelpful. I have added a one-line function to convert these objects back into standard dict objects ONLY where we are printing out information from them. Then the only change is the ordering of the keys, as global keys are now returned before local keys and "title" is a global …
=> Developer_tools: Updates metadata interpreter to print dict-like strings from CubeAttrsDict objects

improver/generate_ancillaries/generate_orographic_smoothing_coefficients.py, improver/generate_ancillaries/generate_svp_table.py
Addresses https://github.com/metoppv/mo-blue-team/issues/911
- Modifications to the generate_orographic_smoothing_coefficients.py file to prevent type escalation to float64.
- Impose float64 type on constant used in SVP calculation to preserve original values.
Testing:
=> Environment upgrade: generate ancillaries

improver/between_thresholds.py, improver/categorical/modal_code.py, improver_tests/categorical/modal_code/test_ModalCategory.py
Related to https://github.com/metoppv/mo-blue-team/issues/936
Description
* Enforce float32 within the `OccurrenceBetweenThresholds` to ensure that the output cube contains float32 data as required.
* Ensure that the output of cube.collapsed in the ModalCategory plugin is the same data type as the input.
Testing:
=> Acceptance test batch 2

improver/categorical/modal_code.py
Accommodate type overflow in modal aggregator whilst resetting the data type at the end of the process.
The modal calculation uses max and unset values that can fall outside the range of data that may be accommodated by the input data dtype. This is made clear in the unit tests where the int8 type is unable to accommodate the min and max values causing an overflow. This change allows the type to grow in the modal aggregation to accommodate the transient values before being reset at the end of the process; the mode values must be within the bounds of the original data and so the original dtype must be sufficient to accommodate them.
=> MOBT-290 Environment upgrade: modal categories

improver/utilities/forecast_reference_enforcement.py
Move dtype setting out of numpy.clip call as this causes a casting error.
Allow clipping to occur, then apply type casting to result to ensure data type is unchanged.
Testing:
=> MOBT-290 Environment upgrade: enforce consistency

improver/psychrometric_calculations/psychrometric_calculations.py, improver_tests/psychrometric_calculations/test_calculate_svp_derivative_in_air.py
[EPPT-2510](https://metoffice.atlassian.net/browse/EPPT-2510)
This change is adding the calculation of saturation vapour pressure derivative in air.
The saturation vapour pressure (SVP), SVP corrected for air, and SVP derivative are already calculated by existing functions, so this change is focused on correcting the SVP derivative so it is valid in air. This involves creating the following new functions within `psychrometric_calculations.py`:
1. `_svp_derivative_table` - to run the extisting `SaturatedVapourPressureTableDerivative` function and generate a table of SVP derivative values.
2. `_svp_derivative_from_lookup` - To look up the SVP derivative values from the table of SVP derivative values, based in input temperatures.
3. `calculate_svp_derivative_in_air` - This is modifying the …
=> EPPT-2510: Adding calculation of saturation vapour pressure derivative in air

.github/workflows/ci.yml, CONTRIBUTING.md, README.md, doc/rtd_environment.yml
A few tidy-up changes related to the environment upgrade:
- Remove references to python 3.6 and 3.7.
- Upgrade pre-commit CI environment to use python 3.12.
- Update readme environment building advice, though this may be at odds with the currently available version of improver in the conda library; this needs updating.
- Update the python version badge shown in the readme.
- Remove Rachael's name from the contributors list for now as the merge commit, despite listing Rachael as one of the 7 authors, cannot identify any single commits associated with Rachael's rainforests work and thus complains.
=> Environment upgrade tidy-up

improver/cli/combine.py, improver/cube_combiner.py, improver_tests/cube_combiner/test_Combine.py
Addresses https://github.com/metoppv/mo-blue-team/issues/965
Add use_latest_frt option to the cube combiner. In combination with the expand_bound option this allows the time coordinates of a diagnostic to be expanded to represent a period, with the time point at the end of the inputs. The forecast reference time however will remain a single point scalar as the input cubes have been unified to this point prior to the combination step.
Testing:
=> Use latest FRT option for cube combiner

improver/metadata/forecast_times.py, improver_tests/metadata/test_forecast_times.py
This PR modifies the rebadge_forecasts_as_latest_cycle function to look for and update a blend_time if it is present on the cubes being rebadged. This ensures that the blend time and forecast reference time cannot get out of step.
This function has not been used for model blended diagnostics before, but it can have a use there, but to be useful it must also handle the blend_time coordinate if it exists, rather than just the forecast_reference_time. 
Testing:
=> rebadge_forecasts_as_latest_cycle modified for use in the mix suite

improver/regrid/bilinear.py
Prior to NumPy 1.24 a DeprecationWarning was given when an empty array is used in a boolean context. This is now a ValueError in more recent versions:
`ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.`
This PR fixes this in the recommended way, by evaluating the size of the array to be greater than zero.
Testing:
=> Fix empty array check

improver/precipitation/hail_fraction.py, improver_tests/precipitation/hail_fraction/test_HailFraction.py
Closes #2117
The documented meaning of masked convective cloud top temperature data is "no convection" (because the convection depth is too shallow). The HailFraction plugin doesn't explicitly handle masked values and so they are treated as deep convection which can yield hail.
This change explicitly handles masked or invalid convective cloud top temperature data as "no convection" with zero hail-fraction returned.
Testing:
=> HailFraction handles masked CTT data as "no convection"

doc/source/conf.py
gh actions is failling with scitools cartopy documentation changing URL.
At the same time I have updated scipy URL (was pointing to really old version).
https://github.com/metoppv/improver/actions/runs/17474093407/job/49629510211?pr=2185
=> Fix gh action Sphinx-Pytest-Coverage: updated intersphinx inventory URLs
