lib/improver/tests/test_threshold_basicthreshold.py
lib/improver/threshold.py

As with #1, import the Threshold plugin.
~Builds on #1 code, do not merge yet.~
The code is a straightforward lift and shift from our internal BGD codebase, with the exception of the process/operation swap.

Import threshold plugin

---

lib/improver/constants.py
lib/improver/tests/test_wind_downscaling_roughnesscorrection.py
lib/improver/wind_downscaling.py

This imports wind downscaling (1D height and roughness correction) from our internal code.
Code by Martina Friedrich of the Met Office, based on approach by [Howard and Clark 2007](http://onlinelibrary.wiley.com/doi/10.1002/met.12/full).

Import wind downscaling

---

lib/improver/tests/test_weighted_blend_BasicWeightedAverage.py
lib/improver/weighted_blend.py

Reference issue #35 Weighted Blending Plugin
Testing:
- [OK] Ran tests and they passed OK
- [OK] Added new tests for the new feature(s)
CLA
- [Not Applicable] If a new developer, signed up to CLA

35 weighted blending plugin

---

bin/improver-nbhood
lib/improver/nbhood.py
lib/improver/tests/helper_functions_ensemble_calibration.py
lib/improver/tests/test_ensemble_calibration_ApplyCoefficientsForEnsembleCalibration.py
lib/improver/tests/test_ensemble_calibration_EnsembleCalibration.py
lib/improver/tests/test_ensemble_calibration_EnsembleReordering.py
lib/improver/tests/test_ensemble_calibration_EstimateCoefficientsForEnsembleCalibration.py
lib/improver/tests/test_ensemble_calibration_GeneratePercentilesFromMeanAndVariance.py
lib/improver/tests/test_nbhood_basicneighbourhoodprocessing.py
tests/improver-nbhood/00-null.bats
tests/improver-nbhood/01-help.bats

#36 
Testing:
- [OK] Ran tests and they passed OK
- [OK] Added new tests for the new feature(s)

Neighbourhood processing: Configurable radius by lead times

---

lib/improver/tests/test_weights_ChooseDefaultWeightsLinear.py
lib/improver/tests/test_weights_ChooseDefaultWeightsNonLinear.py
lib/improver/weights.py

#39 Develop Blending weights function
Testing:
- [Ok ] Ran tests and they passed OK
- [Ok] Added new tests for the new feature(s)
CLA
- [N/A ] If a new developer, signed up to CLA

39 blending weights function

---

README.md

Added badge to README.md for documentation build status

---

lib/improver/tests/test_ensemble_calibration_ContinuousRankedProbabilityScoreMinimisers.py

Tidy up some unused imports as an example PR.
Testing:

Remove unused imports

---

bin/improver-percentile
tests/improver-percentile/01-help.bats

Additional information about default percentiles as requested by @MoseleyS . (Addition to issue #69).
Testing:

Additional printing from CLI to detail default percentiles.

---

lib/improver/constants.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py

Absolute zero fix

---

bin/improver-nbhood
bin/improver-wind-downscaling
lib/improver/tests/wind_downscaling/test_roughnesscorrection.py
lib/improver/wind_downscaling.py
tests/improver-wind-downscaling/00_null.bats
tests/improver-wind-downscaling/01_help.bats
tests/improver-wind-downscaling/02_basic.bats
tests/improver-wind-downscaling/03_veg.bats
tests/improver-wind-downscaling/04_with_realization.bats

Issue #67 
- CLI written
- sample input and known good output files created for bats tests.
- Bats tests for: no arguments, -help option, acceptance test with all compulsory arguments, acceptance test with -vegetation cover optional field.
Notes:
- currently target orography = standard orography. When target orography is defined in the future, acceptance tests will have to be updated.
- some technical debt notes were made on the original issue ( #67 ). These should be addressed in technical debt issues.
Testing:

Wind Downscaling CLI

---

etc/pylintrc
lib/improver/spotdata/common_functions.py
lib/improver/spotdata/extract_data.py
lib/improver/spotdata/neighbour_finding.py
lib/improver/spotdata/read_input.py
lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/spotdata/spotdata/test_extract_data.py
lib/improver/tests/spotdata/spotdata/test_neighbour_finding.py

Replacing PR #86, part of #34.
Testing:

Spot extraction cleaned up

---

bin/improver-nbhood
lib/improver/nbhood.py
lib/improver/tests/nbhood/test_neighbourhoodprocessing.py
lib/improver/tests/nbhood/test_utilities.py
tests/improver-nbhood/00-null.bats
tests/improver-nbhood/01-help.bats
tests/improver-nbhood/03-ens.bats

Reference issue #75 
Testing:
CLA

75 adjust nbh for ens v2

---

bin/improver-weighted-blending
bin/lib/utilities.py
lib/improver/argparser.py
tests/improver-weighted-blending/00-null.bats
tests/improver-weighted-blending/01-help.bats
tests/improver-weighted-blending/02-basic_nonlin.bats
tests/improver-weighted-blending/03_basic_lin.bats
tests/improver-weighted-blending/04_bothoptions_fail.bats
tests/improver-weighted-blending/05_options_nonlin.bats
tests/improver-weighted-blending/06_options_lin.bats
tests/improver-weighted-blending/07_coord_adj.bats
tests/improver-weighted-blending/08_linear_wrongargs.bats
tests/improver-weighted-blending/09_lin_nonlin_args.bats
tests/improver-weighted-blending/10_nonlin_lin_args.bats

Issue #110 
* See comments on Issue.
* Tests to check failure for incompatible options and acceptance tests.
Testing:

Weighted blending cli

---

lib/improver/utilities/spatial.py

A bug fix for #83 PR #147 
The problem was that not all the metadata from the coordinates was not copied across to the new cube.
Testing:

Bug fix to ensure all coordinate metadata is copied across onto new code

---

lib/improver/ensemble_calibration/ensemble_calibration.py

Improve ensemble calibration referencing

---

lib/improver/spotdata/common_functions.py
lib/improver/spotdata/extrema.py
lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/spotdata/spotdata/test_extrema.py

A component of #34
Added functions to move model data onto site local times and extract maxima and minima over defined periods.
Testing:

Extrema extraction

---

bin/improver-weighted-blending
lib/improver/tests/weights/test_ChooseDefaultWeightsLinear.py
lib/improver/tests/weights/test_ChooseDefaultWeightsNonLinear.py
lib/improver/tests/weights/test_WeightsUtilities.py
lib/improver/weights.py
tests/improver-weighted-blending/00-null.bats
tests/improver-weighted-blending/01-help.bats
tests/improver-weighted-blending/02-basic_nonlin.bats
tests/improver-weighted-blending/03_basic_lin.bats
tests/improver-weighted-blending/04_bothoptions_fail.bats
tests/improver-weighted-blending/05_options_nonlin.bats
tests/improver-weighted-blending/06_options_lin.bats
tests/improver-weighted-blending/07_coord_adj.bats
tests/improver-weighted-blending/08_linear_wrongargs.bats
tests/improver-weighted-blending/09_lin_nonlin_args.bats
tests/improver-weighted-blending/10_nonlin_lin_args.bats
tests/improver-weighted-blending/11-expected-coord-vals.bats

This is a new PR to complete work started by @carolinejjones in #157 
Issue: #82.
Comment from 2 reviews on PR #157 are addressed.
Testing:

Cjj 82 redistribute weights (version 2)

---

lib/improver/tests/nbhood/test_neighbourhoodprocessing.py

Correction of unit error noticed by @gavinevans in nbhood unit tests.
Testing:

Correct precipitation amount units to kg m^-2.

---

lib/improver/spotdata/extract_data.py
lib/improver/spotdata/neighbour_finding.py
lib/improver/spotdata/read_input.py
lib/improver/spotdata/write_output.py
lib/improver/tests/spotdata/spotdata/test_ancillaries.py
lib/improver/tests/spotdata/spotdata/test_extract_data.py
lib/improver/tests/spotdata/spotdata/test_neighbour_finding.py
lib/improver/tests/spotdata/spotdata/test_read_input.py
lib/improver/tests/spotdata/spotdata/test_write_output.py

A component of #34
Components to read and write data. Unit tests for reading and writing routines, plus missing tests for ancillaries.
Testing:

SpotData reading and writing.

---

bin/improver-nbhood
lib/improver/nbhood.py
lib/improver/tests/nbhood/test_circularneighbourhood.py
lib/improver/tests/nbhood/test_neighbourhoodprocessing.py
lib/improver/tests/nbhood/test_squareneighbourhood.py
lib/improver/tests/nbhood/test_utilities.py
tests/improver-nbhood/00-null.bats
tests/improver-nbhood/01-help.bats
tests/improver-nbhood/02-basic-circular.bats
tests/improver-nbhood/03-ens.bats
tests/improver-nbhood/04-basic-square.bats

Changes to CLI, plugin, unittests and cli tests to use radius in metres rather than kilometres.
Issue: #53 
Testing:
- Updated tests for the new units

Neighbourhood Processing radius from km -> m

---

lib/improver/nbhood.py
lib/improver/tests/nbhood/test_squareneighbourhood.py
tests/improver-nbhood/05-mask-square.bats

First attempt at modifying square neighbourhood class to handle cubes containing masked data. Bats test added and new unit tests for masked data.
Issue: #2 
Testing:

Square neighbourhood processing masked data

---

lib/improver/spotdata/extract_data.py
lib/improver/spotdata/neighbour_finding.py
lib/improver/spotdata/read_input.py
lib/improver/spotdata/site_data.py
lib/improver/tests/spotdata/spotdata/test_neighbour_finding.py
lib/improver/tests/spotdata/spotdata/test_site_data.py

A component of #34 
Adds ability to read site definitions from json files or options set at the interface.
Testing:

Added components to read or define site details.

---

bin/improver-ecc
bin/improver-ensemble-calibration
bin/improver-generate-topographybands-ancillary
bin/improver-gradient
bin/improver-nbhood
bin/improver-percentile
bin/improver-spot-extract
bin/improver-weighted-blending
bin/improver-wind-downscaling
doc/source/conf.py

Issues #179 
Still getting a warning saying unsuitable module names. We could change the pylintrc to make an exception, but I'm not sure we should.
Only other outstanding pylint errors are some TODO statements remaining, two warnings in weighted-blending which I'm not sure how to fix and some similar lines in two CLIs.
Testing:

179 bin directory cleanup

---

lib/improver/tests/weights/test_ChooseDefaultWeightsTriangular.py
lib/improver/tests/weights/test_WeightsUtilities.py
lib/improver/weights.py

Reference issue #202 
Testing:

202 triangular weighted function

---

.travis.yml

Test PR to see if forcing Numpy to 1.11.1 fixes some testing issues.

Edit to Travis to force numpy version to 1.11.1

---

bin/improver-blend-adjacent-points
bin/improver-weighted-blending
lib/improver/blending/blend_across_adjacent_points.py
lib/improver/blending/weighted_blend.py
lib/improver/tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py
lib/improver/tests/blending/weighted_blend/test_MaxProbabilityAggregator.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/utilities/cube_manipulation.py
tests/improver-blend-adjacent-points/00-null.bats
tests/improver-blend-adjacent-points/01-help.bats
tests/improver-blend-adjacent-points/02_basic_mean.bats
tests/improver-blend-adjacent-points/03_basic_max.bats
tests/improver-weighted-blending/00-null.bats
tests/improver-weighted-blending/01-help.bats
tests/improver-weighted-blending/02-basic_nonlin.bats
tests/improver-weighted-blending/03_basic_lin.bats
tests/improver-weighted-blending/04_bothoptions_fail.bats
tests/improver-weighted-blending/05_options_nonlin.bats
tests/improver-weighted-blending/06_options_lin.bats
tests/improver-weighted-blending/07_coord_adj.bats
tests/improver-weighted-blending/08_linear_wrongargs.bats
tests/improver-weighted-blending/09_lin_nonlin_args.bats
tests/improver-weighted-blending/10_nonlin_lin_args.bats
tests/improver-weighted-blending/11-expected-coord-vals.bats
tests/improver-weighted-blending/12-percentile_blending.bats
tests/improver-weighted-blending/13-weighted_max.bats

#189 
Full PR to meet outstanding acceptance criteria.
Testing:

189 part2 max probabilities

---

lib/improver/convection.py
lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/threshold.py

Impro 207 threshold naming convention

---

bin/improver-threshold
lib/improver/convection.py
lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/threshold.py
tests/improver-threshold/01-help.bats

Changes to move looping over multiple thresholds into the plugin and out of the CLI. Added new unit tests to check this works and modified other tests to account for changes.
Also removed error associated with thresholds of zero and removed associated unit test.
Testing:

Multiple threshold handling within threshold plugin.

---

bin/improver-spot-extract
lib/improver/spotdata/extract_data.py
lib/improver/spotdata/main.py
lib/improver/tests/spotdata/spotdata/test_main.py
tests/improver-spot-extract/00-null.bats
tests/improver-spot-extract/01-help.bats

Refactoring of the top-level of the SpotData framework, so that the reading in from a file, and the writing out to a file happens within the CLI, rather than at multiple lower-level points, so that this aspect of the SpotData framework is more consistent with other CLIs.
Issue: #217
Testing:

IMPRO-262 Refactor SpotData CLI to change file loading and saving

---

bin/improver-spot-extract
lib/improver/spotdata/ancillaries.py
lib/improver/spotdata/main.py
lib/improver/spotdata/read_input.py
lib/improver/spotdata/site_data.py
lib/improver/spotdata/write_output.py
lib/improver/tests/spotdata/spotdata/test_ancillaries.py
lib/improver/tests/spotdata/spotdata/test_main.py
lib/improver/tests/spotdata/spotdata/test_read_input.py
lib/improver/tests/spotdata/spotdata/test_site_data.py
tests/improver-spot-extract/00-null.bats
tests/improver-spot-extract/01-help.bats
tests/improver-spot-extract/02-nearest.bats
tests/improver-spot-extract/03-model_level.bats

Refactor SpotData CLI to change usage of forecast times

---

lib/improver/blending/weighted_blend.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
tests/lib/utils

This is to remove a memory problem where there are lots of thesholds on the cube.
Reference issue #300 
Testing:
CLA

Adding changes so that when blending we slice over thresholds

---

lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/wxcode/wxcode_utilities.py

Reference issue #294 
Testing:
CLA
- [n/a] If a new developer, signed up to CLA

Changes to add weather_code metadata #294

---

bin/improver

Help for IMPROVER_SITE_INIT environment override, see #272

help for IMPROVER_SITE_INIT override

---

lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/wxcode/wxcode_utilities.py

Revised weather code metadata changes

---

lib/improver/blending/weighted_blend.py
lib/improver/blending/weights.py
lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/percentile.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/blending/weights/test_ChooseDefaultWeightsLinear.py
lib/improver/tests/blending/weights/test_ChooseDefaultWeightsNonLinear.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
lib/improver/tests/percentile/test_PercentileConverter.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/tests/wind_downscaling/test_roughnesscorrection.py
lib/improver/utilities/cube_manipulation.py
lib/improver/wind_downscaling.py

Replace ValueError with TypeError where appropriate.

---

bin/improver-wind-gust-diagnostic
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py
lib/improver/utilities/cube_manipulation.py
lib/improver/wind_gust_diagnostic.py
tests/improver-wind-gust-diagnostic/00-null.bats
tests/improver-wind-gust-diagnostic/01-help.bats
tests/improver-wind-gust-diagnostic/02-average-wind-gust.bats
tests/improver-wind-gust-diagnostic/03-extreme-wind-gust.bats

256 windgust

---

bin/improver-percentile
lib/improver/percentile.py
tests/improver-percentile/01-help.bats
tests/improver-percentile/02-basic.bats

a list of floats instead of integers for requested percentile values.
Reference issue IMPRO336
Testing:

Pull request to fix bug in improver-percentile. Changed to accept

---

bin/improver-ecc
lib/improver/blending/weighted_blend.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_RebadgePercentilesAsMembers.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py
lib/improver/tests/utilities/test_cube_checker.py
lib/improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py
lib/improver/utilities/cube_checker.py
lib/improver/wind_gust_diagnostic.py

Reference issue IMPRO336
Testing:
- [Some tests ] Ran tests and they passed OK

percentile_over_realization bug

---

bin/improver-blend-adjacent-points
lib/improver/generate_ancillaries/generate_ancillary.py
lib/improver/tests/generate_ancillaries/test_generate_ancillary.py

unit test set to check that topographic band units are correct
full stop removed from blend_adjacent points file
Testing:

topographic_bands hardcoded to have units of cfunits.Unit('m')

---

lib/improver/nbhood/vicinity.py
lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/tests/wxcode/wxcode/test_wxcode_decision_tree.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/weather_symbols.py
lib/improver/wxcode/weather_symbols.py
lib/improver/wxcode/wxcode_decision_tree.py
lib/improver/wxcode/wxcode_utilities.py

#292 (IMPRO-341)
Implementation of the weather symbols decision tree.
Tests have not been added. There are some print statements left in, commented out, which might he helpful in trying to understand what is going on.
More information is on IMPRO-341.
Testing:

Weather symbol implementation

---

bin/improver-generate-topographybands-ancillary
lib/improver/generate_ancillaries/generate_ancillary.py
lib/improver/tests/generate_ancillaries/test_topographicmasks.py
tests/improver-generate-topographybands-ancillary/00-null.bats
tests/improver-generate-topographybands-ancillary/01-help.bats
tests/improver-generate-topographybands-ancillary/02_basic.bats
tests/improver-generate-topographybands-ancillary/03-bounds_json.bats

Allow user to specify Topography bands from a .json file.
Testing:

Imp 346 ii allow topographic bands arg

---

bin/improver-nbhood-vicinity
lib/improver/nbhood/vicinity.py
lib/improver/tests/nbhood/vicinity/test_ProbabilityOfOccurrence.py
tests/improver-nbhood-vicinity/00-null.bats
tests/improver-nbhood-vicinity/01-help.bats
tests/improver-nbhood-vicinity/02-basic.bats
tests/improver-nbhood-vicinity/03-ens.bats

Reference issue #319 
Testing:

CLI for Vicinity plugin

---

lib/improver/tests/ensemble_calibration/ensemble_calibration/helper_functions.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py
lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/wxcode/weather_symbols.py
lib/improver/wxcode/wxcode_decision_tree.py

Imp 380 wx symbols plugin additions

---

bin/improver-wxcode
tests/improver-wxcode/00-null.bats
tests/improver-wxcode/01-help.bats
tests/improver-wxcode/02-basic.bats
tests/improver-wxcode/03-si_units.bats

This also contains commits from #335, and should only be merged subsequent to that ticket. It will probably be easier to proofread too!
Testing:

Imp 373 cli for wx symbol plugin

---

bin/improver-weighted-blending
lib/improver/blending/weighted_blend.py
lib/improver/nbhood/nbhood.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/blending/weighted_blend/test_conform_metadata.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/utilities/temporal.py
tests/improver-weighted-blending/00-null.bats
tests/improver-weighted-blending/01-help.bats
tests/improver-weighted-blending/04_bothoptions_fail.bats
tests/improver-weighted-blending/08_linear_wrongargs.bats
tests/improver-weighted-blending/09_lin_nonlin_args.bats
tests/improver-weighted-blending/10_nonlin_lin_args.bats
tests/improver-weighted-blending/14-cycletime.bats
tests/improver-weighted-blending/15-cycletime_remove_bounds.bats

Cycle and model blending metadata

---

.travis.yml
lib/improver/psychrometric_calculations/psychrometric_calculations.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_Utilities.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperatureIntegral.py
lib/improver/utilities/mathematical_operations.py

Reference issue #318 
Testing:

318 falling snow level

---

bin/improver-weighted-blending
lib/improver/blending/weighted_blend.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/utilities/cube_manipulation.py
tests/improver-weighted-blending/00-null.bats
tests/improver-weighted-blending/01-help.bats
tests/improver-weighted-blending/04_bothoptions_fail.bats
tests/improver-weighted-blending/09_lin_nonlin_args.bats
tests/improver-weighted-blending/10_nonlin_lin_args.bats
tests/improver-weighted-blending/16_model_blending.bats

Reference issue #275 
Testing:

275 multiple files in blending

---

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py

Add more diagnostics for ECC to support.

Support more diagnostic in ECC constants for percentile extraction

---

lib/improver/spotdata/extract_data.py
lib/improver/tests/spotdata/spotdata/test_extract_data.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/utilities/cube_manipulation.py

Reference issue #180 
Testing:
- [ X] Ran tests and they passed OK
- [ X ] Added new tests for the new feature(s)

180 useful spotdata utilities

---

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py

Low cloud constants added to ECC.

---

bin/improver-generate-topography-bands-weights
tests/improver-generate-topography-bands-weights/04-missing_landmask.bats

Add correction to improver-generate-topography-bands-weights following incorrect rebase. A bats test has been added to test the exception being raised.
#362 
Testing:

Bug fix to improver-generate-topography-bands-weights

---

lib/improver/spotdata/common_functions.py
lib/improver/spotdata/neighbour_finding.py
lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/utilities/test_spatial.py
lib/improver/utilities/spatial.py

Reference issue #180 
Testing:

Refactoring spatial spotdata utilities into spatial.py

---

bin/improver-tests

Timing added to CLI test

---

bin/improver-combine
lib/improver/cube_combiner.py
lib/improver/tests/cube_combiner/test_CubeCombiner.py
tests/improver-combine/04-min-temp.bats
tests/improver-combine/05-max-temp.bats
tests/improver-combine/06-accumulations.bats
tests/improver-combine/07-mean-temp.bats

Testing:
The tests will fail becuase the kgo for the bats testing is not updated.

Imp 422 make cube combiner do nice things with time bounds

---

lib/improver/nbhood/use_nbhood.py
lib/improver/tests/nbhood/use_nbhood/test_ApplyNeighbourhoodProcessingWithAMask.py

Added an additional loop to the collapsing over topographic bands to solve memory issues.

---

bin/improver-nbhood-iterate-with-mask
lib/improver/blending/weights.py
lib/improver/generate_ancillaries/generate_ancillary.py
lib/improver/nbhood/use_nbhood.py
lib/improver/tests/blending/weights/test_WeightsUtilities.py
lib/improver/tests/generate_ancillaries/test_GenerateOrographyBandAncils.py
lib/improver/tests/nbhood/use_nbhood/test_CollapseMaskedNeighbourhoodCoordinate.py
tests/improver-nbhood-iterate-with-mask/00-null.bats
tests/improver-nbhood-iterate-with-mask/01-help.bats
tests/improver-nbhood-iterate-with-mask/03-basic_collapse_bounds.bats
tests/improver-nbhood-iterate-with-mask/04-collapse_store_intermediate.bats
tests/improver-nbhood-iterate-with-mask/05-collapse_no_clip.bats

IMPRO-411
Github #365 
Testing:

Collapse the topographic zone coordinate after using topographic bands in neighbourhooding.

---

lib/improver/cube_combiner.py
lib/improver/tests/utilities/test_ProbabilitiesFromPercentiles2D.py
lib/improver/tests/utilities/test_statistical_operations.py
lib/improver/utilities/cube_metadata.py
lib/improver/utilities/statistical_operations.py

A plugin to interpolate percentiles to intermediate values to extract probabilities.
There is a notebook relating to IMPRO-296 in improver_aux that includes this plugin with demonstrations of its use, and which outlines a preferred method for using it in the suite.
There are currently no tests to go with this plugin, these will be added after it has been looked at.

IMPRO-296 Snow falling probability - Percentile to Probability

---

bin/improver-nbhood-land-and-sea
tests/improver-nbhood-land-and-sea/00-null.bats
tests/improver-nbhood-land-and-sea/01-help.bats
tests/improver-nbhood-land-and-sea/02-no_topographic_bands.bats
tests/improver-nbhood-land-and-sea/03-topographic_bands.bats
tests/improver-nbhood-land-and-sea/04-unneeded_weights.bats
tests/improver-nbhood-land-and-sea/05-missing_weights.bats
tests/improver-nbhood-land-and-sea/06-incorrect_weights_masking.bats
tests/improver-nbhood-land-and-sea/07-intermediate_output.bats
tests/improver-nbhood-land-and-sea/07-topographic_mask_with_sea.bats
tests/improver-nbhood-land-and-sea/08-intermediate_output.bats

A new CLI to process land and sea points separately before combining in the output.
Testing:

IMPRO-427 (PT II): Create new CLI to enable nbhood processing of land and sea separately.

---

bin/improver-nbhood-land-and-sea

Bug fix for masks the wrong way round for non-topographic neighbourhooding

---

lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/utilities/temporal.py

Fix extraction so it ignores the bounds on the coordinate.

---

bin/improver-blend-adjacent-points
bin/improver-combine
bin/improver-ecc
bin/improver-ensemble-calibration
bin/improver-generate-landmask-ancillary
bin/improver-generate-topography-bands-mask
bin/improver-generate-topography-bands-weights
bin/improver-gradient
bin/improver-nbhood
bin/improver-nbhood-iterate-with-mask
bin/improver-nbhood-land-and-sea
bin/improver-nbhood-vicinity
bin/improver-percentile
bin/improver-percentiles-to-probabilities
bin/improver-recursive-filter
bin/improver-snow-falling-level
bin/improver-spotdb
bin/improver-threshold
bin/improver-weighted-blending
bin/improver-wet-bulb-temperature
bin/improver-wind-downscaling
bin/improver-wind-gust-diagnostic
bin/improver-wxcode
lib/improver/tests/utilities/test_save.py
lib/improver/utilities/save.py

Incorporating "iris.FUTURE.no_unlimited_dimensions = True" breaks some existing CLI tests.  This PR replicates the existing "save" functionality with a dummy wrapper, and identifies the known good output that needs to be updated before developing the required new "save" functionality.
Testing:

Impro426: replicate existing "save" functionality accounting for iris future behaviour

---

bin/improver-nbhood-iterate-with-mask
bin/improver-nbhood-land-and-sea
lib/improver/nbhood/square_kernel.py
lib/improver/tests/nbhood/nbhood/test_BaseNeighbourhoodProcessing.py
lib/improver/tests/nbhood/nbhood/test_RecursiveFilter.py
lib/improver/tests/nbhood/square_kernel/test_SquareNeighbourhood.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/utilities/cube_manipulation.py

Moved data clipping into utilities as there was a need to slice to avoid memory issues; code is used in multiple places. Also added slicing to the square_kernel, again to mitigate memory issues.
IMPRO-430
Testing:

IMPRO-430 - Memory mitigation changes for nbhooding with masks.

---

lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/tests/wind_downscaling/test_FrictionVelocity.py
lib/improver/wind_downscaling.py

This addresses issue #19 concerning developing tests for the FrictionVelocity plugin of wind downscaling.
Issue #19 
Testing:
CLA

Impro249: Friction velocity unit tests

---

tests/improver-extract/07-list-constraints.bats

Changes bats test to accommodate new input file.

IMPRO450: Small change to accommodate smaller test input file

---

lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/blending/weighted_blend/test_conform_metadata.py
lib/improver/tests/cube_combiner/test_CubeCombiner.py
lib/improver/tests/database/test_SpotDatabase.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromMeanAndVariance.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromProbabilities.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py
lib/improver/tests/generate_ancillaries/test_GenerateTopographicZoneWeights.py
lib/improver/tests/nbhood/vicinity/test_ProbabilityOfOccurrence.py
lib/improver/tests/percentile/test_PercentileConverter.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperature.py
lib/improver/tests/spotdata/spotdata/test_WriteOutput.py
lib/improver/tests/spotdata/spotdata/test_ancillaries.py
lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/spotdata/spotdata/test_extract_data.py
lib/improver/tests/spotdata/spotdata/test_extrema.py
lib/improver/tests/spotdata/spotdata/test_read_input.py
lib/improver/tests/utilities/test_ProbabilitiesFromPercentiles2D.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/tests/utilities/test_cube_metadata.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/tests/utilities/test_warnings_handler.py
lib/improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py
lib/improver/utilities/warnings_handler.py

Reference issue #249 
This is a new pull request to try and pull in Fiona's changes to reduce warnings in unit test. Original PR was #383 
Testing:

249  Reduce warnings in unit test 

---

lib/improver/blending/weighted_blend.py

IMPRO-509
Testing:
- [x ] Ran tests and they passed OK

Impro 509: Remove cell method customisation when blending

---

lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/tests/wind_downscaling/test_FrictionVelocity.py
lib/improver/tests/wind_downscaling/test_RoughnessCorrection.py
lib/improver/tests/wind_downscaling/test_roughnesscorrection.py
lib/improver/utilities/cube_manipulation.py
lib/improver/wind_downscaling.py

IMPRO_504 Downscaled precision and added unit tests

---

.travis.yml
bin/improver-percentiles-to-probabilities
bin/improver-spotdb
bin/improver-tests
lib/improver/blending/weighted_blend.py
lib/improver/constants.py
lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/nbhood/use_nbhood.py
lib/improver/spotdata/ancillaries.py
lib/improver/spotdata/common_functions.py
lib/improver/spotdata/site_data.py
lib/improver/spotdata/write_output.py
lib/improver/tests/blending/weighted_blend/test_PercentileBlendingAggregator.py
lib/improver/tests/blending/weights/test_WeightsUtilities.py
lib/improver/tests/nbhood/nbhood/test_GeneratePercentilesFromANeighbourhood.py
lib/improver/tests/nbhood/nbhood/test_NeighbourhoodProcessing.py
lib/improver/tests/spotdata/spotdata/test_ancillaries.py
lib/improver/tests/utilities/test_cube_manipulation.py
lib/improver/tests/utilities/test_cube_metadata.py
lib/improver/tests/utilities/test_spatial.py
lib/improver/tests/utilities/test_warnings_handler.py
lib/improver/tests/wind_downscaling/test_FrictionVelocity.py
lib/improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py
lib/improver/tests/wxcode/wxcode/test_wxcode_decision_tree.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/utilities/statistical_operations.py
lib/improver/wind_downscaling.py
tests/improver-tests/00-help.bats
tests/improver-tests/01-bad-option.bats

Addresses issue #332.
Supersedes @bayliffe's PR #463  
Testing:

pycodestyle changes

---

lib/improver/spotdata/write_output.py
lib/improver/tests/utilities/test_load.py
lib/improver/tests/utilities/test_save.py
lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py

JIRA ticket: IMPRO-508
Testing:
- [x ] Ran tests and they passed OK
- [N/A ] Added new tests for the new feature(s)

Replaced loadsave with IMPROVER equivalents

---

bin/improver-threshold
lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/threshold.py
tests/improver-threshold/01-help.bats
tests/improver-threshold/08-threshold_units_fuzzy_factor.bats

#503 
Fixes issue, plus new unit and CLI tests to cover.
Testing:

Thresholding with fuzzy factor and unit conversion

---

lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py

Fix for iris2 "cell_datetime_object" behaviour in ensemble calibration tests

---

.travis.yml

Required for Iris 2 feature branch.
Related issues: #474, #476
Testing:

Upgrade Travis to use Iris 2.

---

lib/improver/optical_flow/optical_flow.py
lib/improver/tests/optical_flow/test_AdvectField.py

Create IMPROVER plugin to extrapolate a field using advection velocities

---

lib/improver/tests/wind_direction/test_WindDirection.py
lib/improver/wind_direction.py

Issue No: #490
Testing:
- [x ] Ran tests and they passed OK
- [x ] Added new tests for the new feature(s)

Created wind direction averaging plugin

---

lib/improver/spotdata/extrema.py
lib/improver/tests/spotdata/spotdata/test_extrema.py

#484 
New CLI test output required
Testing:

Removed changes to forecast reference time coordinate in min / max spot extract

---

bin/improver-wind-direction
tests/improver-wind-direction/00-null.bats
tests/improver-wind-direction/01-help.bats
tests/improver-wind-direction/02-basic.bats

Addresses #521 
Description:
Added CLI interface and tests for wind direction plugin.
Testing:
- [ x] Ran tests and they passed OK
- [x ] Added new tests for the new feature(s)

Added CLI interface and tests for wind dir

---

bin/improver-threshold
tests/improver-threshold/00-null.bats
tests/improver-threshold/01-help.bats
tests/improver-threshold/09-coordinate_collapse_realization
tests/improver-threshold/09-coordinate_collapse_realization.bats

Addresses #512 
Description
Testing:
CLA

Impro 624 add coordinate collapse

---

bin/improver-percentile
lib/improver/percentile.py
lib/improver/tests/percentile/test_PercentileConverter.py
tests/improver-percentile/06-masked_cube.bats

Changed percentile CLI to use fast_percentile_method within Iris 2.
Testing:

IMPRO-212: A faster percentile method.

---

bin/improver-nbhood
lib/improver/nbhood/square_kernel.py
lib/improver/tests/nbhood/square_kernel/test_SquareNeighbourhood.py
tests/improver-nbhood/00-null.bats
tests/improver-nbhood/01-help.bats
tests/improver-nbhood/15-wind-direction.bats

Modifications to allow neighbourhood processing of complex numbers

---

lib/improver/psychrometric_calculations/psychrometric_calculations.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py

Addresses #586 
Refactors the filling function into separate steps so each one can be modified separately. This change doesn't add any new functionality.
The .process unit tests are unchanged, as is the CLI test data.
Testing:
CLA

Refactored to allow for separate filling functions

---

doc/source/conf.py
lib/improver/psychrometric_calculations/psychrometric_calculations.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperatureIntegral.py

Impro 621 improve snow extrapolate

---

lib/improver/tests/utilities/test_TemporalInterpolation.py
lib/improver/utilities/temporal.py

Plugin to perform temporal interpolation.
Testing:

IMPRO-638: Plugin to perform temporal interpolation.

---

.gitignore

I think this is ok, I don't think we need to track these files, but I'm not 100% certain.
Testing:

Update .gitignore to ignore files generated by code coverage tests.

---

lib/improver/nowcasting/optical_flow.py
lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py

Implements recommendations following literature review of optical flow method.  Some changes to unit tests required, mostly relating to minimum iterations requirement.

IMPRO-720 optical flow usage

---

lib/improver/psychrometric_calculations/psychrometric_calculations.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_FallingSnowLevel.py
lib/improver/tests/utilities/test_spatial.py
lib/improver/utilities/spatial.py

Addresses IMPRO-779
Description
Testing:
CLA

Impro 779 fill in horizontally

---

bin/improver-wind-direction
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py
tests/improver-wind-direction/00-null.bats
tests/improver-wind-direction/01-help.bats
tests/improver-wind-direction/03-global.bats

Description:
There are a few changes which are required to get the global data working properly
1. Add precipitation_rate to BOUNDS_FOR_ECDF in ensemble_coupla_coupling_constants.py
2. Add option for backup_method to wind-direction CLI
Testing:

Impro787 global chains

---

lib/improver/constants.py
lib/improver/lapse_rate.py
lib/improver/tests/lapse_rate/Test_LapseRate.py

Description:
Created basic Lapse Rate code - there are unresolved questions which are highlighted in the doc string for the class.
I have added an extremely basic unit test file, this is not intended to be the finished version. It is simply to allow the user to run the code themselves using a simplistic dataset.
Testing:
- [ x] Ran tests and they passed OK
- [ x] Added new tests for the new feature(s)

Added Lapse Rate code and basic test

---

lib/improver/tests/utilities/cube_manipulation/test__equalise_coord_bounds.py
lib/improver/tests/utilities/cube_manipulation/test__equalise_cube_attributes.py
lib/improver/tests/utilities/cube_manipulation/test_compare_attributes.py
lib/improver/tests/utilities/cube_manipulation/test_demote_float64_precision.py
lib/improver/tests/utilities/cube_manipulation/test_equalise_cubes.py
lib/improver/tests/utilities/cube_manipulation/test_merge_cubes.py
lib/improver/tests/utilities/test_cube_metadata.py
lib/improver/tests/utilities/test_save.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/utilities/cube_manipulation.py
lib/improver/utilities/cube_metadata.py
lib/improver/utilities/save.py
lib/improver/utilities/temporal.py
tests/improver-weighted-blending/16_model_blending.bats

Addresses #284 
Implements improvements to the utilities.cube_manipulation module recommended by @carolinejjones.
See JIRA ticket for full list of modifications.
A separate PR will implement the improvements to weights.py.
Testing:

Impro 331 Improve cube_manipulation

---

lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/wxcode/weather_symbols.py
lib/improver/wxcode/wxcode_utilities.py

Addresses #500
Description : Adding update to weather symbol depending on day or night.
Testing:

Impro605 day night wxcode

---

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_constants.py

Adds ECDF bounds for relative humidity as part of IMPRO-757.

Add ECDF bounds for relative humidity

---

bin/improver-orographic-enhancement
lib/improver/orographic_enhancement.py
lib/improver/tests/orographic_enhancement/test_OrographicEnhancement.py
lib/improver/tests/utilities/test_filename.py
lib/improver/utilities/filename.py
tests/improver-orographic-enhancement/00-null.bats
tests/improver-orographic-enhancement/01-help.bats
tests/improver-orographic-enhancement/02-basic.bats
tests/improver-orographic-enhancement/03-boundary_height.bats
tests/improver-orographic-enhancement/04-unit_convert_boundary_height.bats
tests/improver-orographic-enhancement/05-height_level_not_found.bats

Addresses #599 
CLI and tests for calculating orographic enhancement.  This works but runs very slowly (86.6 seconds per functional test).  Plugins may need some optimisation.
Testing:

Orographic enhancement CLI

---

bin/improver-threshold
lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/tests/utilities/test_OccurrenceWithinVicinity.py
lib/improver/threshold.py
lib/improver/utilities/spatial.py
tests/improver-threshold/12-vicinity_masked.bats

Description : Threshold-in-vicinity works with masked data
Testing:

Impro886 vicinity masked data

---

bin/improver-wxcode
lib/improver/tests/utilities/solar/test_DayNightMask.py
lib/improver/tests/utilities/solar/test_solar.py
lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/tests/wxcode/wxcode/test_wxcode_decision_tree_global.py
lib/improver/utilities/solar.py
lib/improver/wxcode/weather_symbols.py
lib/improver/wxcode/wxcode_decision_tree_global.py
tests/improver-wxcode/00-null.bats
tests/improver-wxcode/01-help.bats
tests/improver-wxcode/04-global.bats
tests/improver-wxcode/05-insufficient-files.bats

Description - Adding a new weather code tree for Global data.
Testing:

Impro739 global vicinity wxcode

---

lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
lib/improver/tests/nowcasting/optical_flow/test_AdvectField.py
lib/improver/tests/nowcasting/optical_flow/test_OpticalFlow.py
lib/improver/tests/psychrometric_calculations/psychrometric_calculations/test_WetBulbTemperature.py
lib/improver/tests/spotdata/spotdata/test_common_functions.py
lib/improver/tests/spotdata_new/spotdata_new/test_NeighbourSelection.py
lib/improver/tests/utilities/test_ProbabilitiesFromPercentiles2D.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/tests/utilities/test_warnings_handler.py

Addresses #701 
Description
Testing:

Updating unit tests to be more flexible for warnings.

---

doc/source/extended_documentation/spot_extraction_examples.rst
lib/improver/spotdata_new/spot_extraction.py
lib/improver/tests/spotdata_new/spotdata_new/test_SpotExtraction.py
lib/improver/tests/spotdata_new/spotdata_new/test_check_cube_compatibility.py

A plugin to use neighbour cubes to extract spot data plus unit tests.
Testing:

IMPRO879: Spotdata diagnostic data extraction plugin

---

.travis.yml
lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py
lib/improver/tests/blending/weighted_blend/test_unify_forecast_reference_time.py
lib/improver/tests/utilities/test_TemporalInterpolation.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/utilities/solar.py

Fixes following cftime change to operating temporal precision.
Details given in IMPRO-978.
Testing:

CF-Time update fixes

---

.travis.yml
lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py
lib/improver/tests/blending/weighted_blend/test_unify_forecast_reference_time.py
lib/improver/tests/utilities/test_TemporalInterpolation.py
lib/improver/tests/utilities/test_temporal.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/utilities/solar.py

Revert "CF-Time update fixes"

---

lib/improver/tests/uv_index/test_uv_index.py
lib/improver/uv_index.py

Addresses #661 
Description
Testing:
I have added a plugin (and associated unit tests) to calculate the uv index.

Adding a plugin (and unit tests) to calculate the uv index.

---

bin/improver-feels-like-temp
tests/improver-feels-like-temp/00-null.bats
tests/improver-feels-like-temp/01-help.bats
tests/improver-feels-like-temp/02-basic.bats

The feels-like-temperature CLI and associated bats tests.

---

lib/improver/lapse_rate.py

Fixed future warning in lapse rate plugin.  Unit tests pass.

Added necessary line to fix future warning.

---

bin/improver-extend-radar-mask
tests/improver-extend-radar-mask/00-null.bats
tests/improver-extend-radar-mask/03-float64.bats

Updated CLI and bats tests for extend-radar-mask required for IMPR0-1002

---

bin/improver-uv-index
lib/improver/tests/uv_index/test_uv_index.py
lib/improver/uv_index.py
tests/improver-uv-index/00-null.bats
tests/improver-uv-index/01-help.bats
tests/improver-uv-index/02-basic.bats

Description: Create a CLI for UV index
Testing:

IMPRO-892 CLI for UV - initial draft

---

bin/improver-temporal-interpolate
lib/improver/utilities/temporal.py
tests/improver-temporal-interpolate/00-null.bats
tests/improver-temporal-interpolate/01-help.bats
tests/improver-temporal-interpolate/02-basic.bats
tests/improver-temporal-interpolate/03-linear_interval.bats
tests/improver-temporal-interpolate/04-error_file_names.bats

Description : Add command line interface for temporal interpolation
Testing:

IMPRO 827 CLI for temporal interpolation.

---

bin/improver-percentiles-to-realizations
bin/improver-probabilities-to-realizations
lib/improver/blending/weighted_blend.py
lib/improver/feels_like_temperature.py
lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py
lib/improver/tests/utilities/test_RegridLandSea.py

Fixes some pep8 issues that aren't thrown up by a later version of pycodestyle.

Fix some pep8 issues

---

bin/improver-wxcode
lib/improver/nowcasting/lightning.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/blending/weighted_blend/test_rationalise_blend_time_coords.py
lib/improver/tests/nowcasting/lightning/test_NowcastLightning.py
lib/improver/tests/set_up_test_cubes.py
lib/improver/tests/test_set_up_test_cubes.py
lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/tests/utilities/test_cube_extraction.py
lib/improver/tests/utilities/test_cube_metadata.py
lib/improver/tests/wxcode/wxcode/test_WeatherSymbols.py
lib/improver/threshold.py
lib/improver/wxcode/weather_symbols.py
lib/improver/wxcode/wxcode_decision_tree.py
lib/improver/wxcode/wxcode_decision_tree_global.py
tests/improver-wxcode/01-help.bats
tests/improver-wxcode/02-basic.bats
tests/improver-wxcode/03-native_units.bats
tests/improver-wxcode/04-global.bats
tests/improver-wxcode/05-insufficient-files.bats

Revert "Impro-1121: Rename probability cubes - 1"

---

lib/improver/tests/feels_like_temperature/test_calculate_apparent_temperature.py
lib/improver/tests/feels_like_temperature/test_calculate_feels_like_temperature.py
lib/improver/tests/feels_like_temperature/test_calculate_wind_chill.py
lib/improver/tests/generate_ancillaries/test_GenerateTopographicZoneWeights.py
lib/improver/tests/utilities/test_save.py

Update unit test cube creation: feels like temperature & generate ancillaries

---

lib/improver/tests/utilities/test_filename.py
lib/improver/utilities/filename.py

Addresses part of #663 
Description
As part of #663, this adds support for a filename to be generated that contains an accumulation period. The resulting filename when it is specified that a period will be included will contain an additional period identifier of the format "PT01H" or "PT15M".
Testing:

Update filename construction to include accumulation period

---

lib/improver/tests/set_up_test_cubes.py
lib/improver/tests/test_set_up_test_cubes.py
lib/improver/tests/utilities/test_TemporalInterpolation.py
lib/improver/tests/utilities/test_load.py

Corrected wrong order of lat / lon in unit test cube setup.
Testing:

Corrected location in cube setup utilities and fixed dependent tests.

---

.gitignore
bin/improver
bin/improver-tests

and also adding atom .nfs files to gitignore
Description
Testing:

Adding licence messages to improver and improver tests

---

.travis.yml
lib/improver/cli/ensemble_calibration.py
lib/improver/cli/estimate_emos_coefficients.py
lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
tests/improver-ensemble-calibration/00-null.bats
tests/improver-ensemble-calibration/01-help.bats
tests/improver-ensemble-calibration/07-current_forecast_percentiles.bats
tests/improver-ensemble-calibration/09-current_forecast_rebadged_percentiles.bats
tests/improver-estimate-emos-coefficients/00-null.bats
tests/improver-estimate-emos-coefficients/01-help.bats
tests/improver-estimate-emos-coefficients/02-gaussian.bats
tests/improver-estimate-emos-coefficients/03-trunc_gaussian.bats
tests/improver-estimate-emos-coefficients/04-units.bats
tests/improver-estimate-emos-coefficients/05-predictor_of_mean.bats

This reverts commit 21437b7e1eb5fa741d9bd718aab1387d18287c2c.

Revert "Modifications to EMOS related to using all realizations as the predictor (#865)"

---

lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/threshold.py

Addresses #833 
Updates BasicThreshold plugin to output newly formatted threshold coordinate.  New unit tests.  Suite has been tested and new CLI test outputs generated.
Testing:

Impro1122 create new threshold coord

---

lib/improver/tests/threshold/test_BasicThreshold.py
lib/improver/threshold.py

Addresses #833 
Changes were made to https://github.com/metoppv/improver/pull/869 that made the code less maintainable and more prone to future problems.  This PR reverts those changes.
Testing:

Fixed code design issue added in PR 869

---

lib/improver/cli/spot_extract.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_utilities.py
lib/improver/nbhood/circular_kernel.py
lib/improver/percentile.py
lib/improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_GeneratePercentilesFromMeanAndVariance.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_RebadgePercentilesAsMembers.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ResamplePercentiles.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_ensemble_copula_coupling_utilities.py
lib/improver/tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py
lib/improver/tests/percentile/test_PercentileConverter.py
lib/improver/tests/set_up_test_cubes.py
lib/improver/tests/test_set_up_test_cubes.py
lib/improver/tests/utilities/test_cube_checker.py
lib/improver/tests/utilities/test_load.py
lib/improver/tests/wind_calculations/wind_gust_diagnostic/test_WindGustDiagnostic.py
lib/improver/threshold.py
lib/improver/utilities/load.py

Impro 1161 correct coordinate name and units

---

lib/improver/blending/weights.py
lib/improver/tests/blending/weights/test_ChooseWeightsLinear.py

Removed unwanted scalar coordinates and attributes from weights cube

---

lib/improver/tests/utilities/test_load.py
lib/improver/tests/utilities/test_save.py
lib/improver/utilities/save.py

Added check for "unknown" units in the IMPROVER save wrapper

---

lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
lib/improver/tests/ensemble_copula_coupling/ensemble_copula_coupling/test_EnsembleReordering.py

Addresses IMPRO-1206
Description
Testing:
CLA

Impro 1206 remove cubelist support from ecc

---

lib/improver/cli/apply_emos_coefficients.py
lib/improver/cli/estimate_emos_coefficients.py
lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/ensemble_calibration/ensemble_calibration_utilities.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ApplyCoefficientsForEnsembleCalibration.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
lib/improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py

This will make it clearer to developers which methods are the ones 
designed to be called from CLIs
Addresses IMPRO-1206
Testing:

Renamed existing methods as process method.

---

lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/ensemble_calibration/ensemble_calibration_utilities.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling.py
lib/improver/ensemble_copula_coupling/ensemble_copula_coupling_utilities.py

Updated ensemble calibration and ecc docstrings.

---

lib/improver/utilities/save.py
tests/improver-gradient/02-basic.bats

Description :  Bug fix to chunksize to improve speed of processing.
Testing:

IMPRO1214 Bug fix to chunksize to improve speed of processing.

---

lib/improver/cli/wind_gust_diagnostic.py
lib/improver/ensemble_calibration/ensemble_calibration.py
lib/improver/nowcasting/accumulation.py
lib/improver/utilities/cube_metadata.py
lib/improver/utilities/temporal.py

Fixes all current raised Sphinx warnings. This is a periodic PR to tidy up sphinx warnings that creep in over time.
Testing:

The latest round of sphinx fixes.

---

lib/improver/ensemble_calibration/ensemble_calibration.py

Simple formatting fix.
Testing:

Fix missed pycodestyle objection to a sphinx math section.

---

lib/improver/tests/utilities/test_mathematical_operations.py
lib/improver/utilities/mathematical_operations.py

Description
Update the docstrings in the integration plugin to clarify that it only integrates positive values.
Testing:

Update docstrings in integration plugin to clarify restriction

---

lib/improver/cli/weighted_blending.py
tests/improver-weighted-blending/01-help.bats

Updated help strings to correct references to non-linear scaling value.

Fixed help string.

---

lib/improver/tests/utilities/test_cli_utilities.py
lib/improver/utilities/cli_utilities.py

Added more tests to test cli_utilities.
Changed the docstrings in cli_utilites to account for input of None.
Testing:

IMPRO-1343: Added tests for cli_utilities.

---

lib/improver/tests/utilities/test_cube_metadata.py
lib/improver/utilities/cube_metadata.py

Added support for "between_thresholds" to cube utilities.

---

lib/improver/cli/between_thresholds.py
tests/improver-between-thresholds/00-null.bats
tests/improver-between-thresholds/01-help.bats
tests/improver-between-thresholds/02-basic.bats
tests/improver-between-thresholds/03-units.bats

Added CLI to calculate probabilities of occurrence between thresholds.
Testing:

Between thresholds cli

---

CONTRIBUTING.md
lib/improver/tests/wxcode/wxcode/test_cli_wxcode.py

Added Wxcode CLI Pytest

---

CONTRIBUTING.md
lib/improver/tests/wind_calculations/wind_gust_diagnostic/test_cli_wind_gust_diagnostic.py

Added acceptance tests for the wind gust diagnostic cli.
Testing:
CLA

Wind gust cli acceptance tests

---

lib/improver/cli/feels_like_temp.py
lib/improver/tests/acceptance/test_feels_like_temp.py

Description
Testing:
I have made the small changes required to convert feels like temperature to clize and made sure the tests all run fine.

Changes to convert feels like temperature to clize.

---

lib/improver/cli/weighted_blending.py
lib/improver/tests/acceptance/test_weighted_blending.py

Clizify weighted blending CLI

---

lib/improver/cli/apply_lapse_rate.py
lib/improver/tests/acceptance/test_apply_lapse_rate.py

Clize applied to apply-lapse-rate CLI

---

lib/improver/cli/create_grid_with_halo.py
lib/improver/tests/acceptance/test_create_grid_with_halo.py

Applies Clize to create-grid-with-halo CLI.
Testing:

Clizes create-grid-with-halo

---

lib/improver/cli/create_grid_with_halo.py
lib/improver/tests/acceptance/test_create_grid_with_halo.py

Convert create-grid-with-halo CLI to clize

---

lib/improver/blending/weighted_blend.py
lib/improver/cli/time_lagged_ensembles.py
lib/improver/metadata/forecast_times.py
lib/improver/tests/acceptance/test_time_lagged_ensembles.py
lib/improver/tests/metadata/test_forecast_times.py
lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py
lib/improver/utilities/time_lagging.py

Clizefied time lagging CLI and did some cleaning up.
Didn't move code block into plugin for the moment as this would require extensions to unit tests, which are being dealt with in another PR.
Testing:

Clize time lagging (2)

---

lib/improver/cli/wet_bulb_temperature.py
lib/improver/tests/acceptance/test_wet_bulb_temperature.py

Wet-bulb temperature modified to use clize.
Testing:

Clize wet-bulb-temperature

---

lib/improver/cli/uv_index.py
lib/improver/tests/acceptance/test_uv_index.py

IMPRO-1521 subtask IMPRO-1531.
Testing:

clize changes for uv-index

---

lib/improver/cli/phase_change_level.py
lib/improver/tests/acceptance/test_phase_change_level.py

Clize phase-change-level

---

lib/improver/cli/wet_bulb_temperature_integral.py
lib/improver/psychrometric_calculations/psychrometric_calculations.py
lib/improver/tests/acceptance/test_wet_bulb_temperature_integral.py

Clize wet-bulb-temperature-integral

---

lib/improver/cli/wind_direction.py
lib/improver/tests/acceptance/test_wind_direction.py

Clize wind direction

---

lib/improver/cli/apply_emos_coefficients.py
lib/improver/tests/acceptance/test_apply_emos_coefficients.py

Convert apply-emos-coefficients to clize

---

lib/improver/cli/blend_adjacent_points.py
lib/improver/tests/acceptance/test_blend_adjacent_points.py

Convert blend-adjacent-points CLI to use clize

---

lib/improver/cli/apply_emos_coefficients.py
lib/improver/cli/blend_adjacent_points.py
lib/improver/cli/threshold.py

Fix pycodestyle errors

---

lib/improver/cli/spot_extract.py
lib/improver/tests/acceptance/test_spot_extract.py

Migrates spot-extract to use Clize.

---

lib/improver/cli/generate_topography_bands_mask.py
lib/improver/cli/generate_topography_bands_weights.py
lib/improver/generate_ancillaries/generate_ancillary.py
lib/improver/tests/acceptance/test_generate_topography_bands.py

I simplified the CLIs by removing the checking for existing files in the destination location, as we do not do this with any other CLIs.  As such the behaviour is to create the requested output even if a file exists at the destination path.
Testing:

Clize topographic band CLIs

---

lib/improver/cli/between_thresholds.py
lib/improver/tests/acceptance/test_between_thresholds.py

between-thresholds CLI to clize

---

lib/improver/cli/generate_landmask_ancillary.py
lib/improver/tests/acceptance/test_generate_landmask_ancillary.py

generate-landmask-ancillary CLI using clize

---

lib/improver/cli/percentiles_to_probabilities.py
lib/improver/tests/acceptance/test_percentiles_to_probabilities.py

Note, I've moved quite a lot of the docstring stuff around. I think it renders ok when you do it help on the command line now, but it would be worth checking in review.
Testing:
CLA

Impro 1497 clize percentiles to probabilities

---

lib/improver/cli/neighbour_finding.py
lib/improver/tests/acceptance/test_neighbour_finding.py

neighbour-finding CLI to clize

---

lib/improver/cli/extend_radar_mask.py
lib/improver/tests/acceptance/test_extend_radar_mask.py

- The order that the arguments go into the cli are not the other way around.
Testing:

IMPRO-1534: convert extend radar mask to use clize

---

lib/improver/cli/wxcode.py
lib/improver/tests/acceptance/test_wxcode.py
lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
lib/improver/wxcode/wxcode_utilities.py

wxcode CLI to clize

---

lib/improver/cli/update_grid_metadata.py
lib/improver/metadata/amend.py
lib/improver/tests/acceptance/test_update_grid_metadata.py

**CLI is soon to be removed**
Testing:

update-grid-metadata CLI to clize

---

lib/improver/cli/temporal_interpolate.py
lib/improver/tests/acceptance/test_temporal_interpolate.py

* CLI now outputs `CubeList` into a single file.
**Need to update one of the KGOs to reflect this change**
Testing:

temporal-interpolate CLI to clize

---

lib/improver/cli/nbhood_land_and_sea.py
lib/improver/tests/acceptance/test_nbhood_land_and_sea.py

Converting nbhood-land-and-sea to clize, in the tests, the intermediate output needing changing name and the cube needed moving to the front of the list.
Testing:

IMPRO-1516: clize nbhood land sea

---

lib/improver/cli/nbhood.py
lib/improver/cli/nbhood_land_and_sea.py
lib/improver/nbhood/__init__.py
lib/improver/tests/acceptance/test_nbhood.py
lib/improver/tests/nbhood/test_init.py

This change includes the removal of the recursive filter options from the nbhood CLI and all associated tests.
Testing:

IMPRO-1539: clizify nbhood

---

lib/improver/tests/acceptance/test_generate_orographic_alphas.py

Very small change to update the test to reflect usage which is compatible with the recursive filter CLI.

Update orographic alphas test

---

lib/improver/cli/nowcast_accumulate.py
lib/improver/tests/acceptance/test_nowcast_accumulate.py

Use semi-lagrangian backward extrapolation in nowcast feature branch accumulations.
Testing:

Update accumulate in nowcast feature branch

---

lib/improver/cli/nbhood.py
lib/improver/cli/nbhood_iterate_with_mask.py
lib/improver/cli/nbhood_land_and_sea.py
lib/improver/nbhood/__init__.py
lib/improver/tests/acceptance/test_nbhood.py
lib/improver/tests/nbhood/test_init.py

Changes following an inadvertently skipped review.
Testing:

nbhood clizification tidy-up

---

.travis.yml
bin/improver-tests
lib/improver/cli/recursive_filter.py
lib/improver/tests/acceptance/test_recursive_filter.py

Builds on top of @Katie-Howard's PR and supersedes it - https://github.com/metoppv/improver/pull/1051
Testing:

Convert recursive-filter CLI to use clize

---

lib/improver/tests/metadata/test_forecast_times.py
lib/improver/tests/set_up_test_cubes.py
lib/improver/tests/test_set_up_test_cubes.py
lib/improver/tests/utilities/cube_manipulation/test_enforce_coordinate_ordering.py
lib/improver/utilities/cube_manipulation.py
lib/improver/utilities/load.py
lib/improver/utilities/pad_spatial.py

Refactored `enforce_coordinate_ordering` to remove unnecessary complexity and enforce better encapsulation.
Testing:

Refactor cube manipulation

---

lib/improver/cli/recursive_filter.py

Fix style issue in clize branch

---

improver/cli/__init__.py
improver_tests/acceptance/acceptance.py

Fix no error exit on wrong option

---

.github/workflows/tests.yml

Switch on GitHub Actions for PRs

---

improver/cli/__init__.py
improver/cli/estimate_emos_coefficients.py
improver_tests/acceptance/test_estimate_emos_coefficients.py

Revert "Alter behaviour of estimate-emos-coefficients CLI when either historic forecasts or truths missing"

---

improver/utilities/mathematical_operations.py
improver_tests/set_up_test_cubes.py
improver_tests/utilities/test_mathematical_operations.py

Reworked integration plugin to use new cube creation utility

---

improver/utilities/mathematical_operations.py
improver_tests/acceptance/test_wet_bulb_temperature_integral.py
improver_tests/utilities/test_mathematical_operations.py

Integration plugin can now deal with multiple realizations
Testing:

Impro1584 wbti bug

---

improver/utilities/compare.py
improver_tests/utilities/test_compare.py

Fixed and added unit test for acceptance test data recreation where the difference is missing attributes on the new output file.
Testing:

Who watches the watchers

---

improver_tests/acceptance/test_phase_change_level.py
improver_tests/acceptance/test_phase_probability.py
improver_tests/acceptance/test_sleet_probability.py
improver_tests/acceptance/test_wet_bulb_temperature_integral.py

Removed chain from psychrometric acceptance tests

---

improver/utilities/compare.py
improver_tests/acceptance/acceptance.py

Fixed to:
- Recreate KGO in non-IMPROVER_TESTS directory
- Report difference rather than raising TypeError when comparing datatypes
Unfortunately I can't figure out how to unit test either of those things within the framework available - at least not quickly.

More acceptance test bugs

---

improver/ensemble_copula_coupling/ensemble_copula_coupling.py
improver/generate_ancillaries/generate_ancillary.py
improver/wind_calculations/wind_downscaling.py
improver_tests/calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py
improver_tests/calibration/utilities/test_utilities.py
improver_tests/nowcasting/forecasting/test_CreateExtrapolationForecast.py
improver_tests/percentile/test_PercentileConverter.py
improver_tests/spotdata/spotdata/test_NeighbourSelection.py
improver_tests/threshold/test_BasicThreshold.py
improver_tests/utilities/test_save.py
improver_tests/wxcode/wxcode/test_WeatherSymbols.py
improver_tests/wxcode/wxcode/test_utilities.py

IMPRO-1595: Fix pylint errors.

---

improver/cli/nowcast_optical_flow.py
improver/convection.py
improver/nowcasting/optical_flow.py
improver/orographic_enhancement.py
improver/wxcode/utilities.py
improver/wxcode/weather_symbols.py
improver_tests/acceptance/test_nowcast_optical_flow.py
improver_tests/convection/test_DiagnoseConvectivePrecipitation.py
improver_tests/metadata/test_utilities.py
improver_tests/nowcasting/optical_flow/test_OpticalFlow.py
improver_tests/nowcasting/optical_flow/test_generate_optical_flow_components.py
improver_tests/orographic_enhancement/test_OrographicEnhancement.py
improver_tests/wxcode/wxcode/test_WeatherSymbols.py
improver_tests/wxcode/wxcode/test_utilities.py

Cube creation for new diagnostic plugins that don't require level 3 blending:
- Orographic enhancement
- Weather symbols
- Convection
- Optical flow (nowcast)
Testing:

Cube creation not blendable

---

.github/workflows/tests.yml
environment.yml

Caches tests between runs by just caching the conda env
For discussion as alternative to #1127

Cache Github actions conda env between test runs

---

improver/wxcode/wxcode_decision_tree.py
improver_tests/wxcode/wxcode/test_WeatherSymbols.py

The purpose of this PR is to change the lightning probability threshold used in the weather symbol tree to 0.3 from 0.5. Also required was modifying the unit and acceptance tests to ensure this change is noticeable.
In addition I have removed a lot of duplicate cube set-up code. I have marked all the "new code" with comments, the rest is just slight refactoring.
Testing:

IMPRO-974: Modify lightning threshold and update tests

---

improver/cli/combine.py
improver/cube_combiner.py
improver/nowcasting/accumulation.py
improver/utilities/cube_manipulation.py
improver_tests/acceptance/test_combine.py
improver_tests/cube_combiner/test_CubeCombiner.py
improver_tests/utilities/cube_manipulation/test_expand_bounds.py

Determines coordinates to be expanded automatically, and uses boolean argument to determine whether to use the upper (default) or midpoint as the new coordinate point.
Testing:

Combine expand bounds

---

improver/utilities/compare.py
improver_tests/acceptance/acceptance.py
improver_tests/acceptance/test_apply_emos_coefficients.py
improver_tests/acceptance/test_orographic_enhancement.py
improver_tests/utilities/test_compare.py

This PR adds more unit tests for the comparison code.
It also refactors the comparison code to work with sets of groups, variables and dimensions. Working with sets instead of if/else or try/except branches reduces the number of possible paths through the code and makes it easier to achieve a high percentage of lines covered by unit tests.
Testing:

Additional tests for compare tool

---

improver/blending/weighted_blend.py
improver/ensemble_copula_coupling/ensemble_copula_coupling.py
improver/lapse_rate.py
improver/utilities/cube_manipulation.py
improver/utilities/mathematical_operations.py
improver/utilities/pad_spatial.py
improver_tests/lapse_rate/test_LapseRate.py

- Tidied up lapse rate plugin using `np.squeeze`
- Condensed an often-used one-liner into a utility function
Testing:

Fix array dimensions hack

---

improver/cli/nowcast_extrapolate.py
improver_tests/acceptance/test_nowcast_extrapolate.py

Revert "Pass multiple orographic enhancement files to nowcast-extrapolate CLI"

---

improver/cli/merge.py
improver_tests/acceptance/test_merge.py

Description
This PR:
* Adds a merge CLI that merges multiple files into a single file.
* Adds associated acceptance tests.
Testing:

Edits to add a merge CLI and associated acceptance tests

---

improver/psychrometric_calculations/psychrometric_calculations.py

Alternative to #1176 and #1177 without numba
Testing:

speed up psychrometric calculations

---

improver/blending/calculate_weights_and_blend.py
improver/cli/nbhood.py
improver/nbhood/circular_kernel.py
improver/nbhood/square_kernel.py
improver/orographic_enhancement.py
improver/psychrometric_calculations/psychrometric_calculations.py
improver/utilities/pad_spatial.py
improver/utilities/spatial.py
improver_tests/nbhood/circular_kernel/test_CircularNeighbourhood.py
improver_tests/nbhood/circular_kernel/test_GeneratePercentilesFromACircularNeighbourhood.py
improver_tests/nbhood/circular_kernel/test_check_radius_against_distance.py
improver_tests/nbhood/circular_kernel/test_circular_kernel.py
improver_tests/nbhood/square_kernel/test_SquareNeighbourhood.py
improver_tests/utilities/test_spatial.py
improver_tests/wind_calculations/wind_direction/test_WindDirection.py

The name change is in the second to last commit so easily undoable
renamed `convert_distance_into_number_of_grid_cells` to `distance_to_number_of_grid_cells`
- Moved the checking of the size of the radius against the distance into its own function.
-  part of "circular_kernal.py"
-  called `check_radius_against_distance`
- Simplified the error checking
- Renamed `int_grid_cells` to `return_int` for clarity
- Moved axis to the end of the function arguments
- `max_distance_in_grid_cells=MAX_DISTANCE_IN_GRID_CELLS` is first kwarg and called positionally where needed with the obvious constant name
- Circular Kernel
- Renamed `fullranges` to `full_ranges` to conform to python snake case standards
- No longer takes a tuple of "x" and "y" as they were always the same.
- calculate `area` the use …

IMPRO-1403: Update usage of convert_distance_into_number_of_grid_cells

---

improver/__init__.py
improver_tests/cli/test_init.py

Ban on heavy modules at cli import

---

CONTRIBUTING.md
improver_tests/acceptance/test_phase_change_level.py

Refactored the phase-change-level test, moving the code into a common function, then calling this function from the test_ functions with the relevant parameter.
Testing:
CLA

Refactored phase-change-level tests

---

improver/calibration/reliability_calibration.py
improver/cli/apply_reliability_calibration.py
improver_tests/acceptance/test_apply_reliability_calibration.py

A new CLI and acceptance test for the application of reliability calibration.
Testing:

IMPRO-1507: A CLI to apply reliability calibration

---

improver/utilities/load.py
improver_tests/utilities/test_load.py

Clean up and remove unused functionality, make `load_cube` a thin wrapper around `load_cubelist`.

refactor cube loading code

---

improver/between_thresholds.py
improver/calibration/__init__.py
improver/cube_combiner.py
improver/ensemble_copula_coupling/constants.py
improver/spotdata/neighbour_finding.py
improver/threshold.py
improver/utilities/mathematical_operations.py
improver/utilities/rescale.py

A tidy up of some string concatinations. 
Mostly because of the [between_thresholds](improver/between_thresholds.py) use of multiple `+`.
Testing:

Fade to Black

---

doc/source/about.rst

Added info about sample data to external documentation

---

improver_tests/metadata/test_probabilistic.py
improver_tests/wind_calculations/wind_components/test_ResolveWindComponents.py
improver_tests/wind_calculations/wind_direction/test_WindDirection.py
improver_tests/wind_calculations/wind_gust_diagnostic/test_WindGustDiagnostic.py

Wind unit tests

---

.github/workflows/tests.yml
improver/utilities/mathematical_operations.py
improver/wxcode/weather_symbols.py

Some minor changes to resolve warnings in the sphinx documentation build process.
Also set warnings to become errors in github actions sphinx build so that these are noticed and fixed before PR merging in future.
Testing:

Sphinx doc fixes and better CI warnings

---

improver/cli/nowcast_optical_flow.py
improver/cli/nowcast_optical_flow_perturbation.py
improver_tests/acceptance/test_nowcast_optical_flow_perturbation.py

New CLI to calculate optical flow components as perturbations from a previous nowcast.
Testing:

Two step advection

---

improver/cli/recursive_filter.py
improver_tests/cli/test_init.py

test if cli help writes to sys.stderr

---

improver/blending/calculate_weights_and_blend.py
improver/cli/convection_ratio.py
improver/convection.py
improver_tests/acceptance/SHA256SUMS
improver_tests/acceptance/test_convection_ratio.py
improver_tests/convection/test_ConvectionRatioFromComponents.py

Adds convection-ratio CLI and ConvectionRatioFromComponents plugin to derive the convection ratio from the convective and dynamic precipitationi rate components.
Testing:

Impro 1754 showers cli

---

improver/utilities/rescale.py

Fix an issue with Sphinx building

---

improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py

Description:
Updated the unit tests within the recursive filter folder for neighbourhood processing in order to replace current use of set_up_cube with newer functions.
Testing:
CLA

Impro 1669 part3

---

improver_tests/nbhood/square_kernel/test_SquareNeighbourhood.py

Description:
Updated unit tests within the square kernel folder for neighbourhood processing.
Testing:
CLA

Updated unit tests within the square kernel folder

---

improver/wxcode/weather_symbols.py
improver_tests/wxcode/wxcode/test_WeatherSymbols.py

- If a masked data value is encountered when striding the weather symbols decision trees, the resulting weather code is now also masked rather than that node decision being False.
- Tests updated to ensure that masked data arrays are correctly checked.
Testing:

WeatherSymbols handles masked data.

---

improver/blending/spatial_weights.py
improver_tests/blending/spatial_weights/test_SpatiallyVaryingWeightsFromMask.py

Fixed tiny bug in spatial weights unit tests

---

improver/calibration/ensemble_calibration.py
improver_tests/calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py

Small update to the emos estimate coefficients code, see notebook (https://github.com/MetOffice/improver_aux/pull/232) for details
Testing:

Construct emos coeffs update

---

envs/environment_py36_iris22.yml

Description
Remove duplicated scipy dependency.
Testing:
CLA

Remove duplicated dependency.

---

CONTRIBUTING.md
improver/utilities/neighbourhood_tools.py
improver_tests/utilities/test_neighbourhood_tools.py

Addresses #1386.
Bandit flags assert statements as a security issue. This PR replaces assert statements with exceptions.
Description
Testing:
- [ X ] Ran tests and they passed OK

Replace assert with exception

---

doc/Makefile
doc/source/conf.py
improver/__init__.py
setup.cfg
setup.py

Install will not work (via `pip install`) on a clean/empty environment due to difficulties installing iris from pip (see https://github.com/SciTools/iris/issues/3777). Ultimate goal is to put package on conda-forge
cc @tjtg @dmentipl 
Testing:
- [N/A] Ran tests and they passed OK
- [N/A] Added new tests for the new feature(s)
CLA
- [N/A] If a new developer, signed up to CLA

Add setup files 

---

improver/blending/utilities.py
improver/blending/weighted_blend.py
improver/cli/wind_downscaling.py
improver/utilities/mathematical_operations.py
improver/utilities/spatial.py

Ran automated import optimization from Pycharm. This PR is the result.
Addresses unused import that slipped through #1448 
Testing:

Removes unused import statements

---

improver_tests/acceptance/test_map_to_timezones.py

Missed rearranging the args to match the new interface
Description
Testing:

rearranged args

---

CONTRIBUTING.md
doc/source/Running-at-your-site.rst
doc/source/about.rst

Documentation fixes for broken links

remove or fix broken links in documentation

---

improver/cli/regrid.py
improver/regrid/landsea.py
improver_tests/regrid/test_AdjustLandSeaPoints.py

Addresses #1579
Description
- Realises data for `regrid --regrid-mode` calls.
- Cache for nearest neighbour calls.
Testing:
CLA

ENH: Optimisation of `regrid --regrid-mode`

---

improver/calibration/dataframe_utilities.py
improver/cli/estimate_emos_coefficients_from_table.py
improver/cli/regrid.py
improver/regrid/landsea.py
improver_tests/acceptance/test_estimate_emos_coefficients_from_table.py
improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py
improver_tests/regrid/test_AdjustLandSeaPoints.py

Adds the hotfix PRs for IMPROVER release 1.0.1 into master.
PRs are described on the IMPROVER 1.0.1 release page:
https://github.com/metoppv/improver/releases/tag/1.0.1

Hotfix branch 1.0.1

---

improver_tests/ensemble_copula_coupling/test_utilities.py

Add tests for `interpolate_multiple_rows_same_x` as suggested in #1623 
Testing:
- [ x] Ran tests and they passed OK
- [ x] Added new tests for the new feature(s)

Add tests to resolve #1623

---

improver/calibration/ensemble_calibration.py
improver/cli/apply_emos_coefficients.py
improver_tests/calibration/ensemble_calibration/test_CalibratedForecastDistributionParameters.py

Merge back the 1.0.3 tag and branch. 
Adds time mismatch tolerating for apply emos (#1628).

Merge back of Hotfix_branch_1.0.3

---

improver/blending/blend_across_adjacent_points.py
improver/blending/weights.py
improver/cli/blend_adjacent_points.py

Closes https://github.com/metoppv/mo-blue-team/issues/115
Description:
The doc strings relating to the triangle time blending functionality had some errors in and needed updating so that they were consistent across the multiple related files.
Testing:

Expanding on triangle time blending doc strings.

---

improver/feels_like_temperature.py

During the course of documenting the feels like temperature I noticed a small typo, this PR fixes that.
Testing:
CLA

Doc string typo amendment in Feels Like Temperature plugin

---

improver_tests/test_source_code.py

The developer_tools directory does not currently contain an `__init__.py` file, resulting in it not being packaged by pip/conda. The lack of this module then causes many tests to fail with import errors when run against a built/installed package. Resolve this by adding an empty `__init__.py` file.
Testing:

Add missing init files

---

improver/psychrometric_calculations/psychrometric_calculations.py
improver_tests/psychrometric_calculations/test_dry_adiabatic_methods.py

Closes #1730 
Description and rationale in #1730
Also modifies logic in `WetBulbTemperature` in the same file, because I couldn't help writing the same logic in a manner that seems simpler to me.
Testing:

Add methods for dry adiabatic changes

---

improver/cube_combiner.py

This PR adds realization slicing to the cube combiner for all the standard operations (not extending to multiplication). This reduces the memory used when combining multi-realization data which became prohibitive in the creation of the extreme precipitation accumulation diagnostics.
I tested this change using the data that was causing my suite to fail. This is a combination of 12 files each corresponding to a 1-hour period to find the maximum over a 12 hour period. There is another case in my suite that combines 24 1-hour files to build a 24-hour period (so even more extreme). Each file has the following shape:
`(realization: 15; threshold: 7; radius_of_vicinity: 2; Y: 970; X: 1042)`
This understandably causes some memory issues if the data is not sliced up in a more friendly manner. …

MOBT-289: Realization slicing in cube combiner

---

improver/psychrometric_calculations/cloud_top_temperature.py

Uses the existing mask to determine which columns need further processing. This thins the data more and more as the columns are ascended and results in a 3x speed-up for the MOGREPS-G global domain.
Testing:

Speeds up the cloud-top-temperature CLI

---

doc/source/index.rst
doc/source/metadata/Introduction.rst
doc/source/metadata/Principles.rst
doc/source/metadata/Probabilities.rst
doc/source/metadata/Statistics.rst

Description
An initial draft of the Probabilistic Information metadata document (a re-working of information currently hosted on an internal Met Office site). This creates a Probabilities.rst file.

Updated metadata documentation part 3 - probabilities

---

improver/spotdata/apply_lapse_rate.py

Following https://github.com/metoppv/improver/pull/1879, I want to refactor this code so that it is easier to see what is going on.
Testing:

Refactors SpotLapseRateAdjust so that the two pathways are easier to follow.

---

.github/workflows/ci.yml

Following on from https://github.com/metoppv/improver/pull/1890
Since #1890 was successful, I'm updating the CI to do the same.

CI consistency with scheduled gh actions

---

improver_tests/calibration/dataframe_utilities/test_dataframe_utilities.py

Closes #1896 
Description
This PR updates some pandas syntax in `test_dataframe_utilities.py` to avoid failures in GitHub Actions: https://github.com/metoppv/improver/actions, including within the checks on each PR.
Testing:

Minor edits following release of pandas 2.0.0

---

improver/utilities/solar.py
improver_tests/utilities/solar/test_DayNightMask.py

The day night mask plugin assumes a 2-D spatial grid at present. This PR modifies the plugin to work with an irregular grid defined with latitude and longitude coordinates, such as is found in spot data.
Unit test have been added.
Testing:

MOBT-494: Modify day night mask to work with spot data.

---

doc/source/index.rst
doc/source/metadata/Working-with-Metadata.rst

Description: Adds a new "Developer guide to working with metadata" section to provide details on working with the metadata when developing the code. This mainly the Working-with-Metadata.rst file.

Updated metadata documentation part 5 - Developer guide

---

.mailmap
CONTRIBUTING.md
improver/blending/weighted_blend.py
improver/regrid/bilinear.py
improver/utilities/temporal_interpolation.py
improver/wind_calculations/wind_direction.py
improver_tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py
improver_tests/utilities/test_TemporalInterpolation.py

Description
Use the Met Office's "complex number wind direction" code to process wind directions when doing model blending and temporal interpolation.
Testing:

Wind direction changes

---

doc/source/extended_documentation/categorical/build_a_decision_tree.rst
improver/categorical/decision_tree.py
improver/categorical/utilities.py
improver_tests/categorical/decision_tree/__init__.py
improver_tests/categorical/decision_tree/test_ApplyDecisionTree.py
improver_tests/categorical/test_utilities.py

This PR makes some further changes to the wx symbols plugin so it can work with a decision tree using deterministic inputs. This PR builds on PR https://github.com/metoppv/improver/pull/1944 which refactored the code to work with any decision tree. This branch points at master but can't be merged before the previous PR.
I have attempted to write this code so that it doesn't require any changes to the current weather symbols decision tree. This is partially to limit the number of changes that need to be made but also so I can show that the changes I've made don't effect the existing decision tree.
Testing:

Categorical plugin accepts deterministic conditions

---

improver/cli/apply_mask.py
improver/utilities/mask.py
improver_tests/acceptance/SHA256SUMS
improver_tests/acceptance/test_apply_mask.py
improver_tests/utilities/test_mask.py

Ticket: https://metoffice.atlassian.net/browse/EPPT-1305
Acceptance test data: https://github.com/metoppv/improver_test_data/pull/50
This PR adds the ability to apply a mask to a cube 
Testing:

Apply mask to cube

---

doc/source/about.rst
doc/source/frontpage.rst

Related to https://github.com/metoppv/mo-blue-team/issues/787
This PR modifies some of the documentation on the improver ReadTheDocs site. The about.rst and frontpage.rst files have been updated to better reflect the current approach.

Update high-level improver documentation on ReadTheDocs

---

improver/cli/cubelist_extract.py
improver/utilities/cube_extraction.py
improver_tests/acceptance/SHA256SUMS
improver_tests/acceptance/test_cubelist_extract.py
improver_tests/utilities/cube_extraction/test_cube_extraction.py

EPP_ticket: https://metoffice.atlassian.net/browse/EPPT-1799
acceptance_test_data: https://github.com/metoppv/improver_test_data/pull/59
Adds in the ability to extract a cube from a cubelist based on the provided name
Testing:

Adds cli and test to extract a cube from a cubelist

---

improver/cli/cubelist_extract.py
improver_tests/acceptance/test_cubelist_extract.py

Slight update to copyright statements for cubelist_extraction files
Testing:

Update copyright statement

---

improver/utilities/temporal_interpolation.py

Move period match check higher to avoid pointlessly realising data.
Testing:

Duration subdivision efficiency tweak

---

improver/threshold.py
improver/utilities/textural.py

Addresses https://github.com/metoppv/mo-blue-team/issues/939
Description
Minor edit to ensure that the threshold used in the `FieldTexture` plugin has the same dtype the values being thresholded, so that the dtype is preserved.
Testing:

Acceptance test batch 5
